// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module controller(
  input         clock,
                reset,
  input  [63:0] io_core_rs1_data,
                io_core_rs2_data,
  input  [6:0]  io_core_funct,
  input  [4:0]  io_core_inst_rd,
  input         io_core_req_val,
                io_core_req_fire,
                io_core_resp_ready,
                io_mem_req_rdy,
                io_mem_resp_val,
  input  [63:0] io_mem_resp_data,
  input  [31:0] io_comp_result,
  input         io_comp_valid,
  output        io_core_req_rdy,
  output [4:0]  io_core_resp_rd,
  output [31:0] io_core_resp_data,
  output        io_core_resp_valid,
                io_mem_req_val,
  output [6:0]  io_mem_req_tag,
  output [3:0]  io_mem_req_size,
  output [39:0] io_mem_req_addr,
  output        io_comp_enable,
  output [31:0] io_vec1_0,
                io_vec1_1,
                io_vec1_2,
                io_vec1_3,
                io_vec1_4,
                io_vec1_5,
                io_vec1_6,
                io_vec1_7,
                io_vec1_8,
                io_vec1_9,
                io_vec1_10,
                io_vec1_11,
                io_vec1_12,
                io_vec1_13,
                io_vec1_14,
                io_vec1_15,
                io_vec2_0,
                io_vec2_1,
                io_vec2_2,
                io_vec2_3,
                io_vec2_4,
                io_vec2_5,
                io_vec2_6,
                io_vec2_7,
                io_vec2_8,
                io_vec2_9,
                io_vec2_10,
                io_vec2_11,
                io_vec2_12,
                io_vec2_13,
                io_vec2_14,
                io_vec2_15,
  output        io_isHandling
);

  reg  [63:0]     vec1_head;	// @[controller.scala:60:28]
  reg  [63:0]     vec2_head;	// @[controller.scala:61:32]
  reg  [4:0]      vec1_index;	// @[controller.scala:65:29]
  reg  [4:0]      vec2_index;	// @[controller.scala:66:33]
  reg  [4:0]      vec_len;	// @[controller.scala:67:26]
  reg  [4:0]      rd_reg;	// @[controller.scala:71:25]
  reg  [31:0]     vec1_reg_0;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_1;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_2;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_3;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_4;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_5;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_6;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_7;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_8;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_9;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_10;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_11;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_12;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_13;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_14;	// @[controller.scala:74:28]
  reg  [31:0]     vec1_reg_15;	// @[controller.scala:74:28]
  reg  [31:0]     vec2_reg_0;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_1;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_2;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_3;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_4;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_5;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_6;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_7;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_8;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_9;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_10;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_11;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_12;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_13;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_14;	// @[controller.scala:75:28]
  reg  [31:0]     vec2_reg_15;	// @[controller.scala:75:28]
  reg  [31:0]     result_reg;	// @[controller.scala:76:29]
  reg             isHandling_reg;	// @[controller.scala:78:33]
  reg  [2:0]      ctrl_state;	// @[controller.scala:103:29]
  reg  [2:0]      m_state;	// @[controller.scala:107:26]
  wire            _T_110 = m_state == 3'h0;	// @[controller.scala:103:29, :107:26, :123:20]
  wire            _T_13 = m_state == 3'h1;	// @[controller.scala:107:26, :123:20, :129:25]
  wire            _finish_v1_T = vec1_index < vec_len;	// @[controller.scala:65:29, :67:26, :135:42]
  wire            _T_48 = m_state == 3'h2;	// @[controller.scala:107:26, :123:20, :146:29]
  wire            _T_61 = m_state == 3'h3;	// @[controller.scala:107:26, :123:20, :159:26]
  wire            _finish_v2_T = vec2_index < vec_len;	// @[controller.scala:66:33, :67:26, :195:42]
  wire            _GEN = _T_61 & _finish_v2_T;	// @[controller.scala:83:24, :123:20, :195:42, :198:30, :200:36]
  wire            _GEN_0 = _T_48 | ~_GEN;	// @[controller.scala:83:24, :123:20, :198:30, :200:36]
  wire            _T_109 = ctrl_state == 3'h0;	// @[controller.scala:103:29, :257:23]
  wire            _T_120 = ctrl_state == 3'h1;	// @[controller.scala:103:29, :129:25, :257:23]
  wire            _T_121 = ctrl_state == 3'h2;	// @[controller.scala:103:29, :146:29, :257:23]
  wire            _T_122 = ctrl_state == 3'h3;	// @[controller.scala:103:29, :159:26, :257:23]
  wire [3:0]      _T_52 = vec1_index[3:0] + 4'h1;	// @[controller.scala:65:29, :170:46, :171:45]
  wire [3:0]      _T_56 = vec1_index[3:0] + 4'h1;	// @[controller.scala:65:29, :170:46, :171:45, :176:45]
  wire [3:0]      _T_60 = vec1_index[3:0] + 4'h1;	// @[controller.scala:65:29, :170:46, :171:45, :182:41]
  wire [3:0]      _T_100 = vec2_index[3:0] + 4'h1;	// @[controller.scala:66:33, :170:46, :231:45]
  wire [3:0]      _T_104 = vec2_index[3:0] + 4'h1;	// @[controller.scala:66:33, :170:46, :231:45, :236:45]
  wire [3:0]      _T_108 = vec2_index[3:0] + 4'h1;	// @[controller.scala:66:33, :170:46, :231:45, :242:41]
  wire            _T_2 = ~isHandling_reg & io_core_req_val & io_core_req_fire;	// @[controller.scala:78:33, :87:28, :110:27]
  wire            _T_3 = io_core_funct == 7'h0;	// @[controller.scala:83:24, :111:29]
  wire            _GEN_1 = _T_2 & _T_3;	// @[controller.scala:60:28, :110:{27,68}, :111:{29,37}, :112:23]
  wire            _T_4 = io_core_funct == 7'h1;	// @[controller.scala:114:34]
  wire [4:0]      _odd_v1_length_T = vec_len % 5'h2;	// @[controller.scala:67:26, :154:36, :163:43]
  wire            alomst_finish_v1 = vec1_index >= vec_len - 5'h2;	// @[controller.scala:65:29, :67:26, :164:{49,59}]
  wire            _GEN_2 = _T_48 & io_mem_resp_val;	// @[controller.scala:74:28, :123:20, :165:36, :168:39]
  wire            _GEN_3 = _T_110 | _T_13 | ~_GEN_2;	// @[controller.scala:65:29, :74:28, :123:20, :165:36, :168:39]
  wire [4:0]      _odd_v2_length_T = vec_len % 5'h2;	// @[controller.scala:67:26, :154:36, :223:43]
  wire            alomst_finish_v2 = vec2_index >= vec_len - 5'h2;	// @[controller.scala:66:33, :67:26, :224:{49,59}]
  wire            _GEN_4 = m_state == 3'h4 & io_mem_resp_val;	// @[controller.scala:75:28, :107:26, :123:20, :154:36, :225:36, :228:55]
  wire            _GEN_5 = _T_110 | _T_13 | _T_48 | _T_61 | ~_GEN_4;	// @[controller.scala:66:33, :75:28, :123:20, :225:36, :228:55]
  wire            _GEN_6 = _T_109 | _T_120 | _T_121 | _T_122 | ctrl_state != 3'h4;	// @[controller.scala:103:29, :123:20, :154:36, :257:23]
  wire [7:0][2:0] _GEN_7 = {{ctrl_state}, {ctrl_state}, {ctrl_state}, {3'h0}, {io_core_resp_ready ? 3'h4 : 3'h3}, {{2'h1, io_comp_valid}}, {3'h2}, {{2'h0, _T_110 & vec2_index >= vec_len & vec1_index >= vec_len & (|vec_len)}}};	// @[controller.scala:65:29, :66:33, :67:26, :103:29, :123:20, :139:36, :146:29, :154:36, :159:26, :257:23, :260:{53,80,91,104,113}, :261:28, :263:28, :268:24, :271:33, :273:28, :275:28, :283:37, :284:28, :286:28, :290:25]
  wire [7:0][2:0] _GEN_8 = {{m_state}, {m_state}, {m_state}, {io_mem_resp_val ? 3'h3 : 3'h4}, {_finish_v2_T ? (io_mem_req_rdy ? 3'h4 : 3'h3) : 3'h0}, {io_mem_resp_val ? 3'h1 : 3'h2}, {_finish_v1_T ? (io_mem_req_rdy ? 3'h2 : 3'h1) : 3'h3}, {{2'h0, isHandling_reg & (|vec_len) & vec1_index < vec_len & vec2_index < vec_len}}};	// @[controller.scala:65:29, :66:33, :67:26, :78:33, :103:29, :107:26, :123:20, :128:{46,70,81,96,107}, :129:25, :131:25, :135:42, :137:30, :139:36, :145:38, :146:29, :148:29, :154:36, :159:26, :165:36, :188:25, :190:25, :195:42, :198:30, :206:38, :207:29, :209:29, :219:26, :225:36, :247:25, :249:25]
  always @(posedge clock) begin
    if (reset) begin
      vec1_head <= 64'h0;	// @[controller.scala:60:28]
      vec2_head <= 64'h0;	// @[controller.scala:60:28, :61:32]
      vec1_index <= 5'h0;	// @[controller.scala:65:29]
      vec2_index <= 5'h0;	// @[controller.scala:65:29, :66:33]
      vec_len <= 5'h0;	// @[controller.scala:65:29, :67:26]
      rd_reg <= 5'h0;	// @[controller.scala:65:29, :71:25]
      vec1_reg_0 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_1 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_2 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_3 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_4 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_5 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_6 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_7 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_8 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_9 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_10 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_11 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_12 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_13 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_14 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec1_reg_15 <= 32'h0;	// @[controller.scala:74:{28,36}]
      vec2_reg_0 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_1 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_2 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_3 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_4 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_5 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_6 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_7 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_8 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_9 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_10 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_11 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_12 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_13 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_14 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      vec2_reg_15 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      result_reg <= 32'h0;	// @[controller.scala:74:36, :76:29]
      isHandling_reg <= 1'h0;	// @[controller.scala:78:33]
      ctrl_state <= 3'h0;	// @[controller.scala:103:29]
      m_state <= 3'h0;	// @[controller.scala:103:29, :107:26]
    end
    else begin
      if (_GEN_3) begin	// @[controller.scala:65:29, :123:20]
        if (_GEN_1)	// @[controller.scala:60:28, :110:68, :111:37, :112:23]
          vec1_head <= io_core_rs1_data;	// @[controller.scala:60:28]
      end
      else if (alomst_finish_v1) begin	// @[controller.scala:164:49]
        if (|(_odd_v1_length_T[1:0]))	// @[controller.scala:163:{43,49}]
          vec1_head <= vec1_head + 64'h8;	// @[controller.scala:60:28, :173:48]
        else	// @[controller.scala:163:49]
          vec1_head <= vec1_head + 64'h8;	// @[controller.scala:60:28, :173:48, :178:48]
      end
      else	// @[controller.scala:164:49]
        vec1_head <= vec1_head + 64'h8;	// @[controller.scala:60:28, :173:48, :184:44]
      if (_GEN_5) begin	// @[controller.scala:66:33, :123:20]
        if (_GEN_1)	// @[controller.scala:60:28, :110:68, :111:37, :112:23]
          vec2_head <= io_core_rs2_data;	// @[controller.scala:61:32]
      end
      else if (alomst_finish_v2) begin	// @[controller.scala:224:49]
        if (|(_odd_v2_length_T[1:0]))	// @[controller.scala:223:{43,49}]
          vec2_head <= vec2_head + 64'h8;	// @[controller.scala:61:32, :173:48, :233:48]
        else	// @[controller.scala:223:49]
          vec2_head <= vec2_head + 64'h8;	// @[controller.scala:61:32, :173:48, :238:48]
      end
      else	// @[controller.scala:224:49]
        vec2_head <= vec2_head + 64'h8;	// @[controller.scala:61:32, :173:48, :244:44]
      if (_GEN_6) begin	// @[controller.scala:123:20, :257:23]
        if (_GEN_3) begin	// @[controller.scala:65:29, :123:20]
        end
        else if (alomst_finish_v1) begin	// @[controller.scala:164:49]
          if (|(_odd_v1_length_T[1:0]))	// @[controller.scala:163:{43,49}]
            vec1_index <= vec1_index + 5'h2;	// @[controller.scala:65:29, :154:36, :172:50]
          else	// @[controller.scala:163:49]
            vec1_index <= vec1_index + 5'h2;	// @[controller.scala:65:29, :154:36, :177:50]
        end
        else	// @[controller.scala:164:49]
          vec1_index <= vec1_index + 5'h2;	// @[controller.scala:65:29, :154:36, :183:46]
        if (_GEN_5) begin	// @[controller.scala:66:33, :123:20]
        end
        else if (alomst_finish_v2) begin	// @[controller.scala:224:49]
          if (|(_odd_v2_length_T[1:0]))	// @[controller.scala:223:{43,49}]
            vec2_index <= vec2_index + 5'h2;	// @[controller.scala:66:33, :154:36, :232:50]
          else	// @[controller.scala:223:49]
            vec2_index <= vec2_index + 5'h2;	// @[controller.scala:66:33, :154:36, :237:50]
        end
        else	// @[controller.scala:224:49]
          vec2_index <= vec2_index + 5'h2;	// @[controller.scala:66:33, :154:36, :243:46]
      end
      else begin	// @[controller.scala:123:20, :257:23]
        vec1_index <= 5'h0;	// @[controller.scala:65:29]
        vec2_index <= 5'h0;	// @[controller.scala:65:29, :66:33]
      end
      if (~_T_2 | _T_3 | ~_T_4) begin	// @[controller.scala:67:26, :110:{27,68}, :111:{29,37}, :114:{34,42}]
      end
      else begin	// @[controller.scala:67:26, :110:68, :111:37]
        vec_len <= io_core_rs1_data[4:0];	// @[controller.scala:67:26, :115:21]
        rd_reg <= io_core_inst_rd;	// @[controller.scala:71:25]
      end
      if (_T_110) begin	// @[controller.scala:123:20]
      end
      else if (_T_13) begin	// @[controller.scala:123:20]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len == 5'h0)) begin	// @[controller.scala:65:29, :67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_0 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len[4:1] == 4'h0)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_1 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'h3)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_2 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len[4:2] == 3'h0)) begin	// @[controller.scala:67:26, :74:28, :103:29, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_3 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'h5)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_4 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'h6)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_5 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'h7)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_6 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len[4:3] == 2'h0)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :139:36, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_7 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'h9)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_8 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'hA)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_9 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'hB)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_10 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'hC)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_11 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'hD)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_12 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'hE)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_13 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | ~(~(vec_len[4]) & vec_len < 5'hF)) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:{36,47}, :155:41]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_14 <= 32'h0;	// @[controller.scala:74:{28,36}]
        if (_finish_v1_T | vec_len[4] | vec_len[4]) begin	// @[controller.scala:67:26, :74:28, :135:42, :137:30, :152:{32,39}, :154:36]
        end
        else	// @[controller.scala:74:28, :137:30, :152:39]
          vec1_reg_15 <= 32'h0;	// @[controller.scala:74:{28,36}]
      end
      else if (_GEN_2) begin	// @[controller.scala:74:28, :123:20, :165:36, :168:39]
        if (alomst_finish_v1) begin	// @[controller.scala:164:49]
          if (|(_odd_v1_length_T[1:0])) begin	// @[controller.scala:163:{43,49}]
            if (_T_52 == 4'h0)	// @[controller.scala:154:36, :171:{45,52}]
              vec1_reg_0 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h0)	// @[controller.scala:65:29, :154:36, :170:46]
              vec1_reg_0 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'h1)	// @[controller.scala:170:46, :171:{45,52}]
              vec1_reg_1 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h1)	// @[controller.scala:65:29, :170:46]
              vec1_reg_1 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'h2)	// @[controller.scala:170:46, :171:{45,52}]
              vec1_reg_2 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h2)	// @[controller.scala:65:29, :170:46]
              vec1_reg_2 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'h3)	// @[controller.scala:170:46, :171:{45,52}]
              vec1_reg_3 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h3)	// @[controller.scala:65:29, :170:46]
              vec1_reg_3 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'h4)	// @[controller.scala:170:46, :171:{45,52}]
              vec1_reg_4 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h4)	// @[controller.scala:65:29, :170:46]
              vec1_reg_4 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'h5)	// @[controller.scala:170:46, :171:{45,52}]
              vec1_reg_5 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h5)	// @[controller.scala:65:29, :170:46]
              vec1_reg_5 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'h6)	// @[controller.scala:170:46, :171:{45,52}]
              vec1_reg_6 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h6)	// @[controller.scala:65:29, :170:46]
              vec1_reg_6 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'h7)	// @[controller.scala:170:46, :171:{45,52}]
              vec1_reg_7 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h7)	// @[controller.scala:65:29, :170:46]
              vec1_reg_7 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'h8)	// @[controller.scala:154:36, :171:{45,52}]
              vec1_reg_8 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h8)	// @[controller.scala:65:29, :154:36, :170:46]
              vec1_reg_8 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'h9)	// @[controller.scala:154:36, :171:{45,52}]
              vec1_reg_9 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'h9)	// @[controller.scala:65:29, :154:36, :170:46]
              vec1_reg_9 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'hA)	// @[controller.scala:154:36, :171:{45,52}]
              vec1_reg_10 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'hA)	// @[controller.scala:65:29, :154:36, :170:46]
              vec1_reg_10 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'hB)	// @[controller.scala:154:36, :171:{45,52}]
              vec1_reg_11 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'hB)	// @[controller.scala:65:29, :154:36, :170:46]
              vec1_reg_11 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'hC)	// @[controller.scala:154:36, :171:{45,52}]
              vec1_reg_12 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'hC)	// @[controller.scala:65:29, :154:36, :170:46]
              vec1_reg_12 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'hD)	// @[controller.scala:154:36, :171:{45,52}]
              vec1_reg_13 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'hD)	// @[controller.scala:65:29, :154:36, :170:46]
              vec1_reg_13 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (_T_52 == 4'hE)	// @[controller.scala:154:36, :171:{45,52}]
              vec1_reg_14 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (vec1_index[3:0] == 4'hE)	// @[controller.scala:65:29, :154:36, :170:46]
              vec1_reg_14 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
            if (&_T_52)	// @[controller.scala:171:{45,52}]
              vec1_reg_15 <= 32'h0;	// @[controller.scala:74:{28,36}]
            else if (&(vec1_index[3:0]))	// @[controller.scala:65:29, :170:46]
              vec1_reg_15 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :170:65]
          end
          else begin	// @[controller.scala:163:49]
            if (_T_56 == 4'h0)	// @[controller.scala:154:36, :176:{45,52}]
              vec1_reg_0 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h0)	// @[controller.scala:65:29, :154:36, :175:46]
              vec1_reg_0 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'h1)	// @[controller.scala:170:46, :176:{45,52}]
              vec1_reg_1 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h1)	// @[controller.scala:65:29, :170:46, :175:46]
              vec1_reg_1 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'h2)	// @[controller.scala:170:46, :176:{45,52}]
              vec1_reg_2 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h2)	// @[controller.scala:65:29, :170:46, :175:46]
              vec1_reg_2 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'h3)	// @[controller.scala:170:46, :176:{45,52}]
              vec1_reg_3 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h3)	// @[controller.scala:65:29, :170:46, :175:46]
              vec1_reg_3 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'h4)	// @[controller.scala:170:46, :176:{45,52}]
              vec1_reg_4 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h4)	// @[controller.scala:65:29, :170:46, :175:46]
              vec1_reg_4 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'h5)	// @[controller.scala:170:46, :176:{45,52}]
              vec1_reg_5 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h5)	// @[controller.scala:65:29, :170:46, :175:46]
              vec1_reg_5 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'h6)	// @[controller.scala:170:46, :176:{45,52}]
              vec1_reg_6 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h6)	// @[controller.scala:65:29, :170:46, :175:46]
              vec1_reg_6 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'h7)	// @[controller.scala:170:46, :176:{45,52}]
              vec1_reg_7 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h7)	// @[controller.scala:65:29, :170:46, :175:46]
              vec1_reg_7 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'h8)	// @[controller.scala:154:36, :176:{45,52}]
              vec1_reg_8 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h8)	// @[controller.scala:65:29, :154:36, :175:46]
              vec1_reg_8 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'h9)	// @[controller.scala:154:36, :176:{45,52}]
              vec1_reg_9 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'h9)	// @[controller.scala:65:29, :154:36, :175:46]
              vec1_reg_9 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'hA)	// @[controller.scala:154:36, :176:{45,52}]
              vec1_reg_10 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'hA)	// @[controller.scala:65:29, :154:36, :175:46]
              vec1_reg_10 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'hB)	// @[controller.scala:154:36, :176:{45,52}]
              vec1_reg_11 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'hB)	// @[controller.scala:65:29, :154:36, :175:46]
              vec1_reg_11 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'hC)	// @[controller.scala:154:36, :176:{45,52}]
              vec1_reg_12 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'hC)	// @[controller.scala:65:29, :154:36, :175:46]
              vec1_reg_12 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'hD)	// @[controller.scala:154:36, :176:{45,52}]
              vec1_reg_13 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'hD)	// @[controller.scala:65:29, :154:36, :175:46]
              vec1_reg_13 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (_T_56 == 4'hE)	// @[controller.scala:154:36, :176:{45,52}]
              vec1_reg_14 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (vec1_index[3:0] == 4'hE)	// @[controller.scala:65:29, :154:36, :175:46]
              vec1_reg_14 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
            if (&_T_56)	// @[controller.scala:176:{45,52}]
              vec1_reg_15 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :176:71]
            else if (&(vec1_index[3:0]))	// @[controller.scala:65:29, :175:46]
              vec1_reg_15 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :175:65]
          end
        end
        else begin	// @[controller.scala:164:49]
          if (_T_60 == 4'h0)	// @[controller.scala:154:36, :182:{41,48}]
            vec1_reg_0 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h0)	// @[controller.scala:65:29, :154:36, :181:42]
            vec1_reg_0 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'h1)	// @[controller.scala:170:46, :182:{41,48}]
            vec1_reg_1 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h1)	// @[controller.scala:65:29, :170:46, :181:42]
            vec1_reg_1 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'h2)	// @[controller.scala:170:46, :182:{41,48}]
            vec1_reg_2 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h2)	// @[controller.scala:65:29, :170:46, :181:42]
            vec1_reg_2 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'h3)	// @[controller.scala:170:46, :182:{41,48}]
            vec1_reg_3 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h3)	// @[controller.scala:65:29, :170:46, :181:42]
            vec1_reg_3 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'h4)	// @[controller.scala:170:46, :182:{41,48}]
            vec1_reg_4 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h4)	// @[controller.scala:65:29, :170:46, :181:42]
            vec1_reg_4 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'h5)	// @[controller.scala:170:46, :182:{41,48}]
            vec1_reg_5 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h5)	// @[controller.scala:65:29, :170:46, :181:42]
            vec1_reg_5 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'h6)	// @[controller.scala:170:46, :182:{41,48}]
            vec1_reg_6 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h6)	// @[controller.scala:65:29, :170:46, :181:42]
            vec1_reg_6 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'h7)	// @[controller.scala:170:46, :182:{41,48}]
            vec1_reg_7 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h7)	// @[controller.scala:65:29, :170:46, :181:42]
            vec1_reg_7 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'h8)	// @[controller.scala:154:36, :182:{41,48}]
            vec1_reg_8 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h8)	// @[controller.scala:65:29, :154:36, :181:42]
            vec1_reg_8 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'h9)	// @[controller.scala:154:36, :182:{41,48}]
            vec1_reg_9 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'h9)	// @[controller.scala:65:29, :154:36, :181:42]
            vec1_reg_9 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'hA)	// @[controller.scala:154:36, :182:{41,48}]
            vec1_reg_10 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'hA)	// @[controller.scala:65:29, :154:36, :181:42]
            vec1_reg_10 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'hB)	// @[controller.scala:154:36, :182:{41,48}]
            vec1_reg_11 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'hB)	// @[controller.scala:65:29, :154:36, :181:42]
            vec1_reg_11 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'hC)	// @[controller.scala:154:36, :182:{41,48}]
            vec1_reg_12 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'hC)	// @[controller.scala:65:29, :154:36, :181:42]
            vec1_reg_12 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'hD)	// @[controller.scala:154:36, :182:{41,48}]
            vec1_reg_13 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'hD)	// @[controller.scala:65:29, :154:36, :181:42]
            vec1_reg_13 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (_T_60 == 4'hE)	// @[controller.scala:154:36, :182:{41,48}]
            vec1_reg_14 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (vec1_index[3:0] == 4'hE)	// @[controller.scala:65:29, :154:36, :181:42]
            vec1_reg_14 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
          if (&_T_60)	// @[controller.scala:182:{41,48}]
            vec1_reg_15 <= io_mem_resp_data[63:32];	// @[controller.scala:74:28, :182:67]
          else if (&(vec1_index[3:0]))	// @[controller.scala:65:29, :181:42]
            vec1_reg_15 <= io_mem_resp_data[31:0];	// @[controller.scala:74:28, :181:61]
        end
      end
      if (_T_110 | _T_13 | _T_48) begin	// @[controller.scala:75:28, :123:20]
      end
      else if (_T_61) begin	// @[controller.scala:123:20]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len == 5'h0)) begin	// @[controller.scala:65:29, :67:26, :75:28, :152:32, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_0 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len[4:1] == 4'h0)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_1 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'h3)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_2 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len[4:2] == 3'h0)) begin	// @[controller.scala:67:26, :75:28, :103:29, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_3 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'h5)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_4 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'h6)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_5 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'h7)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_6 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len[4:3] == 2'h0)) begin	// @[controller.scala:67:26, :75:28, :139:36, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_7 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'h9)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_8 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'hA)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_9 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'hB)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_10 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'hC)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_11 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'hD)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_12 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'hE)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_13 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | ~(~(vec_len[4]) & vec_len < 5'hF)) begin	// @[controller.scala:67:26, :75:28, :152:32, :154:36, :195:42, :198:30, :212:{32,39}, :214:{36,47}, :215:41]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_14 <= 32'h0;	// @[controller.scala:74:36, :75:28]
        if (_finish_v2_T | vec_len[4] | vec_len[4]) begin	// @[controller.scala:67:26, :75:28, :152:32, :195:42, :198:30, :212:39, :214:36]
        end
        else	// @[controller.scala:75:28, :198:30, :212:39]
          vec2_reg_15 <= 32'h0;	// @[controller.scala:74:36, :75:28]
      end
      else if (_GEN_4) begin	// @[controller.scala:75:28, :123:20, :225:36, :228:55]
        if (alomst_finish_v2) begin	// @[controller.scala:224:49]
          if (|(_odd_v2_length_T[1:0])) begin	// @[controller.scala:223:{43,49}]
            if (_T_100 == 4'h0)	// @[controller.scala:154:36, :231:{45,52}]
              vec2_reg_0 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h0)	// @[controller.scala:66:33, :154:36, :230:46]
              vec2_reg_0 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'h1)	// @[controller.scala:170:46, :231:{45,52}]
              vec2_reg_1 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h1)	// @[controller.scala:66:33, :170:46, :230:46]
              vec2_reg_1 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'h2)	// @[controller.scala:170:46, :231:{45,52}]
              vec2_reg_2 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h2)	// @[controller.scala:66:33, :170:46, :230:46]
              vec2_reg_2 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'h3)	// @[controller.scala:170:46, :231:{45,52}]
              vec2_reg_3 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h3)	// @[controller.scala:66:33, :170:46, :230:46]
              vec2_reg_3 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'h4)	// @[controller.scala:170:46, :231:{45,52}]
              vec2_reg_4 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h4)	// @[controller.scala:66:33, :170:46, :230:46]
              vec2_reg_4 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'h5)	// @[controller.scala:170:46, :231:{45,52}]
              vec2_reg_5 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h5)	// @[controller.scala:66:33, :170:46, :230:46]
              vec2_reg_5 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'h6)	// @[controller.scala:170:46, :231:{45,52}]
              vec2_reg_6 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h6)	// @[controller.scala:66:33, :170:46, :230:46]
              vec2_reg_6 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'h7)	// @[controller.scala:170:46, :231:{45,52}]
              vec2_reg_7 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h7)	// @[controller.scala:66:33, :170:46, :230:46]
              vec2_reg_7 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'h8)	// @[controller.scala:154:36, :231:{45,52}]
              vec2_reg_8 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h8)	// @[controller.scala:66:33, :154:36, :230:46]
              vec2_reg_8 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'h9)	// @[controller.scala:154:36, :231:{45,52}]
              vec2_reg_9 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'h9)	// @[controller.scala:66:33, :154:36, :230:46]
              vec2_reg_9 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'hA)	// @[controller.scala:154:36, :231:{45,52}]
              vec2_reg_10 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'hA)	// @[controller.scala:66:33, :154:36, :230:46]
              vec2_reg_10 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'hB)	// @[controller.scala:154:36, :231:{45,52}]
              vec2_reg_11 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'hB)	// @[controller.scala:66:33, :154:36, :230:46]
              vec2_reg_11 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'hC)	// @[controller.scala:154:36, :231:{45,52}]
              vec2_reg_12 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'hC)	// @[controller.scala:66:33, :154:36, :230:46]
              vec2_reg_12 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'hD)	// @[controller.scala:154:36, :231:{45,52}]
              vec2_reg_13 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'hD)	// @[controller.scala:66:33, :154:36, :230:46]
              vec2_reg_13 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (_T_100 == 4'hE)	// @[controller.scala:154:36, :231:{45,52}]
              vec2_reg_14 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (vec2_index[3:0] == 4'hE)	// @[controller.scala:66:33, :154:36, :230:46]
              vec2_reg_14 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
            if (&_T_100)	// @[controller.scala:231:{45,52}]
              vec2_reg_15 <= 32'h0;	// @[controller.scala:74:36, :75:28]
            else if (&(vec2_index[3:0]))	// @[controller.scala:66:33, :230:46]
              vec2_reg_15 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :230:65]
          end
          else begin	// @[controller.scala:223:49]
            if (_T_104 == 4'h0)	// @[controller.scala:154:36, :236:{45,52}]
              vec2_reg_0 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h0)	// @[controller.scala:66:33, :154:36, :235:46]
              vec2_reg_0 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'h1)	// @[controller.scala:170:46, :236:{45,52}]
              vec2_reg_1 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h1)	// @[controller.scala:66:33, :170:46, :235:46]
              vec2_reg_1 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'h2)	// @[controller.scala:170:46, :236:{45,52}]
              vec2_reg_2 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h2)	// @[controller.scala:66:33, :170:46, :235:46]
              vec2_reg_2 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'h3)	// @[controller.scala:170:46, :236:{45,52}]
              vec2_reg_3 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h3)	// @[controller.scala:66:33, :170:46, :235:46]
              vec2_reg_3 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'h4)	// @[controller.scala:170:46, :236:{45,52}]
              vec2_reg_4 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h4)	// @[controller.scala:66:33, :170:46, :235:46]
              vec2_reg_4 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'h5)	// @[controller.scala:170:46, :236:{45,52}]
              vec2_reg_5 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h5)	// @[controller.scala:66:33, :170:46, :235:46]
              vec2_reg_5 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'h6)	// @[controller.scala:170:46, :236:{45,52}]
              vec2_reg_6 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h6)	// @[controller.scala:66:33, :170:46, :235:46]
              vec2_reg_6 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'h7)	// @[controller.scala:170:46, :236:{45,52}]
              vec2_reg_7 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h7)	// @[controller.scala:66:33, :170:46, :235:46]
              vec2_reg_7 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'h8)	// @[controller.scala:154:36, :236:{45,52}]
              vec2_reg_8 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h8)	// @[controller.scala:66:33, :154:36, :235:46]
              vec2_reg_8 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'h9)	// @[controller.scala:154:36, :236:{45,52}]
              vec2_reg_9 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'h9)	// @[controller.scala:66:33, :154:36, :235:46]
              vec2_reg_9 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'hA)	// @[controller.scala:154:36, :236:{45,52}]
              vec2_reg_10 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'hA)	// @[controller.scala:66:33, :154:36, :235:46]
              vec2_reg_10 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'hB)	// @[controller.scala:154:36, :236:{45,52}]
              vec2_reg_11 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'hB)	// @[controller.scala:66:33, :154:36, :235:46]
              vec2_reg_11 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'hC)	// @[controller.scala:154:36, :236:{45,52}]
              vec2_reg_12 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'hC)	// @[controller.scala:66:33, :154:36, :235:46]
              vec2_reg_12 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'hD)	// @[controller.scala:154:36, :236:{45,52}]
              vec2_reg_13 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'hD)	// @[controller.scala:66:33, :154:36, :235:46]
              vec2_reg_13 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (_T_104 == 4'hE)	// @[controller.scala:154:36, :236:{45,52}]
              vec2_reg_14 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (vec2_index[3:0] == 4'hE)	// @[controller.scala:66:33, :154:36, :235:46]
              vec2_reg_14 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
            if (&_T_104)	// @[controller.scala:236:{45,52}]
              vec2_reg_15 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :236:71]
            else if (&(vec2_index[3:0]))	// @[controller.scala:66:33, :235:46]
              vec2_reg_15 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :235:65]
          end
        end
        else begin	// @[controller.scala:224:49]
          if (_T_108 == 4'h0)	// @[controller.scala:154:36, :242:{41,48}]
            vec2_reg_0 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h0)	// @[controller.scala:66:33, :154:36, :241:42]
            vec2_reg_0 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'h1)	// @[controller.scala:170:46, :242:{41,48}]
            vec2_reg_1 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h1)	// @[controller.scala:66:33, :170:46, :241:42]
            vec2_reg_1 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'h2)	// @[controller.scala:170:46, :242:{41,48}]
            vec2_reg_2 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h2)	// @[controller.scala:66:33, :170:46, :241:42]
            vec2_reg_2 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'h3)	// @[controller.scala:170:46, :242:{41,48}]
            vec2_reg_3 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h3)	// @[controller.scala:66:33, :170:46, :241:42]
            vec2_reg_3 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'h4)	// @[controller.scala:170:46, :242:{41,48}]
            vec2_reg_4 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h4)	// @[controller.scala:66:33, :170:46, :241:42]
            vec2_reg_4 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'h5)	// @[controller.scala:170:46, :242:{41,48}]
            vec2_reg_5 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h5)	// @[controller.scala:66:33, :170:46, :241:42]
            vec2_reg_5 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'h6)	// @[controller.scala:170:46, :242:{41,48}]
            vec2_reg_6 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h6)	// @[controller.scala:66:33, :170:46, :241:42]
            vec2_reg_6 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'h7)	// @[controller.scala:170:46, :242:{41,48}]
            vec2_reg_7 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h7)	// @[controller.scala:66:33, :170:46, :241:42]
            vec2_reg_7 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'h8)	// @[controller.scala:154:36, :242:{41,48}]
            vec2_reg_8 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h8)	// @[controller.scala:66:33, :154:36, :241:42]
            vec2_reg_8 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'h9)	// @[controller.scala:154:36, :242:{41,48}]
            vec2_reg_9 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'h9)	// @[controller.scala:66:33, :154:36, :241:42]
            vec2_reg_9 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'hA)	// @[controller.scala:154:36, :242:{41,48}]
            vec2_reg_10 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'hA)	// @[controller.scala:66:33, :154:36, :241:42]
            vec2_reg_10 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'hB)	// @[controller.scala:154:36, :242:{41,48}]
            vec2_reg_11 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'hB)	// @[controller.scala:66:33, :154:36, :241:42]
            vec2_reg_11 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'hC)	// @[controller.scala:154:36, :242:{41,48}]
            vec2_reg_12 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'hC)	// @[controller.scala:66:33, :154:36, :241:42]
            vec2_reg_12 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'hD)	// @[controller.scala:154:36, :242:{41,48}]
            vec2_reg_13 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'hD)	// @[controller.scala:66:33, :154:36, :241:42]
            vec2_reg_13 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (_T_108 == 4'hE)	// @[controller.scala:154:36, :242:{41,48}]
            vec2_reg_14 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (vec2_index[3:0] == 4'hE)	// @[controller.scala:66:33, :154:36, :241:42]
            vec2_reg_14 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
          if (&_T_108)	// @[controller.scala:242:{41,48}]
            vec2_reg_15 <= io_mem_resp_data[63:32];	// @[controller.scala:75:28, :242:67]
          else if (&(vec2_index[3:0]))	// @[controller.scala:66:33, :241:42]
            vec2_reg_15 <= io_mem_resp_data[31:0];	// @[controller.scala:75:28, :241:61]
        end
      end
      if (_T_109 | _T_120 | ~(_T_121 & io_comp_valid)) begin	// @[controller.scala:76:29, :257:23, :271:33, :272:28]
      end
      else	// @[controller.scala:76:29, :257:23]
        result_reg <= io_comp_result;	// @[controller.scala:76:29]
      isHandling_reg <= _GEN_6 & (_T_2 & ~_T_3 & _T_4 | isHandling_reg);	// @[controller.scala:78:33, :110:{27,68}, :111:{29,37}, :114:{34,42}, :123:20, :257:23]
      ctrl_state <= _GEN_7[ctrl_state];	// @[controller.scala:103:29, :257:23, :260:113, :268:24, :271:33, :283:37, :290:25]
      m_state <= _GEN_8[m_state];	// @[controller.scala:107:26, :123:20, :128:107, :137:30, :165:36, :198:30, :225:36]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    logic [31:0] _RANDOM_13;
    logic [31:0] _RANDOM_14;
    logic [31:0] _RANDOM_15;
    logic [31:0] _RANDOM_16;
    logic [31:0] _RANDOM_17;
    logic [31:0] _RANDOM_18;
    logic [31:0] _RANDOM_19;
    logic [31:0] _RANDOM_20;
    logic [31:0] _RANDOM_21;
    logic [31:0] _RANDOM_22;
    logic [31:0] _RANDOM_23;
    logic [31:0] _RANDOM_24;
    logic [31:0] _RANDOM_25;
    logic [31:0] _RANDOM_26;
    logic [31:0] _RANDOM_27;
    logic [31:0] _RANDOM_28;
    logic [31:0] _RANDOM_29;
    logic [31:0] _RANDOM_30;
    logic [31:0] _RANDOM_31;
    logic [31:0] _RANDOM_32;
    logic [31:0] _RANDOM_33;
    logic [31:0] _RANDOM_34;
    logic [31:0] _RANDOM_35;
    logic [31:0] _RANDOM_36;
    logic [31:0] _RANDOM_37;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        _RANDOM_21 = `RANDOM;
        _RANDOM_22 = `RANDOM;
        _RANDOM_23 = `RANDOM;
        _RANDOM_24 = `RANDOM;
        _RANDOM_25 = `RANDOM;
        _RANDOM_26 = `RANDOM;
        _RANDOM_27 = `RANDOM;
        _RANDOM_28 = `RANDOM;
        _RANDOM_29 = `RANDOM;
        _RANDOM_30 = `RANDOM;
        _RANDOM_31 = `RANDOM;
        _RANDOM_32 = `RANDOM;
        _RANDOM_33 = `RANDOM;
        _RANDOM_34 = `RANDOM;
        _RANDOM_35 = `RANDOM;
        _RANDOM_36 = `RANDOM;
        _RANDOM_37 = `RANDOM;
        vec1_head = {_RANDOM_0, _RANDOM_1};	// @[controller.scala:60:28]
        vec2_head = {_RANDOM_2, _RANDOM_3};	// @[controller.scala:61:32]
        vec1_index = _RANDOM_4[4:0];	// @[controller.scala:65:29]
        vec2_index = _RANDOM_4[9:5];	// @[controller.scala:65:29, :66:33]
        vec_len = _RANDOM_4[14:10];	// @[controller.scala:65:29, :67:26]
        rd_reg = _RANDOM_4[19:15];	// @[controller.scala:65:29, :71:25]
        vec1_reg_0 = {_RANDOM_4[31:20], _RANDOM_5[19:0]};	// @[controller.scala:65:29, :74:28]
        vec1_reg_1 = {_RANDOM_5[31:20], _RANDOM_6[19:0]};	// @[controller.scala:74:28]
        vec1_reg_2 = {_RANDOM_6[31:20], _RANDOM_7[19:0]};	// @[controller.scala:74:28]
        vec1_reg_3 = {_RANDOM_7[31:20], _RANDOM_8[19:0]};	// @[controller.scala:74:28]
        vec1_reg_4 = {_RANDOM_8[31:20], _RANDOM_9[19:0]};	// @[controller.scala:74:28]
        vec1_reg_5 = {_RANDOM_9[31:20], _RANDOM_10[19:0]};	// @[controller.scala:74:28]
        vec1_reg_6 = {_RANDOM_10[31:20], _RANDOM_11[19:0]};	// @[controller.scala:74:28]
        vec1_reg_7 = {_RANDOM_11[31:20], _RANDOM_12[19:0]};	// @[controller.scala:74:28]
        vec1_reg_8 = {_RANDOM_12[31:20], _RANDOM_13[19:0]};	// @[controller.scala:74:28]
        vec1_reg_9 = {_RANDOM_13[31:20], _RANDOM_14[19:0]};	// @[controller.scala:74:28]
        vec1_reg_10 = {_RANDOM_14[31:20], _RANDOM_15[19:0]};	// @[controller.scala:74:28]
        vec1_reg_11 = {_RANDOM_15[31:20], _RANDOM_16[19:0]};	// @[controller.scala:74:28]
        vec1_reg_12 = {_RANDOM_16[31:20], _RANDOM_17[19:0]};	// @[controller.scala:74:28]
        vec1_reg_13 = {_RANDOM_17[31:20], _RANDOM_18[19:0]};	// @[controller.scala:74:28]
        vec1_reg_14 = {_RANDOM_18[31:20], _RANDOM_19[19:0]};	// @[controller.scala:74:28]
        vec1_reg_15 = {_RANDOM_19[31:20], _RANDOM_20[19:0]};	// @[controller.scala:74:28]
        vec2_reg_0 = {_RANDOM_20[31:20], _RANDOM_21[19:0]};	// @[controller.scala:74:28, :75:28]
        vec2_reg_1 = {_RANDOM_21[31:20], _RANDOM_22[19:0]};	// @[controller.scala:75:28]
        vec2_reg_2 = {_RANDOM_22[31:20], _RANDOM_23[19:0]};	// @[controller.scala:75:28]
        vec2_reg_3 = {_RANDOM_23[31:20], _RANDOM_24[19:0]};	// @[controller.scala:75:28]
        vec2_reg_4 = {_RANDOM_24[31:20], _RANDOM_25[19:0]};	// @[controller.scala:75:28]
        vec2_reg_5 = {_RANDOM_25[31:20], _RANDOM_26[19:0]};	// @[controller.scala:75:28]
        vec2_reg_6 = {_RANDOM_26[31:20], _RANDOM_27[19:0]};	// @[controller.scala:75:28]
        vec2_reg_7 = {_RANDOM_27[31:20], _RANDOM_28[19:0]};	// @[controller.scala:75:28]
        vec2_reg_8 = {_RANDOM_28[31:20], _RANDOM_29[19:0]};	// @[controller.scala:75:28]
        vec2_reg_9 = {_RANDOM_29[31:20], _RANDOM_30[19:0]};	// @[controller.scala:75:28]
        vec2_reg_10 = {_RANDOM_30[31:20], _RANDOM_31[19:0]};	// @[controller.scala:75:28]
        vec2_reg_11 = {_RANDOM_31[31:20], _RANDOM_32[19:0]};	// @[controller.scala:75:28]
        vec2_reg_12 = {_RANDOM_32[31:20], _RANDOM_33[19:0]};	// @[controller.scala:75:28]
        vec2_reg_13 = {_RANDOM_33[31:20], _RANDOM_34[19:0]};	// @[controller.scala:75:28]
        vec2_reg_14 = {_RANDOM_34[31:20], _RANDOM_35[19:0]};	// @[controller.scala:75:28]
        vec2_reg_15 = {_RANDOM_35[31:20], _RANDOM_36[19:0]};	// @[controller.scala:75:28]
        result_reg = {_RANDOM_36[31:20], _RANDOM_37[19:0]};	// @[controller.scala:75:28, :76:29]
        isHandling_reg = _RANDOM_37[20];	// @[controller.scala:76:29, :78:33]
        ctrl_state = _RANDOM_37[23:21];	// @[controller.scala:76:29, :103:29]
        m_state = _RANDOM_37[26:24];	// @[controller.scala:76:29, :107:26]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  assign io_core_req_rdy = ~isHandling_reg;	// @[controller.scala:78:33, :87:28]
  assign io_core_resp_rd = rd_reg;	// @[controller.scala:71:25]
  assign io_core_resp_data = result_reg;	// @[controller.scala:76:29]
  assign io_core_resp_valid = ~(_T_109 | _T_120 | _T_121) & _T_122;	// @[controller.scala:89:24, :257:23]
  assign io_mem_req_val = ~_T_110 & (_T_13 ? _finish_v1_T : ~_T_48 & _T_61 & _finish_v2_T);	// @[controller.scala:82:24, :123:20, :135:42, :137:30, :195:42]
  assign io_mem_req_tag = _T_110 ? 7'h0 : _T_13 ? (_finish_v1_T ? {2'h0, vec1_index} : 7'h0) : _GEN_0 ? 7'h0 : {2'h0, vec2_index};	// @[controller.scala:65:29, :66:33, :83:24, :123:20, :135:42, :137:30, :139:36, :200:36]
  assign io_mem_req_size = _T_110 ? 4'h2 : _T_13 ? {3'h1, _finish_v1_T} : _T_48 ? 4'h2 : {3'h1, _GEN};	// @[controller.scala:81:21, :83:24, :123:20, :129:25, :135:42, :137:30, :143:32, :170:46, :198:30, :200:36, :204:32]
  assign io_mem_req_addr = _T_110 ? 40'h0 : _T_13 ? (_finish_v1_T ? {8'h0, vec1_head[31:0]} : 40'h0) : _GEN_0 ? 40'h0 : {8'h0, vec2_head[31:0]};	// @[controller.scala:60:28, :61:32, :83:24, :86:24, :123:20, :135:42, :137:30, :142:{36,48}, :203:{36,48}]
  assign io_comp_enable = ~_T_109 & _T_120;	// @[controller.scala:91:21, :257:23]
  assign io_vec1_0 = vec1_reg_0;	// @[controller.scala:74:28]
  assign io_vec1_1 = vec1_reg_1;	// @[controller.scala:74:28]
  assign io_vec1_2 = vec1_reg_2;	// @[controller.scala:74:28]
  assign io_vec1_3 = vec1_reg_3;	// @[controller.scala:74:28]
  assign io_vec1_4 = vec1_reg_4;	// @[controller.scala:74:28]
  assign io_vec1_5 = vec1_reg_5;	// @[controller.scala:74:28]
  assign io_vec1_6 = vec1_reg_6;	// @[controller.scala:74:28]
  assign io_vec1_7 = vec1_reg_7;	// @[controller.scala:74:28]
  assign io_vec1_8 = vec1_reg_8;	// @[controller.scala:74:28]
  assign io_vec1_9 = vec1_reg_9;	// @[controller.scala:74:28]
  assign io_vec1_10 = vec1_reg_10;	// @[controller.scala:74:28]
  assign io_vec1_11 = vec1_reg_11;	// @[controller.scala:74:28]
  assign io_vec1_12 = vec1_reg_12;	// @[controller.scala:74:28]
  assign io_vec1_13 = vec1_reg_13;	// @[controller.scala:74:28]
  assign io_vec1_14 = vec1_reg_14;	// @[controller.scala:74:28]
  assign io_vec1_15 = vec1_reg_15;	// @[controller.scala:74:28]
  assign io_vec2_0 = vec2_reg_0;	// @[controller.scala:75:28]
  assign io_vec2_1 = vec2_reg_1;	// @[controller.scala:75:28]
  assign io_vec2_2 = vec2_reg_2;	// @[controller.scala:75:28]
  assign io_vec2_3 = vec2_reg_3;	// @[controller.scala:75:28]
  assign io_vec2_4 = vec2_reg_4;	// @[controller.scala:75:28]
  assign io_vec2_5 = vec2_reg_5;	// @[controller.scala:75:28]
  assign io_vec2_6 = vec2_reg_6;	// @[controller.scala:75:28]
  assign io_vec2_7 = vec2_reg_7;	// @[controller.scala:75:28]
  assign io_vec2_8 = vec2_reg_8;	// @[controller.scala:75:28]
  assign io_vec2_9 = vec2_reg_9;	// @[controller.scala:75:28]
  assign io_vec2_10 = vec2_reg_10;	// @[controller.scala:75:28]
  assign io_vec2_11 = vec2_reg_11;	// @[controller.scala:75:28]
  assign io_vec2_12 = vec2_reg_12;	// @[controller.scala:75:28]
  assign io_vec2_13 = vec2_reg_13;	// @[controller.scala:75:28]
  assign io_vec2_14 = vec2_reg_14;	// @[controller.scala:75:28]
  assign io_vec2_15 = vec2_reg_15;	// @[controller.scala:75:28]
  assign io_isHandling = isHandling_reg;	// @[controller.scala:78:33]
endmodule

