// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module InputUnit_4(
  input         clock,
                reset,
                io_router_resp_vc_sel_0_0,
                io_router_resp_vc_sel_0_1,
                io_router_resp_vc_sel_0_3,
                io_router_resp_vc_sel_0_4,
                io_router_resp_vc_sel_0_5,
                io_router_resp_vc_sel_0_8,
                io_router_resp_vc_sel_0_9,
                io_vcalloc_req_ready,
                io_vcalloc_resp_vc_sel_3_0,
                io_vcalloc_resp_vc_sel_2_0,
                io_vcalloc_resp_vc_sel_1_0,
                io_vcalloc_resp_vc_sel_0_0,
                io_vcalloc_resp_vc_sel_0_1,
                io_vcalloc_resp_vc_sel_0_3,
                io_vcalloc_resp_vc_sel_0_4,
                io_vcalloc_resp_vc_sel_0_5,
                io_vcalloc_resp_vc_sel_0_8,
                io_vcalloc_resp_vc_sel_0_9,
                io_out_credit_available_3_0,
                io_out_credit_available_2_0,
                io_out_credit_available_1_0,
                io_out_credit_available_0_0,
                io_out_credit_available_0_1,
                io_out_credit_available_0_3,
                io_out_credit_available_0_4,
                io_out_credit_available_0_5,
                io_out_credit_available_0_7,
                io_out_credit_available_0_8,
                io_out_credit_available_0_9,
                io_salloc_req_0_ready,
                io_in_flit_0_valid,
                io_in_flit_0_bits_head,
                io_in_flit_0_bits_tail,
  input  [72:0] io_in_flit_0_bits_payload,
  input  [2:0]  io_in_flit_0_bits_flow_vnet_id,
  input  [3:0]  io_in_flit_0_bits_flow_ingress_node,
  input  [2:0]  io_in_flit_0_bits_flow_ingress_node_id,
  input  [3:0]  io_in_flit_0_bits_flow_egress_node,
  input  [2:0]  io_in_flit_0_bits_flow_egress_node_id,
  input  [3:0]  io_in_flit_0_bits_virt_channel_id,
  output [3:0]  io_router_req_bits_src_virt_id,
  output [2:0]  io_router_req_bits_flow_vnet_id,
  output [3:0]  io_router_req_bits_flow_ingress_node,
  output [2:0]  io_router_req_bits_flow_ingress_node_id,
  output [3:0]  io_router_req_bits_flow_egress_node,
  output [2:0]  io_router_req_bits_flow_egress_node_id,
  output        io_vcalloc_req_valid,
                io_vcalloc_req_bits_vc_sel_3_0,
                io_vcalloc_req_bits_vc_sel_2_0,
                io_vcalloc_req_bits_vc_sel_1_0,
                io_vcalloc_req_bits_vc_sel_0_0,
                io_vcalloc_req_bits_vc_sel_0_1,
                io_vcalloc_req_bits_vc_sel_0_3,
                io_vcalloc_req_bits_vc_sel_0_4,
                io_vcalloc_req_bits_vc_sel_0_5,
                io_vcalloc_req_bits_vc_sel_0_8,
                io_vcalloc_req_bits_vc_sel_0_9,
                io_salloc_req_0_valid,
                io_salloc_req_0_bits_vc_sel_3_0,
                io_salloc_req_0_bits_vc_sel_2_0,
                io_salloc_req_0_bits_vc_sel_1_0,
                io_salloc_req_0_bits_vc_sel_0_0,
                io_salloc_req_0_bits_vc_sel_0_1,
                io_salloc_req_0_bits_vc_sel_0_3,
                io_salloc_req_0_bits_vc_sel_0_4,
                io_salloc_req_0_bits_vc_sel_0_5,
                io_salloc_req_0_bits_vc_sel_0_7,
                io_salloc_req_0_bits_vc_sel_0_8,
                io_salloc_req_0_bits_vc_sel_0_9,
                io_salloc_req_0_bits_tail,
                io_out_0_valid,
                io_out_0_bits_flit_head,
                io_out_0_bits_flit_tail,
  output [72:0] io_out_0_bits_flit_payload,
  output [2:0]  io_out_0_bits_flit_flow_vnet_id,
  output [3:0]  io_out_0_bits_flit_flow_ingress_node,
  output [2:0]  io_out_0_bits_flit_flow_ingress_node_id,
  output [3:0]  io_out_0_bits_flit_flow_egress_node,
  output [2:0]  io_out_0_bits_flit_flow_egress_node_id,
  output [3:0]  io_out_0_bits_out_virt_channel,
                io_debug_va_stall,
                io_debug_sa_stall,
  output [9:0]  io_in_credit_return,
                io_in_vc_free
);

  wire        vcalloc_vals_9;	// @[InputUnit.scala:249:32]
  wire        vcalloc_vals_8;	// @[InputUnit.scala:249:32]
  wire        vcalloc_vals_5;	// @[InputUnit.scala:249:32]
  wire        vcalloc_vals_4;	// @[InputUnit.scala:249:32]
  wire        vcalloc_vals_3;	// @[InputUnit.scala:249:32]
  wire        vcalloc_vals_1;	// @[InputUnit.scala:249:32]
  wire        vcalloc_vals_0;	// @[InputUnit.scala:249:32]
  wire        _salloc_arb_io_in_0_ready;	// @[InputUnit.scala:279:26]
  wire        _salloc_arb_io_in_1_ready;	// @[InputUnit.scala:279:26]
  wire        _salloc_arb_io_in_3_ready;	// @[InputUnit.scala:279:26]
  wire        _salloc_arb_io_in_4_ready;	// @[InputUnit.scala:279:26]
  wire        _salloc_arb_io_in_5_ready;	// @[InputUnit.scala:279:26]
  wire        _salloc_arb_io_in_7_ready;	// @[InputUnit.scala:279:26]
  wire        _salloc_arb_io_in_8_ready;	// @[InputUnit.scala:279:26]
  wire        _salloc_arb_io_in_9_ready;	// @[InputUnit.scala:279:26]
  wire        _salloc_arb_io_out_0_valid;	// @[InputUnit.scala:279:26]
  wire [9:0]  _salloc_arb_io_chosen_oh_0;	// @[InputUnit.scala:279:26]
  wire        _route_arbiter_io_in_1_ready;	// @[InputUnit.scala:186:29]
  wire        _route_arbiter_io_in_2_ready;	// @[InputUnit.scala:186:29]
  wire        _route_arbiter_io_in_3_ready;	// @[InputUnit.scala:186:29]
  wire        _route_arbiter_io_in_4_ready;	// @[InputUnit.scala:186:29]
  wire        _route_arbiter_io_in_5_ready;	// @[InputUnit.scala:186:29]
  wire        _route_arbiter_io_in_6_ready;	// @[InputUnit.scala:186:29]
  wire        _route_arbiter_io_in_7_ready;	// @[InputUnit.scala:186:29]
  wire        _route_arbiter_io_in_8_ready;	// @[InputUnit.scala:186:29]
  wire        _route_arbiter_io_in_9_ready;	// @[InputUnit.scala:186:29]
  wire        _route_arbiter_io_out_valid;	// @[InputUnit.scala:186:29]
  wire [3:0]  _route_arbiter_io_out_bits_src_virt_id;	// @[InputUnit.scala:186:29]
  wire        _input_buffer_io_deq_0_valid;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_0_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_0_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_0_bits_payload;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_1_valid;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_1_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_1_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_1_bits_payload;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_2_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_2_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_2_bits_payload;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_3_valid;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_3_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_3_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_3_bits_payload;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_4_valid;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_4_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_4_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_4_bits_payload;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_5_valid;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_5_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_5_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_5_bits_payload;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_6_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_6_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_6_bits_payload;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_7_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_7_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_7_bits_payload;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_8_valid;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_8_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_8_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_8_bits_payload;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_9_valid;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_9_bits_head;	// @[InputUnit.scala:180:28]
  wire        _input_buffer_io_deq_9_bits_tail;	// @[InputUnit.scala:180:28]
  wire [72:0] _input_buffer_io_deq_9_bits_payload;	// @[InputUnit.scala:180:28]
  reg  [2:0]  states_0_g;	// @[InputUnit.scala:191:19]
  reg         states_0_vc_sel_3_0;	// @[InputUnit.scala:191:19]
  reg         states_0_vc_sel_2_0;	// @[InputUnit.scala:191:19]
  reg         states_0_vc_sel_1_0;	// @[InputUnit.scala:191:19]
  reg         states_0_vc_sel_0_0;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_0_flow_vnet_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_0_flow_ingress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_0_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_0_flow_egress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_0_flow_egress_node_id;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_1_g;	// @[InputUnit.scala:191:19]
  reg         states_1_vc_sel_3_0;	// @[InputUnit.scala:191:19]
  reg         states_1_vc_sel_2_0;	// @[InputUnit.scala:191:19]
  reg         states_1_vc_sel_1_0;	// @[InputUnit.scala:191:19]
  reg         states_1_vc_sel_0_0;	// @[InputUnit.scala:191:19]
  reg         states_1_vc_sel_0_1;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_1_flow_vnet_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_1_flow_ingress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_1_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_1_flow_egress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_1_flow_egress_node_id;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_3_g;	// @[InputUnit.scala:191:19]
  reg         states_3_vc_sel_3_0;	// @[InputUnit.scala:191:19]
  reg         states_3_vc_sel_2_0;	// @[InputUnit.scala:191:19]
  reg         states_3_vc_sel_1_0;	// @[InputUnit.scala:191:19]
  reg         states_3_vc_sel_0_3;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_3_flow_vnet_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_3_flow_ingress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_3_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_3_flow_egress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_3_flow_egress_node_id;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_4_g;	// @[InputUnit.scala:191:19]
  reg         states_4_vc_sel_3_0;	// @[InputUnit.scala:191:19]
  reg         states_4_vc_sel_2_0;	// @[InputUnit.scala:191:19]
  reg         states_4_vc_sel_1_0;	// @[InputUnit.scala:191:19]
  reg         states_4_vc_sel_0_4;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_4_flow_vnet_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_4_flow_ingress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_4_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_4_flow_egress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_4_flow_egress_node_id;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_5_g;	// @[InputUnit.scala:191:19]
  reg         states_5_vc_sel_3_0;	// @[InputUnit.scala:191:19]
  reg         states_5_vc_sel_2_0;	// @[InputUnit.scala:191:19]
  reg         states_5_vc_sel_1_0;	// @[InputUnit.scala:191:19]
  reg         states_5_vc_sel_0_4;	// @[InputUnit.scala:191:19]
  reg         states_5_vc_sel_0_5;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_5_flow_vnet_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_5_flow_ingress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_5_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_5_flow_egress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_5_flow_egress_node_id;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_8_g;	// @[InputUnit.scala:191:19]
  reg         states_8_vc_sel_3_0;	// @[InputUnit.scala:191:19]
  reg         states_8_vc_sel_2_0;	// @[InputUnit.scala:191:19]
  reg         states_8_vc_sel_1_0;	// @[InputUnit.scala:191:19]
  reg         states_8_vc_sel_0_8;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_8_flow_vnet_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_8_flow_ingress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_8_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_8_flow_egress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_8_flow_egress_node_id;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_9_g;	// @[InputUnit.scala:191:19]
  reg         states_9_vc_sel_3_0;	// @[InputUnit.scala:191:19]
  reg         states_9_vc_sel_2_0;	// @[InputUnit.scala:191:19]
  reg         states_9_vc_sel_1_0;	// @[InputUnit.scala:191:19]
  reg         states_9_vc_sel_0_8;	// @[InputUnit.scala:191:19]
  reg         states_9_vc_sel_0_9;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_9_flow_vnet_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_9_flow_ingress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_9_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
  reg  [3:0]  states_9_flow_egress_node;	// @[InputUnit.scala:191:19]
  reg  [2:0]  states_9_flow_egress_node_id;	// @[InputUnit.scala:191:19]
  wire        _T = io_in_flit_0_valid & io_in_flit_0_bits_head;	// @[InputUnit.scala:194:32]
  wire        _route_arbiter_io_in_0_valid_T = states_0_g == 3'h1;	// @[InputUnit.scala:191:19, :199:26, :212:22]
  wire        _route_arbiter_io_in_1_valid_T = states_1_g == 3'h1;	// @[InputUnit.scala:191:19, :199:26, :212:22]
  wire        _route_arbiter_io_in_3_valid_T = states_3_g == 3'h1;	// @[InputUnit.scala:191:19, :199:26, :212:22]
  wire        _route_arbiter_io_in_4_valid_T = states_4_g == 3'h1;	// @[InputUnit.scala:191:19, :199:26, :212:22]
  wire        _route_arbiter_io_in_5_valid_T = states_5_g == 3'h1;	// @[InputUnit.scala:191:19, :199:26, :212:22]
  wire        _route_arbiter_io_in_8_valid_T = states_8_g == 3'h1;	// @[InputUnit.scala:191:19, :199:26, :212:22]
  wire        _route_arbiter_io_in_9_valid_T = states_9_g == 3'h1;	// @[InputUnit.scala:191:19, :199:26, :212:22]
  reg  [9:0]  mask;	// @[InputUnit.scala:233:21]
  wire [9:0]  _vcalloc_filter_T_3 = {vcalloc_vals_9, vcalloc_vals_8, 2'h0, vcalloc_vals_5, vcalloc_vals_4, vcalloc_vals_3, 1'h0, vcalloc_vals_1, vcalloc_vals_0} & ~mask;	// @[InputUnit.scala:233:21, :236:{80,87,89}, :249:32, Mux.scala:27:73]
  wire [19:0] vcalloc_filter = _vcalloc_filter_T_3[0] ? 20'h1 : _vcalloc_filter_T_3[1] ? 20'h2 : _vcalloc_filter_T_3[3] ? 20'h8 : _vcalloc_filter_T_3[4] ? 20'h10 : _vcalloc_filter_T_3[5] ? 20'h20 : _vcalloc_filter_T_3[8] ? 20'h100 : _vcalloc_filter_T_3[9] ? 20'h200 : vcalloc_vals_0 ? 20'h400 : vcalloc_vals_1 ? 20'h800 : vcalloc_vals_3 ? 20'h2000 : vcalloc_vals_4 ? 20'h4000 : vcalloc_vals_5 ? 20'h8000 : vcalloc_vals_8 ? 20'h40000 : {vcalloc_vals_9, 19'h0};	// @[InputUnit.scala:236:87, :249:32, Mux.scala:47:70, OneHot.scala:84:71]
  wire [9:0]  vcalloc_sel = vcalloc_filter[9:0] | vcalloc_filter[19:10];	// @[InputUnit.scala:237:{35,58,76}, Mux.scala:47:70]
  wire        _io_vcalloc_req_valid_output = vcalloc_vals_0 | vcalloc_vals_1 | vcalloc_vals_3 | vcalloc_vals_4 | vcalloc_vals_5 | vcalloc_vals_8 | vcalloc_vals_9;	// @[InputUnit.scala:249:32, package.scala:73:59]
  assign vcalloc_vals_0 = states_0_g == 3'h2;	// @[InputUnit.scala:191:19, :199:26, :249:32]
  assign vcalloc_vals_1 = states_1_g == 3'h2;	// @[InputUnit.scala:191:19, :199:26, :249:32]
  assign vcalloc_vals_3 = states_3_g == 3'h2;	// @[InputUnit.scala:191:19, :199:26, :249:32]
  assign vcalloc_vals_4 = states_4_g == 3'h2;	// @[InputUnit.scala:191:19, :199:26, :249:32]
  assign vcalloc_vals_5 = states_5_g == 3'h2;	// @[InputUnit.scala:191:19, :199:26, :249:32]
  assign vcalloc_vals_8 = states_8_g == 3'h2;	// @[InputUnit.scala:191:19, :199:26, :249:32]
  assign vcalloc_vals_9 = states_9_g == 3'h2;	// @[InputUnit.scala:191:19, :199:26, :249:32]
  wire        _T_65 = io_vcalloc_req_ready & _io_vcalloc_req_valid_output;	// @[Decoupled.scala:51:35, package.scala:73:59]
  wire        _GEN = _T_65 & vcalloc_sel[0];	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :270:29, Mux.scala:29:36]
  wire        _GEN_0 = _T_65 & vcalloc_sel[1];	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :270:29, Mux.scala:29:36]
  wire        _GEN_1 = _T_65 & vcalloc_sel[3];	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :270:29, Mux.scala:29:36]
  wire        _GEN_2 = _T_65 & vcalloc_sel[4];	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :270:29, Mux.scala:29:36]
  wire        _GEN_3 = _T_65 & vcalloc_sel[5];	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :270:29, Mux.scala:29:36]
  wire        _GEN_4 = _T_65 & vcalloc_sel[8];	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :270:29, Mux.scala:29:36]
  wire        _GEN_5 = _T_65 & vcalloc_sel[9];	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :270:29, Mux.scala:29:36]
  wire [12:0] _credit_available_T_2 = {states_0_vc_sel_3_0, states_0_vc_sel_2_0, states_0_vc_sel_1_0, 9'h0, states_0_vc_sel_0_0} & {io_out_credit_available_3_0, io_out_credit_available_2_0, io_out_credit_available_1_0, io_out_credit_available_0_9, io_out_credit_available_0_8, io_out_credit_available_0_7, 1'h1, io_out_credit_available_0_5, io_out_credit_available_0_4, io_out_credit_available_0_3, 1'h1, io_out_credit_available_0_1, io_out_credit_available_0_0};	// @[InputUnit.scala:191:19, :287:{40,47,73}]
  wire        _salloc_arb_io_in_0_valid_T_2 = states_0_g == 3'h3 & (|{_credit_available_T_2[12:10], _credit_available_T_2[0]}) & _input_buffer_io_deq_0_valid;	// @[InputUnit.scala:180:28, :191:19, :253:82, :287:{47,81}, :288:{22,50}]
  wire [12:0] _credit_available_T_5 = {states_1_vc_sel_3_0, states_1_vc_sel_2_0, states_1_vc_sel_1_0, 8'h0, states_1_vc_sel_0_1, states_1_vc_sel_0_0} & {io_out_credit_available_3_0, io_out_credit_available_2_0, io_out_credit_available_1_0, io_out_credit_available_0_9, io_out_credit_available_0_8, io_out_credit_available_0_7, 1'h1, io_out_credit_available_0_5, io_out_credit_available_0_4, io_out_credit_available_0_3, 1'h1, io_out_credit_available_0_1, io_out_credit_available_0_0};	// @[InputUnit.scala:191:19, :287:{40,47,73}]
  wire        _salloc_arb_io_in_1_valid_T_2 = states_1_g == 3'h3 & (|{_credit_available_T_5[12:10], _credit_available_T_5[1:0]}) & _input_buffer_io_deq_1_valid;	// @[InputUnit.scala:180:28, :191:19, :253:82, :287:{47,81}, :288:{22,50}]
  wire [9:0]  _GEN_6 = {states_3_vc_sel_3_0, states_3_vc_sel_2_0, states_3_vc_sel_1_0, 6'h0, states_3_vc_sel_0_3} & {io_out_credit_available_3_0, io_out_credit_available_2_0, io_out_credit_available_1_0, io_out_credit_available_0_9, io_out_credit_available_0_8, io_out_credit_available_0_7, 1'h1, io_out_credit_available_0_5, io_out_credit_available_0_4, io_out_credit_available_0_3};	// @[InputUnit.scala:191:19, :287:{40,47,73}, Mux.scala:27:73]
  wire        _salloc_arb_io_in_3_valid_T_2 = states_3_g == 3'h3 & (|{_GEN_6[9:7], _GEN_6[0]}) & _input_buffer_io_deq_3_valid;	// @[InputUnit.scala:180:28, :191:19, :253:82, :287:{47,81}, :288:{22,50}]
  wire [8:0]  _GEN_7 = {io_out_credit_available_3_0, io_out_credit_available_2_0, io_out_credit_available_1_0, io_out_credit_available_0_9, io_out_credit_available_0_8, io_out_credit_available_0_7, 1'h1, io_out_credit_available_0_5, io_out_credit_available_0_4};	// @[InputUnit.scala:287:73]
  wire [8:0]  _GEN_8 = {states_4_vc_sel_3_0, states_4_vc_sel_2_0, states_4_vc_sel_1_0, 5'h0, states_4_vc_sel_0_4} & _GEN_7;	// @[InputUnit.scala:191:19, :287:{40,47,73,81}]
  wire        _salloc_arb_io_in_4_valid_T_2 = states_4_g == 3'h3 & (|{_GEN_8[8:6], _GEN_8[0]}) & _input_buffer_io_deq_4_valid;	// @[InputUnit.scala:180:28, :191:19, :253:82, :287:{47,81}, :288:{22,50}]
  wire [8:0]  _GEN_9 = {states_5_vc_sel_3_0, states_5_vc_sel_2_0, states_5_vc_sel_1_0, 4'h0, states_5_vc_sel_0_5, states_5_vc_sel_0_4} & _GEN_7;	// @[InputUnit.scala:191:19, :199:20, :287:{40,47,73}]
  wire        _salloc_arb_io_in_5_valid_T_2 = states_5_g == 3'h3 & (|{_GEN_9[8:6], _GEN_9[1:0]}) & _input_buffer_io_deq_5_valid;	// @[InputUnit.scala:180:28, :191:19, :253:82, :287:{47,81}, :288:{22,50}]
  wire [4:0]  _GEN_10 = {io_out_credit_available_3_0, io_out_credit_available_2_0, io_out_credit_available_1_0, io_out_credit_available_0_9, io_out_credit_available_0_8};	// @[InputUnit.scala:287:73]
  wire [4:0]  _GEN_11 = {states_8_vc_sel_3_0, states_8_vc_sel_2_0, states_8_vc_sel_1_0, 1'h0, states_8_vc_sel_0_8} & _GEN_10;	// @[InputUnit.scala:191:19, :287:{40,47,73}]
  wire        _salloc_arb_io_in_8_valid_T_2 = states_8_g == 3'h3 & (|{_GEN_11[4:2], _GEN_11[0]}) & _input_buffer_io_deq_8_valid;	// @[InputUnit.scala:180:28, :191:19, :253:82, :287:{47,81}, :288:{22,50}]
  wire        _salloc_arb_io_in_9_valid_T_2 = states_9_g == 3'h3 & (|({states_9_vc_sel_3_0, states_9_vc_sel_2_0, states_9_vc_sel_1_0, states_9_vc_sel_0_9, states_9_vc_sel_0_8} & _GEN_10)) & _input_buffer_io_deq_9_valid;	// @[InputUnit.scala:180:28, :191:19, :253:82, :287:{40,47,73,81}, :288:{22,50}]
  reg         salloc_outs_0_valid;	// @[InputUnit.scala:318:8]
  reg  [3:0]  salloc_outs_0_out_vid;	// @[InputUnit.scala:318:8]
  reg         salloc_outs_0_flit_head;	// @[InputUnit.scala:318:8]
  reg         salloc_outs_0_flit_tail;	// @[InputUnit.scala:318:8]
  reg  [72:0] salloc_outs_0_flit_payload;	// @[InputUnit.scala:318:8]
  reg  [2:0]  salloc_outs_0_flit_flow_vnet_id;	// @[InputUnit.scala:318:8]
  reg  [3:0]  salloc_outs_0_flit_flow_ingress_node;	// @[InputUnit.scala:318:8]
  reg  [2:0]  salloc_outs_0_flit_flow_ingress_node_id;	// @[InputUnit.scala:318:8]
  reg  [3:0]  salloc_outs_0_flit_flow_egress_node;	// @[InputUnit.scala:318:8]
  reg  [2:0]  salloc_outs_0_flit_flow_egress_node_id;	// @[InputUnit.scala:318:8]
  wire        _T_130 = io_salloc_req_0_ready & _salloc_arb_io_out_0_valid;	// @[Decoupled.scala:51:35, InputUnit.scala:279:26]
  wire        _GEN_12 = _route_arbiter_io_out_valid & ~(|_route_arbiter_io_out_bits_src_virt_id);	// @[InputUnit.scala:186:29, :194:60, :222:31, :225:18, :227:{17,25}, :228:26]
  wire        _GEN_13 = _route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h1;	// @[InputUnit.scala:186:29, :194:60, :199:20, :222:31, :227:{17,25}, :228:26]
  wire        _GEN_14 = _route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h3;	// @[InputUnit.scala:186:29, :194:60, :199:20, :222:31, :227:{17,25}, :228:26]
  wire        _GEN_15 = _route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h4;	// @[InputUnit.scala:186:29, :194:60, :199:20, :222:31, :227:{17,25}, :228:26]
  wire        _GEN_16 = _route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h5;	// @[InputUnit.scala:186:29, :194:60, :199:20, :222:31, :227:{17,25}, :228:26]
  wire        _GEN_17 = _route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h8;	// @[InputUnit.scala:186:29, :194:60, :199:20, :222:31, :227:{17,25}, :228:26]
  wire        _GEN_18 = _route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h9;	// @[InputUnit.scala:186:29, :194:60, :199:20, :222:31, :227:{17,25}, :228:26]
  wire [15:0] _mask_T = 16'h1 << _route_arbiter_io_out_bits_src_virt_id;	// @[InputUnit.scala:186:29, :240:18]
  wire        at_dest = io_in_flit_0_bits_flow_egress_node == 4'h4;	// @[InputUnit.scala:198:57, :199:20]
  wire        _GEN_19 = io_in_flit_0_bits_virt_channel_id == 4'h0;	// @[InputUnit.scala:199:20]
  wire        _GEN_20 = _T & _GEN_19;	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20]
  wire        _GEN_21 = io_in_flit_0_bits_virt_channel_id == 4'h1;	// @[InputUnit.scala:199:20]
  wire        _GEN_22 = _T & _GEN_21;	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20]
  wire        _GEN_23 = io_in_flit_0_bits_virt_channel_id == 4'h3;	// @[InputUnit.scala:199:20]
  wire        _GEN_24 = _T & _GEN_23;	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20]
  wire        _GEN_25 = io_in_flit_0_bits_virt_channel_id == 4'h4;	// @[InputUnit.scala:199:20]
  wire        _GEN_26 = _T & _GEN_25;	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20]
  wire        _GEN_27 = io_in_flit_0_bits_virt_channel_id == 4'h5;	// @[InputUnit.scala:199:20]
  wire        _GEN_28 = _T & _GEN_27;	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20]
  wire        _GEN_29 = io_in_flit_0_bits_virt_channel_id == 4'h8;	// @[InputUnit.scala:199:20]
  wire        _GEN_30 = _T & _GEN_29;	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20]
  wire        _GEN_31 = io_in_flit_0_bits_virt_channel_id == 4'h9;	// @[InputUnit.scala:199:20]
  wire        _GEN_32 = _T & _GEN_31;	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20]
  wire        _T_9 = io_in_flit_0_bits_flow_egress_node_id == 3'h0;	// @[InputUnit.scala:197:27, :202:19]
  wire        _T_10 = io_in_flit_0_bits_flow_egress_node_id == 3'h1;	// @[InputUnit.scala:199:26, :202:19]
  wire        _T_11 = io_in_flit_0_bits_flow_egress_node_id == 3'h2;	// @[InputUnit.scala:199:26, :202:19]
  wire        _vc_sel_WIRE_2 = _salloc_arb_io_chosen_oh_0[1] & states_1_vc_sel_0_1;	// @[InputUnit.scala:191:19, :279:26, Mux.scala:27:73, :29:36]
  wire        _vc_sel_WIRE_4 = _salloc_arb_io_chosen_oh_0[3] & states_3_vc_sel_0_3;	// @[InputUnit.scala:191:19, :279:26, Mux.scala:27:73, :29:36]
  wire        _vc_sel_WIRE_5 = _salloc_arb_io_chosen_oh_0[4] & states_4_vc_sel_0_4 | _salloc_arb_io_chosen_oh_0[5] & states_5_vc_sel_0_4;	// @[InputUnit.scala:191:19, :279:26, Mux.scala:27:73, :29:36]
  wire        _vc_sel_WIRE_6 = _salloc_arb_io_chosen_oh_0[5] & states_5_vc_sel_0_5;	// @[InputUnit.scala:191:19, :279:26, Mux.scala:27:73, :29:36]
  wire        _vc_sel_WIRE_9 = _salloc_arb_io_chosen_oh_0[8] & states_8_vc_sel_0_8 | _salloc_arb_io_chosen_oh_0[9] & states_9_vc_sel_0_8;	// @[InputUnit.scala:191:19, :279:26, Mux.scala:27:73, :29:36]
  wire        _vc_sel_WIRE_10 = _salloc_arb_io_chosen_oh_0[9] & states_9_vc_sel_0_9;	// @[InputUnit.scala:191:19, :279:26, Mux.scala:27:73, :29:36]
  always @(posedge clock) begin
    if (reset | _salloc_arb_io_in_0_ready & _salloc_arb_io_in_0_valid_T_2 & _input_buffer_io_deq_0_bits_tail)	// @[InputUnit.scala:180:28, :268:32, :279:26, :288:50, :292:{22,35}, :293:13, :377:23, :378:24]
      states_0_g <= 3'h0;	// @[InputUnit.scala:191:19, :197:27]
    else if (_T_65 & vcalloc_sel[0] | vcalloc_vals_0 & vcalloc_sel[0] & io_vcalloc_req_ready)	// @[Decoupled.scala:51:35, InputUnit.scala:222:31, :237:58, :249:32, :253:{51,76,82}, :268:32, :270:29, :272:21, Mux.scala:29:36]
      states_0_g <= 3'h3;	// @[InputUnit.scala:191:19, :253:82]
    else if (_route_arbiter_io_out_valid & ~(|_route_arbiter_io_out_bits_src_virt_id) | _route_arbiter_io_in_0_valid_T)	// @[InputUnit.scala:186:29, :194:60, :212:22, :215:{23,29}, :222:31, :225:18]
      states_0_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
    else if (_GEN_20) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      if (at_dest)	// @[InputUnit.scala:198:57]
        states_0_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
      else	// @[InputUnit.scala:198:57]
        states_0_g <= 3'h1;	// @[InputUnit.scala:191:19, :199:26]
    end
    if (_GEN) begin	// @[InputUnit.scala:270:29]
      states_0_vc_sel_3_0 <= io_vcalloc_resp_vc_sel_3_0;	// @[InputUnit.scala:191:19]
      states_0_vc_sel_2_0 <= io_vcalloc_resp_vc_sel_2_0;	// @[InputUnit.scala:191:19]
      states_0_vc_sel_1_0 <= io_vcalloc_resp_vc_sel_1_0;	// @[InputUnit.scala:191:19]
      states_0_vc_sel_0_0 <= io_vcalloc_resp_vc_sel_0_0;	// @[InputUnit.scala:191:19]
    end
    else begin	// @[InputUnit.scala:270:29]
      states_0_vc_sel_3_0 <= ~_GEN_12 & (_T ? _T_11 & _GEN_19 | ~_GEN_19 & states_0_vc_sel_3_0 : states_0_vc_sel_3_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_0_vc_sel_2_0 <= ~_GEN_12 & (_T ? _T_10 & _GEN_19 | ~_GEN_19 & states_0_vc_sel_2_0 : states_0_vc_sel_2_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_0_vc_sel_1_0 <= ~_GEN_12 & (_T ? _T_9 & _GEN_19 | ~_GEN_19 & states_0_vc_sel_1_0 : states_0_vc_sel_1_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      if (_GEN_12)	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_0_vc_sel_0_0 <= io_router_resp_vc_sel_0_0;	// @[InputUnit.scala:191:19]
      else	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_0_vc_sel_0_0 <= ~_GEN_20 & states_0_vc_sel_0_0;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
    end
    if (_GEN_20) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      states_0_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[InputUnit.scala:191:19]
      states_0_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[InputUnit.scala:191:19]
      states_0_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
      states_0_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[InputUnit.scala:191:19]
      states_0_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[InputUnit.scala:191:19]
    end
    if (reset | _salloc_arb_io_in_1_ready & _salloc_arb_io_in_1_valid_T_2 & _input_buffer_io_deq_1_bits_tail)	// @[InputUnit.scala:180:28, :268:32, :279:26, :288:50, :292:{22,35}, :293:13, :377:23, :378:24]
      states_1_g <= 3'h0;	// @[InputUnit.scala:191:19, :197:27]
    else if (_T_65 & vcalloc_sel[1] | vcalloc_vals_1 & vcalloc_sel[1] & io_vcalloc_req_ready)	// @[Decoupled.scala:51:35, InputUnit.scala:222:31, :237:58, :249:32, :253:{51,76,82}, :268:32, :270:29, :272:21, Mux.scala:29:36]
      states_1_g <= 3'h3;	// @[InputUnit.scala:191:19, :253:82]
    else if (_route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h1 | _route_arbiter_io_in_1_ready & _route_arbiter_io_in_1_valid_T)	// @[Decoupled.scala:51:35, InputUnit.scala:186:29, :194:60, :199:20, :212:22, :215:{23,29}, :222:31, :225:18]
      states_1_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
    else if (_GEN_22) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      if (at_dest)	// @[InputUnit.scala:198:57]
        states_1_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
      else	// @[InputUnit.scala:198:57]
        states_1_g <= 3'h1;	// @[InputUnit.scala:191:19, :199:26]
    end
    if (_GEN_0) begin	// @[InputUnit.scala:270:29]
      states_1_vc_sel_3_0 <= io_vcalloc_resp_vc_sel_3_0;	// @[InputUnit.scala:191:19]
      states_1_vc_sel_2_0 <= io_vcalloc_resp_vc_sel_2_0;	// @[InputUnit.scala:191:19]
      states_1_vc_sel_1_0 <= io_vcalloc_resp_vc_sel_1_0;	// @[InputUnit.scala:191:19]
      states_1_vc_sel_0_0 <= io_vcalloc_resp_vc_sel_0_0;	// @[InputUnit.scala:191:19]
      states_1_vc_sel_0_1 <= io_vcalloc_resp_vc_sel_0_1;	// @[InputUnit.scala:191:19]
    end
    else begin	// @[InputUnit.scala:270:29]
      states_1_vc_sel_3_0 <= ~_GEN_13 & (_T ? _T_11 & _GEN_21 | ~_GEN_21 & states_1_vc_sel_3_0 : states_1_vc_sel_3_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_1_vc_sel_2_0 <= ~_GEN_13 & (_T ? _T_10 & _GEN_21 | ~_GEN_21 & states_1_vc_sel_2_0 : states_1_vc_sel_2_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_1_vc_sel_1_0 <= ~_GEN_13 & (_T ? _T_9 & _GEN_21 | ~_GEN_21 & states_1_vc_sel_1_0 : states_1_vc_sel_1_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      if (_GEN_13) begin	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_1_vc_sel_0_0 <= io_router_resp_vc_sel_0_0;	// @[InputUnit.scala:191:19]
        states_1_vc_sel_0_1 <= io_router_resp_vc_sel_0_1;	// @[InputUnit.scala:191:19]
      end
      else begin	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_1_vc_sel_0_0 <= ~_GEN_22 & states_1_vc_sel_0_0;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
        states_1_vc_sel_0_1 <= ~_GEN_22 & states_1_vc_sel_0_1;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
      end
    end
    if (_GEN_22) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      states_1_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[InputUnit.scala:191:19]
      states_1_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[InputUnit.scala:191:19]
      states_1_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
      states_1_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[InputUnit.scala:191:19]
      states_1_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[InputUnit.scala:191:19]
    end
    if (reset | _salloc_arb_io_in_3_ready & _salloc_arb_io_in_3_valid_T_2 & _input_buffer_io_deq_3_bits_tail)	// @[InputUnit.scala:180:28, :268:32, :279:26, :288:50, :292:{22,35}, :293:13, :377:23, :378:24]
      states_3_g <= 3'h0;	// @[InputUnit.scala:191:19, :197:27]
    else if (_T_65 & vcalloc_sel[3] | vcalloc_vals_3 & vcalloc_sel[3] & io_vcalloc_req_ready)	// @[Decoupled.scala:51:35, InputUnit.scala:222:31, :237:58, :249:32, :253:{51,76,82}, :268:32, :270:29, :272:21, Mux.scala:29:36]
      states_3_g <= 3'h3;	// @[InputUnit.scala:191:19, :253:82]
    else if (_route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h3 | _route_arbiter_io_in_3_ready & _route_arbiter_io_in_3_valid_T)	// @[Decoupled.scala:51:35, InputUnit.scala:186:29, :194:60, :199:20, :212:22, :215:{23,29}, :222:31, :225:18]
      states_3_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
    else if (_GEN_24) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      if (at_dest)	// @[InputUnit.scala:198:57]
        states_3_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
      else	// @[InputUnit.scala:198:57]
        states_3_g <= 3'h1;	// @[InputUnit.scala:191:19, :199:26]
    end
    if (_GEN_1) begin	// @[InputUnit.scala:270:29]
      states_3_vc_sel_3_0 <= io_vcalloc_resp_vc_sel_3_0;	// @[InputUnit.scala:191:19]
      states_3_vc_sel_2_0 <= io_vcalloc_resp_vc_sel_2_0;	// @[InputUnit.scala:191:19]
      states_3_vc_sel_1_0 <= io_vcalloc_resp_vc_sel_1_0;	// @[InputUnit.scala:191:19]
      states_3_vc_sel_0_3 <= io_vcalloc_resp_vc_sel_0_3;	// @[InputUnit.scala:191:19]
    end
    else begin	// @[InputUnit.scala:270:29]
      states_3_vc_sel_3_0 <= ~_GEN_14 & (_T ? _T_11 & _GEN_23 | ~_GEN_23 & states_3_vc_sel_3_0 : states_3_vc_sel_3_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_3_vc_sel_2_0 <= ~_GEN_14 & (_T ? _T_10 & _GEN_23 | ~_GEN_23 & states_3_vc_sel_2_0 : states_3_vc_sel_2_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_3_vc_sel_1_0 <= ~_GEN_14 & (_T ? _T_9 & _GEN_23 | ~_GEN_23 & states_3_vc_sel_1_0 : states_3_vc_sel_1_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      if (_GEN_14)	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_3_vc_sel_0_3 <= io_router_resp_vc_sel_0_3;	// @[InputUnit.scala:191:19]
      else	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_3_vc_sel_0_3 <= ~_GEN_24 & states_3_vc_sel_0_3;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
    end
    if (_GEN_24) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      states_3_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[InputUnit.scala:191:19]
      states_3_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[InputUnit.scala:191:19]
      states_3_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
      states_3_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[InputUnit.scala:191:19]
      states_3_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[InputUnit.scala:191:19]
    end
    if (reset | _salloc_arb_io_in_4_ready & _salloc_arb_io_in_4_valid_T_2 & _input_buffer_io_deq_4_bits_tail)	// @[InputUnit.scala:180:28, :268:32, :279:26, :288:50, :292:{22,35}, :293:13, :377:23, :378:24]
      states_4_g <= 3'h0;	// @[InputUnit.scala:191:19, :197:27]
    else if (_T_65 & vcalloc_sel[4] | vcalloc_vals_4 & vcalloc_sel[4] & io_vcalloc_req_ready)	// @[Decoupled.scala:51:35, InputUnit.scala:222:31, :237:58, :249:32, :253:{51,76,82}, :268:32, :270:29, :272:21, Mux.scala:29:36]
      states_4_g <= 3'h3;	// @[InputUnit.scala:191:19, :253:82]
    else if (_route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h4 | _route_arbiter_io_in_4_ready & _route_arbiter_io_in_4_valid_T)	// @[Decoupled.scala:51:35, InputUnit.scala:186:29, :194:60, :199:20, :212:22, :215:{23,29}, :222:31, :225:18]
      states_4_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
    else if (_GEN_26) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      if (at_dest)	// @[InputUnit.scala:198:57]
        states_4_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
      else	// @[InputUnit.scala:198:57]
        states_4_g <= 3'h1;	// @[InputUnit.scala:191:19, :199:26]
    end
    if (_GEN_2) begin	// @[InputUnit.scala:270:29]
      states_4_vc_sel_3_0 <= io_vcalloc_resp_vc_sel_3_0;	// @[InputUnit.scala:191:19]
      states_4_vc_sel_2_0 <= io_vcalloc_resp_vc_sel_2_0;	// @[InputUnit.scala:191:19]
      states_4_vc_sel_1_0 <= io_vcalloc_resp_vc_sel_1_0;	// @[InputUnit.scala:191:19]
      states_4_vc_sel_0_4 <= io_vcalloc_resp_vc_sel_0_4;	// @[InputUnit.scala:191:19]
    end
    else begin	// @[InputUnit.scala:270:29]
      states_4_vc_sel_3_0 <= ~_GEN_15 & (_T ? _T_11 & _GEN_25 | ~_GEN_25 & states_4_vc_sel_3_0 : states_4_vc_sel_3_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_4_vc_sel_2_0 <= ~_GEN_15 & (_T ? _T_10 & _GEN_25 | ~_GEN_25 & states_4_vc_sel_2_0 : states_4_vc_sel_2_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_4_vc_sel_1_0 <= ~_GEN_15 & (_T ? _T_9 & _GEN_25 | ~_GEN_25 & states_4_vc_sel_1_0 : states_4_vc_sel_1_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      if (_GEN_15)	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_4_vc_sel_0_4 <= io_router_resp_vc_sel_0_4;	// @[InputUnit.scala:191:19]
      else	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_4_vc_sel_0_4 <= ~_GEN_26 & states_4_vc_sel_0_4;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
    end
    if (_GEN_26) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      states_4_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[InputUnit.scala:191:19]
      states_4_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[InputUnit.scala:191:19]
      states_4_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
      states_4_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[InputUnit.scala:191:19]
      states_4_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[InputUnit.scala:191:19]
    end
    if (reset | _salloc_arb_io_in_5_ready & _salloc_arb_io_in_5_valid_T_2 & _input_buffer_io_deq_5_bits_tail)	// @[InputUnit.scala:180:28, :268:32, :279:26, :288:50, :292:{22,35}, :293:13, :377:23, :378:24]
      states_5_g <= 3'h0;	// @[InputUnit.scala:191:19, :197:27]
    else if (_T_65 & vcalloc_sel[5] | vcalloc_vals_5 & vcalloc_sel[5] & io_vcalloc_req_ready)	// @[Decoupled.scala:51:35, InputUnit.scala:222:31, :237:58, :249:32, :253:{51,76,82}, :268:32, :270:29, :272:21, Mux.scala:29:36]
      states_5_g <= 3'h3;	// @[InputUnit.scala:191:19, :253:82]
    else if (_route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h5 | _route_arbiter_io_in_5_ready & _route_arbiter_io_in_5_valid_T)	// @[Decoupled.scala:51:35, InputUnit.scala:186:29, :194:60, :199:20, :212:22, :215:{23,29}, :222:31, :225:18]
      states_5_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
    else if (_GEN_28) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      if (at_dest)	// @[InputUnit.scala:198:57]
        states_5_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
      else	// @[InputUnit.scala:198:57]
        states_5_g <= 3'h1;	// @[InputUnit.scala:191:19, :199:26]
    end
    if (_GEN_3) begin	// @[InputUnit.scala:270:29]
      states_5_vc_sel_3_0 <= io_vcalloc_resp_vc_sel_3_0;	// @[InputUnit.scala:191:19]
      states_5_vc_sel_2_0 <= io_vcalloc_resp_vc_sel_2_0;	// @[InputUnit.scala:191:19]
      states_5_vc_sel_1_0 <= io_vcalloc_resp_vc_sel_1_0;	// @[InputUnit.scala:191:19]
      states_5_vc_sel_0_4 <= io_vcalloc_resp_vc_sel_0_4;	// @[InputUnit.scala:191:19]
      states_5_vc_sel_0_5 <= io_vcalloc_resp_vc_sel_0_5;	// @[InputUnit.scala:191:19]
    end
    else begin	// @[InputUnit.scala:270:29]
      states_5_vc_sel_3_0 <= ~_GEN_16 & (_T ? _T_11 & _GEN_27 | ~_GEN_27 & states_5_vc_sel_3_0 : states_5_vc_sel_3_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_5_vc_sel_2_0 <= ~_GEN_16 & (_T ? _T_10 & _GEN_27 | ~_GEN_27 & states_5_vc_sel_2_0 : states_5_vc_sel_2_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_5_vc_sel_1_0 <= ~_GEN_16 & (_T ? _T_9 & _GEN_27 | ~_GEN_27 & states_5_vc_sel_1_0 : states_5_vc_sel_1_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      if (_GEN_16) begin	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_5_vc_sel_0_4 <= io_router_resp_vc_sel_0_4;	// @[InputUnit.scala:191:19]
        states_5_vc_sel_0_5 <= io_router_resp_vc_sel_0_5;	// @[InputUnit.scala:191:19]
      end
      else begin	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_5_vc_sel_0_4 <= ~_GEN_28 & states_5_vc_sel_0_4;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
        states_5_vc_sel_0_5 <= ~_GEN_28 & states_5_vc_sel_0_5;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
      end
    end
    if (_GEN_28) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      states_5_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[InputUnit.scala:191:19]
      states_5_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[InputUnit.scala:191:19]
      states_5_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
      states_5_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[InputUnit.scala:191:19]
      states_5_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[InputUnit.scala:191:19]
    end
    if (reset | _salloc_arb_io_in_8_ready & _salloc_arb_io_in_8_valid_T_2 & _input_buffer_io_deq_8_bits_tail)	// @[InputUnit.scala:180:28, :268:32, :279:26, :288:50, :292:{22,35}, :293:13, :377:23, :378:24]
      states_8_g <= 3'h0;	// @[InputUnit.scala:191:19, :197:27]
    else if (_T_65 & vcalloc_sel[8] | vcalloc_vals_8 & vcalloc_sel[8] & io_vcalloc_req_ready)	// @[Decoupled.scala:51:35, InputUnit.scala:222:31, :237:58, :249:32, :253:{51,76,82}, :268:32, :270:29, :272:21, Mux.scala:29:36]
      states_8_g <= 3'h3;	// @[InputUnit.scala:191:19, :253:82]
    else if (_route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h8 | _route_arbiter_io_in_8_ready & _route_arbiter_io_in_8_valid_T)	// @[Decoupled.scala:51:35, InputUnit.scala:186:29, :194:60, :199:20, :212:22, :215:{23,29}, :222:31, :225:18]
      states_8_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
    else if (_GEN_30) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      if (at_dest)	// @[InputUnit.scala:198:57]
        states_8_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
      else	// @[InputUnit.scala:198:57]
        states_8_g <= 3'h1;	// @[InputUnit.scala:191:19, :199:26]
    end
    if (_GEN_4) begin	// @[InputUnit.scala:270:29]
      states_8_vc_sel_3_0 <= io_vcalloc_resp_vc_sel_3_0;	// @[InputUnit.scala:191:19]
      states_8_vc_sel_2_0 <= io_vcalloc_resp_vc_sel_2_0;	// @[InputUnit.scala:191:19]
      states_8_vc_sel_1_0 <= io_vcalloc_resp_vc_sel_1_0;	// @[InputUnit.scala:191:19]
      states_8_vc_sel_0_8 <= io_vcalloc_resp_vc_sel_0_8;	// @[InputUnit.scala:191:19]
    end
    else begin	// @[InputUnit.scala:270:29]
      states_8_vc_sel_3_0 <= ~_GEN_17 & (_T ? _T_11 & _GEN_29 | ~_GEN_29 & states_8_vc_sel_3_0 : states_8_vc_sel_3_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_8_vc_sel_2_0 <= ~_GEN_17 & (_T ? _T_10 & _GEN_29 | ~_GEN_29 & states_8_vc_sel_2_0 : states_8_vc_sel_2_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_8_vc_sel_1_0 <= ~_GEN_17 & (_T ? _T_9 & _GEN_29 | ~_GEN_29 & states_8_vc_sel_1_0 : states_8_vc_sel_1_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      if (_GEN_17)	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_8_vc_sel_0_8 <= io_router_resp_vc_sel_0_8;	// @[InputUnit.scala:191:19]
      else	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_8_vc_sel_0_8 <= ~_GEN_30 & states_8_vc_sel_0_8;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
    end
    if (_GEN_30) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      states_8_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[InputUnit.scala:191:19]
      states_8_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[InputUnit.scala:191:19]
      states_8_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
      states_8_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[InputUnit.scala:191:19]
      states_8_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[InputUnit.scala:191:19]
    end
    if (reset | _salloc_arb_io_in_9_ready & _salloc_arb_io_in_9_valid_T_2 & _input_buffer_io_deq_9_bits_tail)	// @[InputUnit.scala:180:28, :268:32, :279:26, :288:50, :292:{22,35}, :293:13, :377:23, :378:24]
      states_9_g <= 3'h0;	// @[InputUnit.scala:191:19, :197:27]
    else if (_T_65 & vcalloc_sel[9] | vcalloc_vals_9 & vcalloc_sel[9] & io_vcalloc_req_ready)	// @[Decoupled.scala:51:35, InputUnit.scala:222:31, :237:58, :249:32, :253:{51,76,82}, :268:32, :270:29, :272:21, Mux.scala:29:36]
      states_9_g <= 3'h3;	// @[InputUnit.scala:191:19, :253:82]
    else if (_route_arbiter_io_out_valid & _route_arbiter_io_out_bits_src_virt_id == 4'h9 | _route_arbiter_io_in_9_ready & _route_arbiter_io_in_9_valid_T)	// @[Decoupled.scala:51:35, InputUnit.scala:186:29, :194:60, :199:20, :212:22, :215:{23,29}, :222:31, :225:18]
      states_9_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
    else if (_GEN_32) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      if (at_dest)	// @[InputUnit.scala:198:57]
        states_9_g <= 3'h2;	// @[InputUnit.scala:191:19, :199:26]
      else	// @[InputUnit.scala:198:57]
        states_9_g <= 3'h1;	// @[InputUnit.scala:191:19, :199:26]
    end
    if (_GEN_5) begin	// @[InputUnit.scala:270:29]
      states_9_vc_sel_3_0 <= io_vcalloc_resp_vc_sel_3_0;	// @[InputUnit.scala:191:19]
      states_9_vc_sel_2_0 <= io_vcalloc_resp_vc_sel_2_0;	// @[InputUnit.scala:191:19]
      states_9_vc_sel_1_0 <= io_vcalloc_resp_vc_sel_1_0;	// @[InputUnit.scala:191:19]
      states_9_vc_sel_0_8 <= io_vcalloc_resp_vc_sel_0_8;	// @[InputUnit.scala:191:19]
      states_9_vc_sel_0_9 <= io_vcalloc_resp_vc_sel_0_9;	// @[InputUnit.scala:191:19]
    end
    else begin	// @[InputUnit.scala:270:29]
      states_9_vc_sel_3_0 <= ~_GEN_18 & (_T ? _T_11 & _GEN_31 | ~_GEN_31 & states_9_vc_sel_3_0 : states_9_vc_sel_3_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_9_vc_sel_2_0 <= ~_GEN_18 & (_T ? _T_10 & _GEN_31 | ~_GEN_31 & states_9_vc_sel_2_0 : states_9_vc_sel_2_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      states_9_vc_sel_1_0 <= ~_GEN_18 & (_T ? _T_9 & _GEN_31 | ~_GEN_31 & states_9_vc_sel_1_0 : states_9_vc_sel_1_0);	// @[InputUnit.scala:191:19, :194:{32,60}, :199:20, :200:45, :202:{19,63}, :203:44, :222:31, :227:25, :228:26]
      if (_GEN_18) begin	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_9_vc_sel_0_8 <= io_router_resp_vc_sel_0_8;	// @[InputUnit.scala:191:19]
        states_9_vc_sel_0_9 <= io_router_resp_vc_sel_0_9;	// @[InputUnit.scala:191:19]
      end
      else begin	// @[InputUnit.scala:194:60, :222:31, :227:25, :228:26]
        states_9_vc_sel_0_8 <= ~_GEN_32 & states_9_vc_sel_0_8;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
        states_9_vc_sel_0_9 <= ~_GEN_32 & states_9_vc_sel_0_9;	// @[InputUnit.scala:191:19, :194:60, :199:20, :200:45]
      end
    end
    if (_GEN_32) begin	// @[InputUnit.scala:191:19, :194:60, :199:20]
      states_9_flow_vnet_id <= io_in_flit_0_bits_flow_vnet_id;	// @[InputUnit.scala:191:19]
      states_9_flow_ingress_node <= io_in_flit_0_bits_flow_ingress_node;	// @[InputUnit.scala:191:19]
      states_9_flow_ingress_node_id <= io_in_flit_0_bits_flow_ingress_node_id;	// @[InputUnit.scala:191:19]
      states_9_flow_egress_node <= io_in_flit_0_bits_flow_egress_node;	// @[InputUnit.scala:191:19]
      states_9_flow_egress_node_id <= io_in_flit_0_bits_flow_egress_node_id;	// @[InputUnit.scala:191:19]
    end
    salloc_outs_0_valid <= _T_130;	// @[Decoupled.scala:51:35, InputUnit.scala:318:8]
    if (_salloc_arb_io_chosen_oh_0[0] & states_0_vc_sel_0_0 | _salloc_arb_io_chosen_oh_0[1] & states_1_vc_sel_0_0 | _vc_sel_WIRE_2 | _vc_sel_WIRE_4 | _vc_sel_WIRE_5 | _vc_sel_WIRE_6 | _vc_sel_WIRE_9 | _vc_sel_WIRE_10)	// @[InputUnit.scala:191:19, :279:26, :334:43, Mux.scala:27:73, :29:36]
      salloc_outs_0_out_vid <= {|{_vc_sel_WIRE_10, _vc_sel_WIRE_9}, |{_vc_sel_WIRE_6, _vc_sel_WIRE_5}, _vc_sel_WIRE_4, _vc_sel_WIRE_4 | _vc_sel_WIRE_6 | _vc_sel_WIRE_10 | _vc_sel_WIRE_2};	// @[Cat.scala:33:92, InputUnit.scala:318:8, Mux.scala:27:73, OneHot.scala:30:18, :32:{14,28}]
    else	// @[InputUnit.scala:334:43]
      salloc_outs_0_out_vid <= 4'h0;	// @[InputUnit.scala:199:20, :318:8]
    salloc_outs_0_flit_head <= _salloc_arb_io_chosen_oh_0[0] & _input_buffer_io_deq_0_bits_head | _salloc_arb_io_chosen_oh_0[1] & _input_buffer_io_deq_1_bits_head | _salloc_arb_io_chosen_oh_0[2] & _input_buffer_io_deq_2_bits_head | _salloc_arb_io_chosen_oh_0[3] & _input_buffer_io_deq_3_bits_head | _salloc_arb_io_chosen_oh_0[4] & _input_buffer_io_deq_4_bits_head | _salloc_arb_io_chosen_oh_0[5] & _input_buffer_io_deq_5_bits_head | _salloc_arb_io_chosen_oh_0[6] & _input_buffer_io_deq_6_bits_head | _salloc_arb_io_chosen_oh_0[7] & _input_buffer_io_deq_7_bits_head | _salloc_arb_io_chosen_oh_0[8] & _input_buffer_io_deq_8_bits_head | _salloc_arb_io_chosen_oh_0[9] & _input_buffer_io_deq_9_bits_head;	// @[InputUnit.scala:180:28, :279:26, :318:8, Mux.scala:27:73, :29:36]
    salloc_outs_0_flit_tail <= _salloc_arb_io_chosen_oh_0[0] & _input_buffer_io_deq_0_bits_tail | _salloc_arb_io_chosen_oh_0[1] & _input_buffer_io_deq_1_bits_tail | _salloc_arb_io_chosen_oh_0[2] & _input_buffer_io_deq_2_bits_tail | _salloc_arb_io_chosen_oh_0[3] & _input_buffer_io_deq_3_bits_tail | _salloc_arb_io_chosen_oh_0[4] & _input_buffer_io_deq_4_bits_tail | _salloc_arb_io_chosen_oh_0[5] & _input_buffer_io_deq_5_bits_tail | _salloc_arb_io_chosen_oh_0[6] & _input_buffer_io_deq_6_bits_tail | _salloc_arb_io_chosen_oh_0[7] & _input_buffer_io_deq_7_bits_tail | _salloc_arb_io_chosen_oh_0[8] & _input_buffer_io_deq_8_bits_tail | _salloc_arb_io_chosen_oh_0[9] & _input_buffer_io_deq_9_bits_tail;	// @[InputUnit.scala:180:28, :279:26, :318:8, Mux.scala:27:73, :29:36]
    salloc_outs_0_flit_payload <= (_salloc_arb_io_chosen_oh_0[0] ? _input_buffer_io_deq_0_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[1] ? _input_buffer_io_deq_1_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[2] ? _input_buffer_io_deq_2_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[3] ? _input_buffer_io_deq_3_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[4] ? _input_buffer_io_deq_4_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[5] ? _input_buffer_io_deq_5_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[6] ? _input_buffer_io_deq_6_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[7] ? _input_buffer_io_deq_7_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[8] ? _input_buffer_io_deq_8_bits_payload : 73'h0) | (_salloc_arb_io_chosen_oh_0[9] ? _input_buffer_io_deq_9_bits_payload : 73'h0);	// @[InputUnit.scala:180:28, :279:26, :318:8, Mux.scala:27:73, :29:36]
    salloc_outs_0_flit_flow_vnet_id <= (_salloc_arb_io_chosen_oh_0[0] ? states_0_flow_vnet_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_vnet_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[3] ? states_3_flow_vnet_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[4] ? states_4_flow_vnet_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_vnet_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_vnet_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_vnet_id : 3'h0);	// @[InputUnit.scala:191:19, :197:27, :279:26, :318:8, Mux.scala:27:73, :29:36]
    salloc_outs_0_flit_flow_ingress_node <= (_salloc_arb_io_chosen_oh_0[0] ? states_0_flow_ingress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_ingress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[3] ? states_3_flow_ingress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[4] ? states_4_flow_ingress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_ingress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_ingress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_ingress_node : 4'h0);	// @[InputUnit.scala:191:19, :199:20, :279:26, :318:8, Mux.scala:27:73, :29:36]
    salloc_outs_0_flit_flow_ingress_node_id <= (_salloc_arb_io_chosen_oh_0[0] ? states_0_flow_ingress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_ingress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[3] ? states_3_flow_ingress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[4] ? states_4_flow_ingress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_ingress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_ingress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_ingress_node_id : 3'h0);	// @[InputUnit.scala:191:19, :197:27, :279:26, :318:8, Mux.scala:27:73, :29:36]
    salloc_outs_0_flit_flow_egress_node <= (_salloc_arb_io_chosen_oh_0[0] ? states_0_flow_egress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_egress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[3] ? states_3_flow_egress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[4] ? states_4_flow_egress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_egress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_egress_node : 4'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_egress_node : 4'h0);	// @[InputUnit.scala:191:19, :199:20, :279:26, :318:8, Mux.scala:27:73, :29:36]
    salloc_outs_0_flit_flow_egress_node_id <= (_salloc_arb_io_chosen_oh_0[0] ? states_0_flow_egress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[1] ? states_1_flow_egress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[3] ? states_3_flow_egress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[4] ? states_4_flow_egress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[5] ? states_5_flow_egress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[8] ? states_8_flow_egress_node_id : 3'h0) | (_salloc_arb_io_chosen_oh_0[9] ? states_9_flow_egress_node_id : 3'h0);	// @[InputUnit.scala:191:19, :197:27, :279:26, :318:8, Mux.scala:27:73, :29:36]
    if (reset)
      mask <= 10'h0;	// @[InputUnit.scala:233:21]
    else if (_route_arbiter_io_out_valid)	// @[InputUnit.scala:186:29]
      mask <= _mask_T[9:0] - 10'h1;	// @[InputUnit.scala:233:21, :240:{18,53}]
    else if (vcalloc_vals_0 | vcalloc_vals_1 | vcalloc_vals_3 | vcalloc_vals_4 | vcalloc_vals_5 | vcalloc_vals_8 | vcalloc_vals_9)	// @[InputUnit.scala:249:32, package.scala:73:59]
      mask <= {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, vcalloc_sel[0]} | {2{vcalloc_sel[1]}}} | {3{vcalloc_sel[2]}}} | {4{vcalloc_sel[3]}}} | {5{vcalloc_sel[4]}}} | {6{vcalloc_sel[5]}}} | {7{vcalloc_sel[6]}}} | {8{vcalloc_sel[7]}}} | {9{vcalloc_sel[8]}}} | {10{vcalloc_sel[9]}};	// @[InputUnit.scala:233:21, :237:58, Mux.scala:27:73, :29:36]
  end // always @(posedge)
  `ifndef SYNTHESIS
    wire  [15:0][2:0] _GEN_33 = {{states_0_g}, {states_0_g}, {states_0_g}, {states_0_g}, {states_0_g}, {states_0_g}, {states_9_g}, {states_8_g}, {3'h0}, {3'h0}, {states_5_g}, {states_4_g}, {states_3_g}, {3'h0}, {states_1_g}, {states_0_g}};	// @[InputUnit.scala:191:19, :197:27]
    always @(posedge clock) begin	// @[InputUnit.scala:196:13]
      if (_T & ~reset & io_in_flit_0_bits_virt_channel_id > 4'h9) begin	// @[InputUnit.scala:194:32, :196:{13,17}, :199:20]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:196:13]
          $error("Assertion failed\n    at InputUnit.scala:196 assert(id < nVirtualChannels.U)\n");	// @[InputUnit.scala:196:13]
        if (`STOP_COND_)	// @[InputUnit.scala:196:13]
          $fatal;	// @[InputUnit.scala:196:13]
      end
      if (_T & ~reset & (|_GEN_33[io_in_flit_0_bits_virt_channel_id])) begin	// @[InputUnit.scala:194:32, :197:{13,27}]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:197:13]
          $error("Assertion failed\n    at InputUnit.scala:197 assert(states(id).g === g_i)\n");	// @[InputUnit.scala:197:13]
        if (`STOP_COND_)	// @[InputUnit.scala:197:13]
          $fatal;	// @[InputUnit.scala:197:13]
      end
      if (_route_arbiter_io_out_valid & ~reset & _GEN_33[_route_arbiter_io_out_bits_src_virt_id] != 3'h1) begin	// @[InputUnit.scala:186:29, :197:27, :199:26, :224:{11,25}]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:224:11]
          $error("Assertion failed\n    at InputUnit.scala:224 assert(states(id).g === g_r)\n");	// @[InputUnit.scala:224:11]
        if (`STOP_COND_)	// @[InputUnit.scala:224:11]
          $fatal;	// @[InputUnit.scala:224:11]
      end
      if (_GEN & ~reset & ~vcalloc_vals_0) begin	// @[InputUnit.scala:249:32, :270:29, :274:17]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
      if (_GEN_0 & ~reset & ~vcalloc_vals_1) begin	// @[InputUnit.scala:249:32, :270:29, :274:17]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
      if (_T_65 & vcalloc_sel[2] & ~reset) begin	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :274:17, Mux.scala:29:36]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
      if (_GEN_1 & ~reset & ~vcalloc_vals_3) begin	// @[InputUnit.scala:249:32, :270:29, :274:17]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
      if (_GEN_2 & ~reset & ~vcalloc_vals_4) begin	// @[InputUnit.scala:249:32, :270:29, :274:17]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
      if (_GEN_3 & ~reset & ~vcalloc_vals_5) begin	// @[InputUnit.scala:249:32, :270:29, :274:17]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
      if (_T_65 & vcalloc_sel[6] & ~reset) begin	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :274:17, Mux.scala:29:36]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
      if (_T_65 & vcalloc_sel[7] & ~reset) begin	// @[Decoupled.scala:51:35, InputUnit.scala:237:58, :274:17, Mux.scala:29:36]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
      if (_GEN_4 & ~reset & ~vcalloc_vals_8) begin	// @[InputUnit.scala:249:32, :270:29, :274:17]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
      if (_GEN_5 & ~reset & ~vcalloc_vals_9) begin	// @[InputUnit.scala:249:32, :270:29, :274:17]
        if (`ASSERT_VERBOSE_COND_)	// @[InputUnit.scala:274:17]
          $error("Assertion failed\n    at InputUnit.scala:274 assert(states(i).g === g_v)\n");	// @[InputUnit.scala:274:17]
        if (`STOP_COND_)	// @[InputUnit.scala:274:17]
          $fatal;	// @[InputUnit.scala:274:17]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0]      _RANDOM_0;
    logic [31:0]      _RANDOM_1;
    logic [31:0]      _RANDOM_2;
    logic [31:0]      _RANDOM_3;
    logic [31:0]      _RANDOM_4;
    logic [31:0]      _RANDOM_5;
    logic [31:0]      _RANDOM_6;
    logic [31:0]      _RANDOM_7;
    logic [31:0]      _RANDOM_8;
    logic [31:0]      _RANDOM_9;
    logic [31:0]      _RANDOM_10;
    logic [31:0]      _RANDOM_11;
    logic [31:0]      _RANDOM_12;
    logic [31:0]      _RANDOM_13;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        states_0_g = _RANDOM_0[2:0];	// @[InputUnit.scala:191:19]
        states_0_vc_sel_3_0 = _RANDOM_0[3];	// @[InputUnit.scala:191:19]
        states_0_vc_sel_2_0 = _RANDOM_0[4];	// @[InputUnit.scala:191:19]
        states_0_vc_sel_1_0 = _RANDOM_0[5];	// @[InputUnit.scala:191:19]
        states_0_vc_sel_0_0 = _RANDOM_0[6];	// @[InputUnit.scala:191:19]
        states_0_flow_vnet_id = _RANDOM_0[18:16];	// @[InputUnit.scala:191:19]
        states_0_flow_ingress_node = _RANDOM_0[22:19];	// @[InputUnit.scala:191:19]
        states_0_flow_ingress_node_id = _RANDOM_0[25:23];	// @[InputUnit.scala:191:19]
        states_0_flow_egress_node = _RANDOM_0[29:26];	// @[InputUnit.scala:191:19]
        states_0_flow_egress_node_id = {_RANDOM_0[31:30], _RANDOM_1[0]};	// @[InputUnit.scala:191:19]
        states_1_g = _RANDOM_1[3:1];	// @[InputUnit.scala:191:19]
        states_1_vc_sel_3_0 = _RANDOM_1[4];	// @[InputUnit.scala:191:19]
        states_1_vc_sel_2_0 = _RANDOM_1[5];	// @[InputUnit.scala:191:19]
        states_1_vc_sel_1_0 = _RANDOM_1[6];	// @[InputUnit.scala:191:19]
        states_1_vc_sel_0_0 = _RANDOM_1[7];	// @[InputUnit.scala:191:19]
        states_1_vc_sel_0_1 = _RANDOM_1[8];	// @[InputUnit.scala:191:19]
        states_1_flow_vnet_id = _RANDOM_1[19:17];	// @[InputUnit.scala:191:19]
        states_1_flow_ingress_node = _RANDOM_1[23:20];	// @[InputUnit.scala:191:19]
        states_1_flow_ingress_node_id = _RANDOM_1[26:24];	// @[InputUnit.scala:191:19]
        states_1_flow_egress_node = _RANDOM_1[30:27];	// @[InputUnit.scala:191:19]
        states_1_flow_egress_node_id = {_RANDOM_1[31], _RANDOM_2[1:0]};	// @[InputUnit.scala:191:19]
        states_3_g = _RANDOM_3[5:3];	// @[InputUnit.scala:191:19]
        states_3_vc_sel_3_0 = _RANDOM_3[6];	// @[InputUnit.scala:191:19]
        states_3_vc_sel_2_0 = _RANDOM_3[7];	// @[InputUnit.scala:191:19]
        states_3_vc_sel_1_0 = _RANDOM_3[8];	// @[InputUnit.scala:191:19]
        states_3_vc_sel_0_3 = _RANDOM_3[12];	// @[InputUnit.scala:191:19]
        states_3_flow_vnet_id = _RANDOM_3[21:19];	// @[InputUnit.scala:191:19]
        states_3_flow_ingress_node = _RANDOM_3[25:22];	// @[InputUnit.scala:191:19]
        states_3_flow_ingress_node_id = _RANDOM_3[28:26];	// @[InputUnit.scala:191:19]
        states_3_flow_egress_node = {_RANDOM_3[31:29], _RANDOM_4[0]};	// @[InputUnit.scala:191:19]
        states_3_flow_egress_node_id = _RANDOM_4[3:1];	// @[InputUnit.scala:191:19]
        states_4_g = _RANDOM_4[6:4];	// @[InputUnit.scala:191:19]
        states_4_vc_sel_3_0 = _RANDOM_4[7];	// @[InputUnit.scala:191:19]
        states_4_vc_sel_2_0 = _RANDOM_4[8];	// @[InputUnit.scala:191:19]
        states_4_vc_sel_1_0 = _RANDOM_4[9];	// @[InputUnit.scala:191:19]
        states_4_vc_sel_0_4 = _RANDOM_4[14];	// @[InputUnit.scala:191:19]
        states_4_flow_vnet_id = _RANDOM_4[22:20];	// @[InputUnit.scala:191:19]
        states_4_flow_ingress_node = _RANDOM_4[26:23];	// @[InputUnit.scala:191:19]
        states_4_flow_ingress_node_id = _RANDOM_4[29:27];	// @[InputUnit.scala:191:19]
        states_4_flow_egress_node = {_RANDOM_4[31:30], _RANDOM_5[1:0]};	// @[InputUnit.scala:191:19]
        states_4_flow_egress_node_id = _RANDOM_5[4:2];	// @[InputUnit.scala:191:19]
        states_5_g = _RANDOM_5[7:5];	// @[InputUnit.scala:191:19]
        states_5_vc_sel_3_0 = _RANDOM_5[8];	// @[InputUnit.scala:191:19]
        states_5_vc_sel_2_0 = _RANDOM_5[9];	// @[InputUnit.scala:191:19]
        states_5_vc_sel_1_0 = _RANDOM_5[10];	// @[InputUnit.scala:191:19]
        states_5_vc_sel_0_4 = _RANDOM_5[15];	// @[InputUnit.scala:191:19]
        states_5_vc_sel_0_5 = _RANDOM_5[16];	// @[InputUnit.scala:191:19]
        states_5_flow_vnet_id = _RANDOM_5[23:21];	// @[InputUnit.scala:191:19]
        states_5_flow_ingress_node = _RANDOM_5[27:24];	// @[InputUnit.scala:191:19]
        states_5_flow_ingress_node_id = _RANDOM_5[30:28];	// @[InputUnit.scala:191:19]
        states_5_flow_egress_node = {_RANDOM_5[31], _RANDOM_6[2:0]};	// @[InputUnit.scala:191:19]
        states_5_flow_egress_node_id = _RANDOM_6[5:3];	// @[InputUnit.scala:191:19]
        states_8_g = _RANDOM_8[10:8];	// @[InputUnit.scala:191:19]
        states_8_vc_sel_3_0 = _RANDOM_8[11];	// @[InputUnit.scala:191:19]
        states_8_vc_sel_2_0 = _RANDOM_8[12];	// @[InputUnit.scala:191:19]
        states_8_vc_sel_1_0 = _RANDOM_8[13];	// @[InputUnit.scala:191:19]
        states_8_vc_sel_0_8 = _RANDOM_8[22];	// @[InputUnit.scala:191:19]
        states_8_flow_vnet_id = _RANDOM_8[26:24];	// @[InputUnit.scala:191:19]
        states_8_flow_ingress_node = _RANDOM_8[30:27];	// @[InputUnit.scala:191:19]
        states_8_flow_ingress_node_id = {_RANDOM_8[31], _RANDOM_9[1:0]};	// @[InputUnit.scala:191:19]
        states_8_flow_egress_node = _RANDOM_9[5:2];	// @[InputUnit.scala:191:19]
        states_8_flow_egress_node_id = _RANDOM_9[8:6];	// @[InputUnit.scala:191:19]
        states_9_g = _RANDOM_9[11:9];	// @[InputUnit.scala:191:19]
        states_9_vc_sel_3_0 = _RANDOM_9[12];	// @[InputUnit.scala:191:19]
        states_9_vc_sel_2_0 = _RANDOM_9[13];	// @[InputUnit.scala:191:19]
        states_9_vc_sel_1_0 = _RANDOM_9[14];	// @[InputUnit.scala:191:19]
        states_9_vc_sel_0_8 = _RANDOM_9[23];	// @[InputUnit.scala:191:19]
        states_9_vc_sel_0_9 = _RANDOM_9[24];	// @[InputUnit.scala:191:19]
        states_9_flow_vnet_id = _RANDOM_9[27:25];	// @[InputUnit.scala:191:19]
        states_9_flow_ingress_node = _RANDOM_9[31:28];	// @[InputUnit.scala:191:19]
        states_9_flow_ingress_node_id = _RANDOM_10[2:0];	// @[InputUnit.scala:191:19]
        states_9_flow_egress_node = _RANDOM_10[6:3];	// @[InputUnit.scala:191:19]
        states_9_flow_egress_node_id = _RANDOM_10[9:7];	// @[InputUnit.scala:191:19]
        mask = _RANDOM_10[19:10];	// @[InputUnit.scala:191:19, :233:21]
        salloc_outs_0_valid = _RANDOM_10[20];	// @[InputUnit.scala:191:19, :318:8]
        salloc_outs_0_out_vid = _RANDOM_10[28:25];	// @[InputUnit.scala:191:19, :318:8]
        salloc_outs_0_flit_head = _RANDOM_10[29];	// @[InputUnit.scala:191:19, :318:8]
        salloc_outs_0_flit_tail = _RANDOM_10[30];	// @[InputUnit.scala:191:19, :318:8]
        salloc_outs_0_flit_payload = {_RANDOM_10[31], _RANDOM_11, _RANDOM_12, _RANDOM_13[7:0]};	// @[InputUnit.scala:191:19, :318:8]
        salloc_outs_0_flit_flow_vnet_id = _RANDOM_13[10:8];	// @[InputUnit.scala:318:8]
        salloc_outs_0_flit_flow_ingress_node = _RANDOM_13[14:11];	// @[InputUnit.scala:318:8]
        salloc_outs_0_flit_flow_ingress_node_id = _RANDOM_13[17:15];	// @[InputUnit.scala:318:8]
        salloc_outs_0_flit_flow_egress_node = _RANDOM_13[21:18];	// @[InputUnit.scala:318:8]
        salloc_outs_0_flit_flow_egress_node_id = _RANDOM_13[24:22];	// @[InputUnit.scala:318:8]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  InputBuffer_4 input_buffer (	// @[InputUnit.scala:180:28]
    .clock                         (clock),
    .reset                         (reset),
    .io_enq_0_valid                (io_in_flit_0_valid),
    .io_enq_0_bits_head            (io_in_flit_0_bits_head),
    .io_enq_0_bits_tail            (io_in_flit_0_bits_tail),
    .io_enq_0_bits_payload         (io_in_flit_0_bits_payload),
    .io_enq_0_bits_virt_channel_id (io_in_flit_0_bits_virt_channel_id),
    .io_deq_0_ready                (_salloc_arb_io_in_0_ready),	// @[InputUnit.scala:279:26]
    .io_deq_1_ready                (_salloc_arb_io_in_1_ready),	// @[InputUnit.scala:279:26]
    .io_deq_3_ready                (_salloc_arb_io_in_3_ready),	// @[InputUnit.scala:279:26]
    .io_deq_4_ready                (_salloc_arb_io_in_4_ready),	// @[InputUnit.scala:279:26]
    .io_deq_5_ready                (_salloc_arb_io_in_5_ready),	// @[InputUnit.scala:279:26]
    .io_deq_8_ready                (_salloc_arb_io_in_8_ready),	// @[InputUnit.scala:279:26]
    .io_deq_9_ready                (_salloc_arb_io_in_9_ready),	// @[InputUnit.scala:279:26]
    .io_deq_0_valid                (_input_buffer_io_deq_0_valid),
    .io_deq_0_bits_head            (_input_buffer_io_deq_0_bits_head),
    .io_deq_0_bits_tail            (_input_buffer_io_deq_0_bits_tail),
    .io_deq_0_bits_payload         (_input_buffer_io_deq_0_bits_payload),
    .io_deq_1_valid                (_input_buffer_io_deq_1_valid),
    .io_deq_1_bits_head            (_input_buffer_io_deq_1_bits_head),
    .io_deq_1_bits_tail            (_input_buffer_io_deq_1_bits_tail),
    .io_deq_1_bits_payload         (_input_buffer_io_deq_1_bits_payload),
    .io_deq_2_bits_head            (_input_buffer_io_deq_2_bits_head),
    .io_deq_2_bits_tail            (_input_buffer_io_deq_2_bits_tail),
    .io_deq_2_bits_payload         (_input_buffer_io_deq_2_bits_payload),
    .io_deq_3_valid                (_input_buffer_io_deq_3_valid),
    .io_deq_3_bits_head            (_input_buffer_io_deq_3_bits_head),
    .io_deq_3_bits_tail            (_input_buffer_io_deq_3_bits_tail),
    .io_deq_3_bits_payload         (_input_buffer_io_deq_3_bits_payload),
    .io_deq_4_valid                (_input_buffer_io_deq_4_valid),
    .io_deq_4_bits_head            (_input_buffer_io_deq_4_bits_head),
    .io_deq_4_bits_tail            (_input_buffer_io_deq_4_bits_tail),
    .io_deq_4_bits_payload         (_input_buffer_io_deq_4_bits_payload),
    .io_deq_5_valid                (_input_buffer_io_deq_5_valid),
    .io_deq_5_bits_head            (_input_buffer_io_deq_5_bits_head),
    .io_deq_5_bits_tail            (_input_buffer_io_deq_5_bits_tail),
    .io_deq_5_bits_payload         (_input_buffer_io_deq_5_bits_payload),
    .io_deq_6_bits_head            (_input_buffer_io_deq_6_bits_head),
    .io_deq_6_bits_tail            (_input_buffer_io_deq_6_bits_tail),
    .io_deq_6_bits_payload         (_input_buffer_io_deq_6_bits_payload),
    .io_deq_7_bits_head            (_input_buffer_io_deq_7_bits_head),
    .io_deq_7_bits_tail            (_input_buffer_io_deq_7_bits_tail),
    .io_deq_7_bits_payload         (_input_buffer_io_deq_7_bits_payload),
    .io_deq_8_valid                (_input_buffer_io_deq_8_valid),
    .io_deq_8_bits_head            (_input_buffer_io_deq_8_bits_head),
    .io_deq_8_bits_tail            (_input_buffer_io_deq_8_bits_tail),
    .io_deq_8_bits_payload         (_input_buffer_io_deq_8_bits_payload),
    .io_deq_9_valid                (_input_buffer_io_deq_9_valid),
    .io_deq_9_bits_head            (_input_buffer_io_deq_9_bits_head),
    .io_deq_9_bits_tail            (_input_buffer_io_deq_9_bits_tail),
    .io_deq_9_bits_payload         (_input_buffer_io_deq_9_bits_payload)
  );
  Arbiter route_arbiter (	// @[InputUnit.scala:186:29]
    .io_in_0_valid                     (_route_arbiter_io_in_0_valid_T),	// @[InputUnit.scala:212:22]
    .io_in_0_bits_flow_vnet_id         (states_0_flow_vnet_id),	// @[InputUnit.scala:191:19]
    .io_in_0_bits_flow_ingress_node    (states_0_flow_ingress_node),	// @[InputUnit.scala:191:19]
    .io_in_0_bits_flow_ingress_node_id (states_0_flow_ingress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_0_bits_flow_egress_node     (states_0_flow_egress_node),	// @[InputUnit.scala:191:19]
    .io_in_0_bits_flow_egress_node_id  (states_0_flow_egress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_1_valid                     (_route_arbiter_io_in_1_valid_T),	// @[InputUnit.scala:212:22]
    .io_in_1_bits_src_virt_id          (4'h1),	// @[InputUnit.scala:199:20]
    .io_in_1_bits_flow_vnet_id         (states_1_flow_vnet_id),	// @[InputUnit.scala:191:19]
    .io_in_1_bits_flow_ingress_node    (states_1_flow_ingress_node),	// @[InputUnit.scala:191:19]
    .io_in_1_bits_flow_ingress_node_id (states_1_flow_ingress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_1_bits_flow_egress_node     (states_1_flow_egress_node),	// @[InputUnit.scala:191:19]
    .io_in_1_bits_flow_egress_node_id  (states_1_flow_egress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_2_valid                     (1'h0),
    .io_in_2_bits_src_virt_id          (4'h0),	// @[InputUnit.scala:199:20]
    .io_in_2_bits_flow_vnet_id         (3'h0),	// @[InputUnit.scala:197:27]
    .io_in_2_bits_flow_ingress_node    (4'h0),	// @[InputUnit.scala:199:20]
    .io_in_2_bits_flow_ingress_node_id (3'h0),	// @[InputUnit.scala:197:27]
    .io_in_2_bits_flow_egress_node     (4'h0),	// @[InputUnit.scala:199:20]
    .io_in_2_bits_flow_egress_node_id  (3'h0),	// @[InputUnit.scala:197:27]
    .io_in_3_valid                     (_route_arbiter_io_in_3_valid_T),	// @[InputUnit.scala:212:22]
    .io_in_3_bits_src_virt_id          (4'h3),	// @[InputUnit.scala:199:20]
    .io_in_3_bits_flow_vnet_id         (states_3_flow_vnet_id),	// @[InputUnit.scala:191:19]
    .io_in_3_bits_flow_ingress_node    (states_3_flow_ingress_node),	// @[InputUnit.scala:191:19]
    .io_in_3_bits_flow_ingress_node_id (states_3_flow_ingress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_3_bits_flow_egress_node     (states_3_flow_egress_node),	// @[InputUnit.scala:191:19]
    .io_in_3_bits_flow_egress_node_id  (states_3_flow_egress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_4_valid                     (_route_arbiter_io_in_4_valid_T),	// @[InputUnit.scala:212:22]
    .io_in_4_bits_src_virt_id          (4'h4),	// @[InputUnit.scala:199:20]
    .io_in_4_bits_flow_vnet_id         (states_4_flow_vnet_id),	// @[InputUnit.scala:191:19]
    .io_in_4_bits_flow_ingress_node    (states_4_flow_ingress_node),	// @[InputUnit.scala:191:19]
    .io_in_4_bits_flow_ingress_node_id (states_4_flow_ingress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_4_bits_flow_egress_node     (states_4_flow_egress_node),	// @[InputUnit.scala:191:19]
    .io_in_4_bits_flow_egress_node_id  (states_4_flow_egress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_5_valid                     (_route_arbiter_io_in_5_valid_T),	// @[InputUnit.scala:212:22]
    .io_in_5_bits_src_virt_id          (4'h5),	// @[InputUnit.scala:199:20]
    .io_in_5_bits_flow_vnet_id         (states_5_flow_vnet_id),	// @[InputUnit.scala:191:19]
    .io_in_5_bits_flow_ingress_node    (states_5_flow_ingress_node),	// @[InputUnit.scala:191:19]
    .io_in_5_bits_flow_ingress_node_id (states_5_flow_ingress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_5_bits_flow_egress_node     (states_5_flow_egress_node),	// @[InputUnit.scala:191:19]
    .io_in_5_bits_flow_egress_node_id  (states_5_flow_egress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_6_valid                     (1'h0),
    .io_in_6_bits_src_virt_id          (4'h0),	// @[InputUnit.scala:199:20]
    .io_in_6_bits_flow_vnet_id         (3'h0),	// @[InputUnit.scala:197:27]
    .io_in_6_bits_flow_ingress_node    (4'h0),	// @[InputUnit.scala:199:20]
    .io_in_6_bits_flow_ingress_node_id (3'h0),	// @[InputUnit.scala:197:27]
    .io_in_6_bits_flow_egress_node     (4'h0),	// @[InputUnit.scala:199:20]
    .io_in_6_bits_flow_egress_node_id  (3'h0),	// @[InputUnit.scala:197:27]
    .io_in_7_valid                     (1'h0),
    .io_in_7_bits_src_virt_id          (4'h0),	// @[InputUnit.scala:199:20]
    .io_in_7_bits_flow_vnet_id         (3'h0),	// @[InputUnit.scala:197:27]
    .io_in_7_bits_flow_ingress_node    (4'h0),	// @[InputUnit.scala:199:20]
    .io_in_7_bits_flow_ingress_node_id (3'h0),	// @[InputUnit.scala:197:27]
    .io_in_7_bits_flow_egress_node     (4'h0),	// @[InputUnit.scala:199:20]
    .io_in_7_bits_flow_egress_node_id  (3'h0),	// @[InputUnit.scala:197:27]
    .io_in_8_valid                     (_route_arbiter_io_in_8_valid_T),	// @[InputUnit.scala:212:22]
    .io_in_8_bits_src_virt_id          (4'h8),	// @[InputUnit.scala:199:20]
    .io_in_8_bits_flow_vnet_id         (states_8_flow_vnet_id),	// @[InputUnit.scala:191:19]
    .io_in_8_bits_flow_ingress_node    (states_8_flow_ingress_node),	// @[InputUnit.scala:191:19]
    .io_in_8_bits_flow_ingress_node_id (states_8_flow_ingress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_8_bits_flow_egress_node     (states_8_flow_egress_node),	// @[InputUnit.scala:191:19]
    .io_in_8_bits_flow_egress_node_id  (states_8_flow_egress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_9_valid                     (_route_arbiter_io_in_9_valid_T),	// @[InputUnit.scala:212:22]
    .io_in_9_bits_src_virt_id          (4'h9),	// @[InputUnit.scala:199:20]
    .io_in_9_bits_flow_vnet_id         (states_9_flow_vnet_id),	// @[InputUnit.scala:191:19]
    .io_in_9_bits_flow_ingress_node    (states_9_flow_ingress_node),	// @[InputUnit.scala:191:19]
    .io_in_9_bits_flow_ingress_node_id (states_9_flow_ingress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_9_bits_flow_egress_node     (states_9_flow_egress_node),	// @[InputUnit.scala:191:19]
    .io_in_9_bits_flow_egress_node_id  (states_9_flow_egress_node_id),	// @[InputUnit.scala:191:19]
    .io_in_1_ready                     (_route_arbiter_io_in_1_ready),
    .io_in_2_ready                     (_route_arbiter_io_in_2_ready),
    .io_in_3_ready                     (_route_arbiter_io_in_3_ready),
    .io_in_4_ready                     (_route_arbiter_io_in_4_ready),
    .io_in_5_ready                     (_route_arbiter_io_in_5_ready),
    .io_in_6_ready                     (_route_arbiter_io_in_6_ready),
    .io_in_7_ready                     (_route_arbiter_io_in_7_ready),
    .io_in_8_ready                     (_route_arbiter_io_in_8_ready),
    .io_in_9_ready                     (_route_arbiter_io_in_9_ready),
    .io_out_valid                      (_route_arbiter_io_out_valid),
    .io_out_bits_src_virt_id           (_route_arbiter_io_out_bits_src_virt_id),
    .io_out_bits_flow_vnet_id          (io_router_req_bits_flow_vnet_id),
    .io_out_bits_flow_ingress_node     (io_router_req_bits_flow_ingress_node),
    .io_out_bits_flow_ingress_node_id  (io_router_req_bits_flow_ingress_node_id),
    .io_out_bits_flow_egress_node      (io_router_req_bits_flow_egress_node),
    .io_out_bits_flow_egress_node_id   (io_router_req_bits_flow_egress_node_id)
  );
  SwitchArbiter_19 salloc_arb (	// @[InputUnit.scala:279:26]
    .clock                    (clock),
    .reset                    (reset),
    .io_in_0_valid            (_salloc_arb_io_in_0_valid_T_2),	// @[InputUnit.scala:288:50]
    .io_in_0_bits_vc_sel_3_0  (states_0_vc_sel_3_0),	// @[InputUnit.scala:191:19]
    .io_in_0_bits_vc_sel_2_0  (states_0_vc_sel_2_0),	// @[InputUnit.scala:191:19]
    .io_in_0_bits_vc_sel_1_0  (states_0_vc_sel_1_0),	// @[InputUnit.scala:191:19]
    .io_in_0_bits_vc_sel_0_0  (states_0_vc_sel_0_0),	// @[InputUnit.scala:191:19]
    .io_in_0_bits_tail        (_input_buffer_io_deq_0_bits_tail),	// @[InputUnit.scala:180:28]
    .io_in_1_valid            (_salloc_arb_io_in_1_valid_T_2),	// @[InputUnit.scala:288:50]
    .io_in_1_bits_vc_sel_3_0  (states_1_vc_sel_3_0),	// @[InputUnit.scala:191:19]
    .io_in_1_bits_vc_sel_2_0  (states_1_vc_sel_2_0),	// @[InputUnit.scala:191:19]
    .io_in_1_bits_vc_sel_1_0  (states_1_vc_sel_1_0),	// @[InputUnit.scala:191:19]
    .io_in_1_bits_vc_sel_0_0  (states_1_vc_sel_0_0),	// @[InputUnit.scala:191:19]
    .io_in_1_bits_vc_sel_0_1  (states_1_vc_sel_0_1),	// @[InputUnit.scala:191:19]
    .io_in_1_bits_tail        (_input_buffer_io_deq_1_bits_tail),	// @[InputUnit.scala:180:28]
    .io_in_3_valid            (_salloc_arb_io_in_3_valid_T_2),	// @[InputUnit.scala:288:50]
    .io_in_3_bits_vc_sel_3_0  (states_3_vc_sel_3_0),	// @[InputUnit.scala:191:19]
    .io_in_3_bits_vc_sel_2_0  (states_3_vc_sel_2_0),	// @[InputUnit.scala:191:19]
    .io_in_3_bits_vc_sel_1_0  (states_3_vc_sel_1_0),	// @[InputUnit.scala:191:19]
    .io_in_3_bits_vc_sel_0_3  (states_3_vc_sel_0_3),	// @[InputUnit.scala:191:19]
    .io_in_3_bits_tail        (_input_buffer_io_deq_3_bits_tail),	// @[InputUnit.scala:180:28]
    .io_in_4_valid            (_salloc_arb_io_in_4_valid_T_2),	// @[InputUnit.scala:288:50]
    .io_in_4_bits_vc_sel_3_0  (states_4_vc_sel_3_0),	// @[InputUnit.scala:191:19]
    .io_in_4_bits_vc_sel_2_0  (states_4_vc_sel_2_0),	// @[InputUnit.scala:191:19]
    .io_in_4_bits_vc_sel_1_0  (states_4_vc_sel_1_0),	// @[InputUnit.scala:191:19]
    .io_in_4_bits_vc_sel_0_4  (states_4_vc_sel_0_4),	// @[InputUnit.scala:191:19]
    .io_in_4_bits_tail        (_input_buffer_io_deq_4_bits_tail),	// @[InputUnit.scala:180:28]
    .io_in_5_valid            (_salloc_arb_io_in_5_valid_T_2),	// @[InputUnit.scala:288:50]
    .io_in_5_bits_vc_sel_3_0  (states_5_vc_sel_3_0),	// @[InputUnit.scala:191:19]
    .io_in_5_bits_vc_sel_2_0  (states_5_vc_sel_2_0),	// @[InputUnit.scala:191:19]
    .io_in_5_bits_vc_sel_1_0  (states_5_vc_sel_1_0),	// @[InputUnit.scala:191:19]
    .io_in_5_bits_vc_sel_0_4  (states_5_vc_sel_0_4),	// @[InputUnit.scala:191:19]
    .io_in_5_bits_vc_sel_0_5  (states_5_vc_sel_0_5),	// @[InputUnit.scala:191:19]
    .io_in_5_bits_tail        (_input_buffer_io_deq_5_bits_tail),	// @[InputUnit.scala:180:28]
    .io_in_7_valid            (1'h0),
    .io_in_7_bits_vc_sel_3_0  (1'h0),
    .io_in_7_bits_vc_sel_2_0  (1'h0),
    .io_in_7_bits_vc_sel_1_0  (1'h0),
    .io_in_7_bits_vc_sel_0_7  (1'h0),
    .io_in_7_bits_tail        (1'h0),
    .io_in_8_valid            (_salloc_arb_io_in_8_valid_T_2),	// @[InputUnit.scala:288:50]
    .io_in_8_bits_vc_sel_3_0  (states_8_vc_sel_3_0),	// @[InputUnit.scala:191:19]
    .io_in_8_bits_vc_sel_2_0  (states_8_vc_sel_2_0),	// @[InputUnit.scala:191:19]
    .io_in_8_bits_vc_sel_1_0  (states_8_vc_sel_1_0),	// @[InputUnit.scala:191:19]
    .io_in_8_bits_vc_sel_0_8  (states_8_vc_sel_0_8),	// @[InputUnit.scala:191:19]
    .io_in_8_bits_tail        (_input_buffer_io_deq_8_bits_tail),	// @[InputUnit.scala:180:28]
    .io_in_9_valid            (_salloc_arb_io_in_9_valid_T_2),	// @[InputUnit.scala:288:50]
    .io_in_9_bits_vc_sel_3_0  (states_9_vc_sel_3_0),	// @[InputUnit.scala:191:19]
    .io_in_9_bits_vc_sel_2_0  (states_9_vc_sel_2_0),	// @[InputUnit.scala:191:19]
    .io_in_9_bits_vc_sel_1_0  (states_9_vc_sel_1_0),	// @[InputUnit.scala:191:19]
    .io_in_9_bits_vc_sel_0_8  (states_9_vc_sel_0_8),	// @[InputUnit.scala:191:19]
    .io_in_9_bits_vc_sel_0_9  (states_9_vc_sel_0_9),	// @[InputUnit.scala:191:19]
    .io_in_9_bits_tail        (_input_buffer_io_deq_9_bits_tail),	// @[InputUnit.scala:180:28]
    .io_out_0_ready           (io_salloc_req_0_ready),
    .io_in_0_ready            (_salloc_arb_io_in_0_ready),
    .io_in_1_ready            (_salloc_arb_io_in_1_ready),
    .io_in_3_ready            (_salloc_arb_io_in_3_ready),
    .io_in_4_ready            (_salloc_arb_io_in_4_ready),
    .io_in_5_ready            (_salloc_arb_io_in_5_ready),
    .io_in_7_ready            (_salloc_arb_io_in_7_ready),
    .io_in_8_ready            (_salloc_arb_io_in_8_ready),
    .io_in_9_ready            (_salloc_arb_io_in_9_ready),
    .io_out_0_valid           (_salloc_arb_io_out_0_valid),
    .io_out_0_bits_vc_sel_3_0 (io_salloc_req_0_bits_vc_sel_3_0),
    .io_out_0_bits_vc_sel_2_0 (io_salloc_req_0_bits_vc_sel_2_0),
    .io_out_0_bits_vc_sel_1_0 (io_salloc_req_0_bits_vc_sel_1_0),
    .io_out_0_bits_vc_sel_0_0 (io_salloc_req_0_bits_vc_sel_0_0),
    .io_out_0_bits_vc_sel_0_1 (io_salloc_req_0_bits_vc_sel_0_1),
    .io_out_0_bits_vc_sel_0_3 (io_salloc_req_0_bits_vc_sel_0_3),
    .io_out_0_bits_vc_sel_0_4 (io_salloc_req_0_bits_vc_sel_0_4),
    .io_out_0_bits_vc_sel_0_5 (io_salloc_req_0_bits_vc_sel_0_5),
    .io_out_0_bits_vc_sel_0_7 (io_salloc_req_0_bits_vc_sel_0_7),
    .io_out_0_bits_vc_sel_0_8 (io_salloc_req_0_bits_vc_sel_0_8),
    .io_out_0_bits_vc_sel_0_9 (io_salloc_req_0_bits_vc_sel_0_9),
    .io_out_0_bits_tail       (io_salloc_req_0_bits_tail),
    .io_chosen_oh_0           (_salloc_arb_io_chosen_oh_0)
  );
  assign io_router_req_bits_src_virt_id = _route_arbiter_io_out_bits_src_virt_id;	// @[InputUnit.scala:186:29]
  assign io_vcalloc_req_valid = _io_vcalloc_req_valid_output;	// @[package.scala:73:59]
  assign io_vcalloc_req_bits_vc_sel_3_0 = vcalloc_sel[0] & states_0_vc_sel_3_0 | vcalloc_sel[1] & states_1_vc_sel_3_0 | vcalloc_sel[3] & states_3_vc_sel_3_0 | vcalloc_sel[4] & states_4_vc_sel_3_0 | vcalloc_sel[5] & states_5_vc_sel_3_0 | vcalloc_sel[8] & states_8_vc_sel_3_0 | vcalloc_sel[9] & states_9_vc_sel_3_0;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_vcalloc_req_bits_vc_sel_2_0 = vcalloc_sel[0] & states_0_vc_sel_2_0 | vcalloc_sel[1] & states_1_vc_sel_2_0 | vcalloc_sel[3] & states_3_vc_sel_2_0 | vcalloc_sel[4] & states_4_vc_sel_2_0 | vcalloc_sel[5] & states_5_vc_sel_2_0 | vcalloc_sel[8] & states_8_vc_sel_2_0 | vcalloc_sel[9] & states_9_vc_sel_2_0;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_vcalloc_req_bits_vc_sel_1_0 = vcalloc_sel[0] & states_0_vc_sel_1_0 | vcalloc_sel[1] & states_1_vc_sel_1_0 | vcalloc_sel[3] & states_3_vc_sel_1_0 | vcalloc_sel[4] & states_4_vc_sel_1_0 | vcalloc_sel[5] & states_5_vc_sel_1_0 | vcalloc_sel[8] & states_8_vc_sel_1_0 | vcalloc_sel[9] & states_9_vc_sel_1_0;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_vcalloc_req_bits_vc_sel_0_0 = vcalloc_sel[0] & states_0_vc_sel_0_0 | vcalloc_sel[1] & states_1_vc_sel_0_0;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_vcalloc_req_bits_vc_sel_0_1 = vcalloc_sel[1] & states_1_vc_sel_0_1;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_vcalloc_req_bits_vc_sel_0_3 = vcalloc_sel[3] & states_3_vc_sel_0_3;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_vcalloc_req_bits_vc_sel_0_4 = vcalloc_sel[4] & states_4_vc_sel_0_4 | vcalloc_sel[5] & states_5_vc_sel_0_4;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_vcalloc_req_bits_vc_sel_0_5 = vcalloc_sel[5] & states_5_vc_sel_0_5;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_vcalloc_req_bits_vc_sel_0_8 = vcalloc_sel[8] & states_8_vc_sel_0_8 | vcalloc_sel[9] & states_9_vc_sel_0_8;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_vcalloc_req_bits_vc_sel_0_9 = vcalloc_sel[9] & states_9_vc_sel_0_9;	// @[InputUnit.scala:191:19, :237:58, Mux.scala:27:73, :29:36]
  assign io_salloc_req_0_valid = _salloc_arb_io_out_0_valid;	// @[InputUnit.scala:279:26]
  assign io_out_0_valid = salloc_outs_0_valid;	// @[InputUnit.scala:318:8]
  assign io_out_0_bits_flit_head = salloc_outs_0_flit_head;	// @[InputUnit.scala:318:8]
  assign io_out_0_bits_flit_tail = salloc_outs_0_flit_tail;	// @[InputUnit.scala:318:8]
  assign io_out_0_bits_flit_payload = salloc_outs_0_flit_payload;	// @[InputUnit.scala:318:8]
  assign io_out_0_bits_flit_flow_vnet_id = salloc_outs_0_flit_flow_vnet_id;	// @[InputUnit.scala:318:8]
  assign io_out_0_bits_flit_flow_ingress_node = salloc_outs_0_flit_flow_ingress_node;	// @[InputUnit.scala:318:8]
  assign io_out_0_bits_flit_flow_ingress_node_id = salloc_outs_0_flit_flow_ingress_node_id;	// @[InputUnit.scala:318:8]
  assign io_out_0_bits_flit_flow_egress_node = salloc_outs_0_flit_flow_egress_node;	// @[InputUnit.scala:318:8]
  assign io_out_0_bits_flit_flow_egress_node_id = salloc_outs_0_flit_flow_egress_node_id;	// @[InputUnit.scala:318:8]
  assign io_out_0_bits_out_virt_channel = salloc_outs_0_out_vid;	// @[InputUnit.scala:318:8]
  assign io_debug_va_stall = {1'h0, {1'h0, {1'h0, vcalloc_vals_0} + {1'h0, vcalloc_vals_1}} + {1'h0, {1'h0, vcalloc_vals_3} + {1'h0, vcalloc_vals_4}}} + {1'h0, {2'h0, vcalloc_vals_5} + {1'h0, {1'h0, vcalloc_vals_8} + {1'h0, vcalloc_vals_9}}} - {3'h0, io_vcalloc_req_ready};	// @[Bitwise.scala:51:90, InputUnit.scala:197:27, :249:32, :266:47, Mux.scala:27:73]
  assign io_debug_sa_stall = {1'h0, {1'h0, {1'h0, _salloc_arb_io_in_0_valid_T_2 & ~_salloc_arb_io_in_0_ready} + {1'h0, _salloc_arb_io_in_1_valid_T_2 & ~_salloc_arb_io_in_1_ready}} + {1'h0, {1'h0, _salloc_arb_io_in_3_valid_T_2 & ~_salloc_arb_io_in_3_ready} + {1'h0, _salloc_arb_io_in_4_valid_T_2 & ~_salloc_arb_io_in_4_ready}}} + {1'h0, {2'h0, _salloc_arb_io_in_5_valid_T_2 & ~_salloc_arb_io_in_5_ready} + {1'h0, {1'h0, _salloc_arb_io_in_8_valid_T_2 & ~_salloc_arb_io_in_8_ready} + {1'h0, _salloc_arb_io_in_9_valid_T_2 & ~_salloc_arb_io_in_9_ready}}};	// @[Bitwise.scala:51:90, InputUnit.scala:279:26, :288:50, :301:{67,70}, Mux.scala:27:73]
  assign io_in_credit_return = _T_130 ? _salloc_arb_io_chosen_oh_0 : 10'h0;	// @[Decoupled.scala:51:35, InputUnit.scala:233:21, :279:26, :322:8]
  assign io_in_vc_free = _T_130 & (_salloc_arb_io_chosen_oh_0[0] & _input_buffer_io_deq_0_bits_tail | _salloc_arb_io_chosen_oh_0[1] & _input_buffer_io_deq_1_bits_tail | _salloc_arb_io_chosen_oh_0[2] & _input_buffer_io_deq_2_bits_tail | _salloc_arb_io_chosen_oh_0[3] & _input_buffer_io_deq_3_bits_tail | _salloc_arb_io_chosen_oh_0[4] & _input_buffer_io_deq_4_bits_tail | _salloc_arb_io_chosen_oh_0[5] & _input_buffer_io_deq_5_bits_tail | _salloc_arb_io_chosen_oh_0[6] & _input_buffer_io_deq_6_bits_tail | _salloc_arb_io_chosen_oh_0[7] & _input_buffer_io_deq_7_bits_tail | _salloc_arb_io_chosen_oh_0[8] & _input_buffer_io_deq_8_bits_tail | _salloc_arb_io_chosen_oh_0[9] & _input_buffer_io_deq_9_bits_tail) ? _salloc_arb_io_chosen_oh_0 : 10'h0;	// @[Decoupled.scala:51:35, InputUnit.scala:180:28, :233:21, :279:26, :325:{8,18}, Mux.scala:27:73, :29:36]
endmodule

