// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module DigitalTop(
  input         auto_prci_ctrl_domain_resetSynchronizer_in_member_allClocks_uncore_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_prci_ctrl_domain_resetSynchronizer_in_member_allClocks_uncore_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                mem_axi4_0_aw_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
                mem_axi4_0_w_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
                mem_axi4_0_b_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  input  [3:0]  mem_axi4_0_b_bits_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  input  [1:0]  mem_axi4_0_b_bits_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  input         mem_axi4_0_ar_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
                mem_axi4_0_r_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  input  [3:0]  mem_axi4_0_r_bits_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  input  [63:0] mem_axi4_0_r_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  input  [1:0]  mem_axi4_0_r_bits_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  input         mem_axi4_0_r_bits_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
                uart_tsi_io_uart_rxd,	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:50:27]
                serial_tl_clock,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:146:24]
                serial_tl_bits_in_valid,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:146:24]
                serial_tl_bits_in_bits,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:146:24]
                serial_tl_bits_out_ready,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:146:24]
  output        auto_subsystem_mbus_fixedClockNode_out_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_subsystem_mbus_fixedClockNode_out_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                mem_axi4_0_aw_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [3:0]  mem_axi4_0_aw_bits_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [32:0] mem_axi4_0_aw_bits_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [7:0]  mem_axi4_0_aw_bits_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [2:0]  mem_axi4_0_aw_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [1:0]  mem_axi4_0_aw_bits_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output        mem_axi4_0_aw_bits_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [3:0]  mem_axi4_0_aw_bits_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [2:0]  mem_axi4_0_aw_bits_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [3:0]  mem_axi4_0_aw_bits_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output        mem_axi4_0_w_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [63:0] mem_axi4_0_w_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [7:0]  mem_axi4_0_w_bits_strb,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output        mem_axi4_0_w_bits_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
                mem_axi4_0_b_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
                mem_axi4_0_ar_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [3:0]  mem_axi4_0_ar_bits_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [32:0] mem_axi4_0_ar_bits_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [7:0]  mem_axi4_0_ar_bits_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [2:0]  mem_axi4_0_ar_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [1:0]  mem_axi4_0_ar_bits_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output        mem_axi4_0_ar_bits_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [3:0]  mem_axi4_0_ar_bits_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [2:0]  mem_axi4_0_ar_bits_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output [3:0]  mem_axi4_0_ar_bits_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
  output        mem_axi4_0_r_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/Nodes.scala:1713:17]
                uart_tsi_io_uart_txd,	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:50:27]
                uart_tsi_io_dropped,	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:50:27]
  output [3:0]  uart_tsi_io_tsi2tl_state,	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:50:27]
  output        serial_tl_bits_in_ready,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:146:24]
                serial_tl_bits_out_valid,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:146:24]
                serial_tl_bits_out_bits	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:146:24]
);

  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_cbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_cbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_mbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_mbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_fbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_fbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_2_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_2_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_1_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_1_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_cbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_cbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_mbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_mbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_fbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_fbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_2_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_2_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_1_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_1_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_4_member_subsystem_cbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_4_member_subsystem_cbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_3_member_subsystem_mbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_3_member_subsystem_mbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_2_member_subsystem_fbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_2_member_subsystem_fbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_2_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_2_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_1_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_1_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  wire        _aggregator_auto_out_4_member_subsystem_cbus_subsystem_cbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_4_member_subsystem_cbus_subsystem_cbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_3_member_subsystem_mbus_subsystem_mbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_3_member_subsystem_mbus_subsystem_mbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_2_member_subsystem_fbus_subsystem_fbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_2_member_subsystem_fbus_subsystem_fbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_2_clock;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_2_reset;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_1_clock;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_1_reset;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_0_clock;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_0_reset;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
  wire        _prci_ctrl_domain_auto_resetSynchronizer_out_member_allClocks_uncore_clock;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:39:36]
  wire        _prci_ctrl_domain_auto_resetSynchronizer_out_member_allClocks_uncore_reset;	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:39:36]
  wire        _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [3:0]  _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [30:0] _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [7:0]  _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [63:0] _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_obus_auto_fixer_in_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_obus_auto_fixer_in_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_obus_auto_fixer_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [1:0]  _subsystem_obus_auto_fixer_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_obus_auto_fixer_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [4:0]  _subsystem_obus_auto_fixer_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_obus_auto_fixer_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_obus_auto_fixer_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [63:0] _subsystem_obus_auto_fixer_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_obus_auto_fixer_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [2:0]  _subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [2:0]  _subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [2:0]  _subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [6:0]  _subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [32:0] _subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [7:0]  _subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [63:0] _subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire        _subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire        _subsystem_l2_wrapper_auto_coherent_jbar_in_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire        _subsystem_l2_wrapper_auto_coherent_jbar_in_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [2:0]  _subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [1:0]  _subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [2:0]  _subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [4:0]  _subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [1:0]  _subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire        _subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire [63:0] _subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire        _subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
  wire        _subsystem_mbus_auto_bus_xing_in_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
  wire        _subsystem_mbus_auto_bus_xing_in_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
  wire [2:0]  _subsystem_mbus_auto_bus_xing_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
  wire [2:0]  _subsystem_mbus_auto_bus_xing_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
  wire [6:0]  _subsystem_mbus_auto_bus_xing_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
  wire        _subsystem_mbus_auto_bus_xing_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
  wire [63:0] _subsystem_mbus_auto_bus_xing_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
  wire        _subsystem_mbus_auto_bus_xing_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
  wire        _subsystem_fbus_auto_tlserial_manager_crossing_in_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire        _subsystem_fbus_auto_tlserial_manager_crossing_in_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [2:0]  _subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [1:0]  _subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [2:0]  _subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [3:0]  _subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire        _subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire        _subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [63:0] _subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire        _subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire        _subsystem_fbus_auto_bus_xing_out_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [2:0]  _subsystem_fbus_auto_bus_xing_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [2:0]  _subsystem_fbus_auto_bus_xing_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [2:0]  _subsystem_fbus_auto_bus_xing_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [4:0]  _subsystem_fbus_auto_bus_xing_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [32:0] _subsystem_fbus_auto_bus_xing_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [7:0]  _subsystem_fbus_auto_bus_xing_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire [63:0] _subsystem_fbus_auto_bus_xing_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire        _subsystem_fbus_auto_bus_xing_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire        _subsystem_fbus_auto_bus_xing_out_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
  wire        _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [4:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [30:0] _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [7:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [63:0] _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [4:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [32:0] _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [7:0]  _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [63:0] _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [1:0]  _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [2:0]  _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [4:0]  _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [1:0]  _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire [63:0] _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_subsystem_sbus_clock_groups_out_1_member_subsystem_obus_0_clock;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_subsystem_sbus_clock_groups_out_1_member_subsystem_obus_0_reset;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_subsystem_sbus_clock_groups_out_0_member_subsystem_l2_0_clock;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  wire        _subsystem_sbus_auto_subsystem_sbus_clock_groups_out_0_member_subsystem_l2_0_reset;	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
  SystemBus subsystem_sbus (	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_ready           (_subsystem_obus_auto_fixer_in_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_valid           (_subsystem_obus_auto_fixer_in_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_opcode     (_subsystem_obus_auto_fixer_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_param      (_subsystem_obus_auto_fixer_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_size       (_subsystem_obus_auto_fixer_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_source     (_subsystem_obus_auto_fixer_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_sink       (_subsystem_obus_auto_fixer_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_denied     (_subsystem_obus_auto_fixer_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_data       (_subsystem_obus_auto_fixer_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_bits_corrupt    (_subsystem_obus_auto_fixer_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_ready             (_subsystem_l2_wrapper_auto_coherent_jbar_in_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_valid             (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_bits_opcode       (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_bits_param        (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_bits_size         (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_bits_source       (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_bits_sink         (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_bits_denied       (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_bits_data         (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_bits_corrupt      (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_valid        (_subsystem_fbus_auto_bus_xing_out_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_bits_opcode  (_subsystem_fbus_auto_bus_xing_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_bits_param   (_subsystem_fbus_auto_bus_xing_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_bits_size    (_subsystem_fbus_auto_bus_xing_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_bits_source  (_subsystem_fbus_auto_bus_xing_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_bits_address (_subsystem_fbus_auto_bus_xing_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_bits_mask    (_subsystem_fbus_auto_bus_xing_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_bits_data    (_subsystem_fbus_auto_bus_xing_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_bits_corrupt (_subsystem_fbus_auto_bus_xing_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_ready        (_subsystem_fbus_auto_bus_xing_out_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_subsystem_sbus_clock_groups_in_member_subsystem_sbus_2_clock     (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_2_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_subsystem_sbus_clock_groups_in_member_subsystem_sbus_2_reset     (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_2_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_subsystem_sbus_clock_groups_in_member_subsystem_sbus_1_clock     (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_1_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_subsystem_sbus_clock_groups_in_member_subsystem_sbus_1_reset     (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_1_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_subsystem_sbus_clock_groups_in_member_subsystem_sbus_0_clock     (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_subsystem_sbus_clock_groups_in_member_subsystem_sbus_0_reset     (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_valid           (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_valid),
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_opcode     (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_opcode),
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_param      (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_param),
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_size       (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_size),
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_source     (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_source),
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_address    (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_address),
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_mask       (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_mask),
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_data       (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_data),
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_corrupt    (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_corrupt),
    .auto_coupler_to_bus_named_subsystem_obus_widget_out_d_ready           (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_d_ready),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_valid             (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_valid),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_opcode       (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_opcode),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_param        (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_param),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_size         (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_size),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_source       (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_source),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_address      (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_address),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_mask         (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_mask),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_data         (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_data),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_corrupt      (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_corrupt),
    .auto_coupler_to_bus_named_subsystem_l2_widget_out_d_ready             (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_d_ready),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_ready        (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_ready),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_valid        (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_valid),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_opcode  (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_opcode),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_param   (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_param),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_size    (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_size),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_source  (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_source),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_sink    (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_sink),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_denied  (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_denied),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_data    (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_data),
    .auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_corrupt (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_corrupt),
    .auto_subsystem_sbus_clock_groups_out_1_member_subsystem_obus_0_clock  (_subsystem_sbus_auto_subsystem_sbus_clock_groups_out_1_member_subsystem_obus_0_clock),
    .auto_subsystem_sbus_clock_groups_out_1_member_subsystem_obus_0_reset  (_subsystem_sbus_auto_subsystem_sbus_clock_groups_out_1_member_subsystem_obus_0_reset),
    .auto_subsystem_sbus_clock_groups_out_0_member_subsystem_l2_0_clock    (_subsystem_sbus_auto_subsystem_sbus_clock_groups_out_0_member_subsystem_l2_0_clock),
    .auto_subsystem_sbus_clock_groups_out_0_member_subsystem_l2_0_reset    (_subsystem_sbus_auto_subsystem_sbus_clock_groups_out_0_member_subsystem_l2_0_reset)
  );
  FrontBus subsystem_fbus (	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock (_clockNamePrefixer_auto_clock_name_prefixer_out_2_member_subsystem_fbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset (_clockNamePrefixer_auto_clock_name_prefixer_out_2_member_subsystem_fbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_tlserial_manager_crossing_in_a_valid                         (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_tlserial_manager_crossing_in_a_bits_opcode                   (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_tlserial_manager_crossing_in_a_bits_param                    (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_tlserial_manager_crossing_in_a_bits_size                     (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_tlserial_manager_crossing_in_a_bits_source                   (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_tlserial_manager_crossing_in_a_bits_address                  (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_tlserial_manager_crossing_in_a_bits_mask                     (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_tlserial_manager_crossing_in_a_bits_data                     (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_tlserial_manager_crossing_in_a_bits_corrupt                  (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_tlserial_manager_crossing_in_d_ready                         (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_a_ready                                         (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_d_valid                                         (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_d_bits_opcode                                   (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_d_bits_param                                    (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_d_bits_size                                     (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_d_bits_source                                   (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_d_bits_sink                                     (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_d_bits_denied                                   (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_d_bits_data                                     (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_bus_xing_out_d_bits_corrupt                                  (_subsystem_sbus_auto_coupler_from_bus_named_subsystem_fbus_bus_xing_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .uart_tsi_io_uart_rxd                                              (uart_tsi_io_uart_rxd),
    .serial_tl_clock                                                   (serial_tl_clock),
    .serial_tl_bits_in_valid                                           (serial_tl_bits_in_valid),
    .serial_tl_bits_in_bits                                            (serial_tl_bits_in_bits),
    .serial_tl_bits_out_ready                                          (serial_tl_bits_out_ready),
    .auto_tlserial_manager_crossing_in_a_ready                         (_subsystem_fbus_auto_tlserial_manager_crossing_in_a_ready),
    .auto_tlserial_manager_crossing_in_d_valid                         (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_valid),
    .auto_tlserial_manager_crossing_in_d_bits_opcode                   (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_opcode),
    .auto_tlserial_manager_crossing_in_d_bits_param                    (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_param),
    .auto_tlserial_manager_crossing_in_d_bits_size                     (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_size),
    .auto_tlserial_manager_crossing_in_d_bits_source                   (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_source),
    .auto_tlserial_manager_crossing_in_d_bits_sink                     (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_sink),
    .auto_tlserial_manager_crossing_in_d_bits_denied                   (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_denied),
    .auto_tlserial_manager_crossing_in_d_bits_data                     (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_data),
    .auto_tlserial_manager_crossing_in_d_bits_corrupt                  (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_corrupt),
    .auto_bus_xing_out_a_valid                                         (_subsystem_fbus_auto_bus_xing_out_a_valid),
    .auto_bus_xing_out_a_bits_opcode                                   (_subsystem_fbus_auto_bus_xing_out_a_bits_opcode),
    .auto_bus_xing_out_a_bits_param                                    (_subsystem_fbus_auto_bus_xing_out_a_bits_param),
    .auto_bus_xing_out_a_bits_size                                     (_subsystem_fbus_auto_bus_xing_out_a_bits_size),
    .auto_bus_xing_out_a_bits_source                                   (_subsystem_fbus_auto_bus_xing_out_a_bits_source),
    .auto_bus_xing_out_a_bits_address                                  (_subsystem_fbus_auto_bus_xing_out_a_bits_address),
    .auto_bus_xing_out_a_bits_mask                                     (_subsystem_fbus_auto_bus_xing_out_a_bits_mask),
    .auto_bus_xing_out_a_bits_data                                     (_subsystem_fbus_auto_bus_xing_out_a_bits_data),
    .auto_bus_xing_out_a_bits_corrupt                                  (_subsystem_fbus_auto_bus_xing_out_a_bits_corrupt),
    .auto_bus_xing_out_d_ready                                         (_subsystem_fbus_auto_bus_xing_out_d_ready),
    .uart_tsi_io_uart_txd                                              (uart_tsi_io_uart_txd),
    .uart_tsi_io_dropped                                               (uart_tsi_io_dropped),
    .uart_tsi_io_tsi2tl_state                                          (uart_tsi_io_tsi2tl_state),
    .serial_tl_bits_in_ready                                           (serial_tl_bits_in_ready),
    .serial_tl_bits_out_valid                                          (serial_tl_bits_out_valid),
    .serial_tl_bits_out_bits                                           (serial_tl_bits_out_bits)
  );
  PeripheryBus_1 subsystem_cbus (	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:31:26]
    .auto_subsystem_cbus_clock_groups_in_member_subsystem_cbus_0_clock (_clockNamePrefixer_auto_clock_name_prefixer_out_4_member_subsystem_cbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_subsystem_cbus_clock_groups_in_member_subsystem_cbus_0_reset (_clockNamePrefixer_auto_clock_name_prefixer_out_4_member_subsystem_cbus_0_reset)	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
  );
  MemoryBus subsystem_mbus (	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_ready      (mem_axi4_0_aw_ready),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_w_ready       (mem_axi4_0_w_ready),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_b_valid       (mem_axi4_0_b_valid),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_b_bits_id     (mem_axi4_0_b_bits_id),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_b_bits_resp   (mem_axi4_0_b_bits_resp),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_ready      (mem_axi4_0_ar_ready),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_r_valid       (mem_axi4_0_r_valid),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_r_bits_id     (mem_axi4_0_r_bits_id),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_r_bits_data   (mem_axi4_0_r_bits_data),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_r_bits_resp   (mem_axi4_0_r_bits_resp),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_r_bits_last   (mem_axi4_0_r_bits_last),
    .auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_clock            (_clockNamePrefixer_auto_clock_name_prefixer_out_3_member_subsystem_mbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_subsystem_mbus_clock_groups_in_member_subsystem_mbus_0_reset            (_clockNamePrefixer_auto_clock_name_prefixer_out_3_member_subsystem_mbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_bus_xing_in_a_valid                                                     (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_bus_xing_in_a_bits_opcode                                               (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_bus_xing_in_a_bits_param                                                (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_bus_xing_in_a_bits_size                                                 (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_bus_xing_in_a_bits_source                                               (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_bus_xing_in_a_bits_address                                              (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_bus_xing_in_a_bits_mask                                                 (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_bus_xing_in_a_bits_data                                                 (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_bus_xing_in_d_ready                                                     (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_valid      (mem_axi4_0_aw_valid),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_bits_id    (mem_axi4_0_aw_bits_id),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_bits_addr  (mem_axi4_0_aw_bits_addr),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_bits_len   (mem_axi4_0_aw_bits_len),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_bits_size  (mem_axi4_0_aw_bits_size),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_bits_burst (mem_axi4_0_aw_bits_burst),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_bits_lock  (mem_axi4_0_aw_bits_lock),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_bits_cache (mem_axi4_0_aw_bits_cache),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_bits_prot  (mem_axi4_0_aw_bits_prot),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_aw_bits_qos   (mem_axi4_0_aw_bits_qos),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_w_valid       (mem_axi4_0_w_valid),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_w_bits_data   (mem_axi4_0_w_bits_data),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_w_bits_strb   (mem_axi4_0_w_bits_strb),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_w_bits_last   (mem_axi4_0_w_bits_last),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_b_ready       (mem_axi4_0_b_ready),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_valid      (mem_axi4_0_ar_valid),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_bits_id    (mem_axi4_0_ar_bits_id),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_bits_addr  (mem_axi4_0_ar_bits_addr),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_bits_len   (mem_axi4_0_ar_bits_len),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_bits_size  (mem_axi4_0_ar_bits_size),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_bits_burst (mem_axi4_0_ar_bits_burst),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_bits_lock  (mem_axi4_0_ar_bits_lock),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_bits_cache (mem_axi4_0_ar_bits_cache),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_bits_prot  (mem_axi4_0_ar_bits_prot),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_ar_bits_qos   (mem_axi4_0_ar_bits_qos),
    .auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_r_ready       (mem_axi4_0_r_ready),
    .auto_fixedClockNode_out_clock                                                (auto_subsystem_mbus_fixedClockNode_out_clock),
    .auto_fixedClockNode_out_reset                                                (auto_subsystem_mbus_fixedClockNode_out_reset),
    .auto_bus_xing_in_a_ready                                                     (_subsystem_mbus_auto_bus_xing_in_a_ready),
    .auto_bus_xing_in_d_valid                                                     (_subsystem_mbus_auto_bus_xing_in_d_valid),
    .auto_bus_xing_in_d_bits_opcode                                               (_subsystem_mbus_auto_bus_xing_in_d_bits_opcode),
    .auto_bus_xing_in_d_bits_size                                                 (_subsystem_mbus_auto_bus_xing_in_d_bits_size),
    .auto_bus_xing_in_d_bits_source                                               (_subsystem_mbus_auto_bus_xing_in_d_bits_source),
    .auto_bus_xing_in_d_bits_denied                                               (_subsystem_mbus_auto_bus_xing_in_d_bits_denied),
    .auto_bus_xing_in_d_bits_data                                                 (_subsystem_mbus_auto_bus_xing_in_d_bits_data),
    .auto_bus_xing_in_d_bits_corrupt                                              (_subsystem_mbus_auto_bus_xing_in_d_bits_corrupt)
  );
  CoherenceManagerWrapper subsystem_l2_wrapper (	// @[generators/rocket-chip/src/main/scala/subsystem/BankedL2Params.scala:47:31]
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_ready        (_subsystem_mbus_auto_bus_xing_in_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_valid        (_subsystem_mbus_auto_bus_xing_in_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_opcode  (_subsystem_mbus_auto_bus_xing_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_size    (_subsystem_mbus_auto_bus_xing_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_source  (_subsystem_mbus_auto_bus_xing_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_denied  (_subsystem_mbus_auto_bus_xing_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_data    (_subsystem_mbus_auto_bus_xing_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_bits_corrupt (_subsystem_mbus_auto_bus_xing_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/MemoryBus.scala:25:26]
    .auto_coherent_jbar_in_a_valid                                        (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coherent_jbar_in_a_bits_opcode                                  (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coherent_jbar_in_a_bits_param                                   (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coherent_jbar_in_a_bits_size                                    (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coherent_jbar_in_a_bits_source                                  (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coherent_jbar_in_a_bits_address                                 (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coherent_jbar_in_a_bits_mask                                    (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coherent_jbar_in_a_bits_data                                    (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coherent_jbar_in_a_bits_corrupt                                 (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coherent_jbar_in_d_ready                                        (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_l2_widget_out_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_subsystem_l2_clock_groups_in_member_subsystem_l2_0_clock        (_subsystem_sbus_auto_subsystem_sbus_clock_groups_out_0_member_subsystem_l2_0_clock),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_subsystem_l2_clock_groups_in_member_subsystem_l2_0_reset        (_subsystem_sbus_auto_subsystem_sbus_clock_groups_out_0_member_subsystem_l2_0_reset),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_valid        (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_valid),
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_opcode  (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_opcode),
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_param   (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_param),
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_size    (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_size),
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_source  (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_source),
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_address (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_address),
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_mask    (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_mask),
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_data    (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_a_bits_data),
    .auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_ready        (_subsystem_l2_wrapper_auto_coupler_to_bus_named_subsystem_mbus_bus_xing_out_d_ready),
    .auto_coherent_jbar_in_a_ready                                        (_subsystem_l2_wrapper_auto_coherent_jbar_in_a_ready),
    .auto_coherent_jbar_in_d_valid                                        (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_valid),
    .auto_coherent_jbar_in_d_bits_opcode                                  (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_opcode),
    .auto_coherent_jbar_in_d_bits_param                                   (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_param),
    .auto_coherent_jbar_in_d_bits_size                                    (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_size),
    .auto_coherent_jbar_in_d_bits_source                                  (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_source),
    .auto_coherent_jbar_in_d_bits_sink                                    (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_sink),
    .auto_coherent_jbar_in_d_bits_denied                                  (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_denied),
    .auto_coherent_jbar_in_d_bits_data                                    (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_data),
    .auto_coherent_jbar_in_d_bits_corrupt                                 (_subsystem_l2_wrapper_auto_coherent_jbar_in_d_bits_corrupt)
  );
  SystemBus_1 subsystem_obus (	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_ready        (_subsystem_fbus_auto_tlserial_manager_crossing_in_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_valid        (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_bits_opcode  (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_bits_param   (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_bits_size    (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_bits_source  (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_bits_sink    (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_bits_denied  (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_bits_data    (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_bits_corrupt (_subsystem_fbus_auto_tlserial_manager_crossing_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/FrontBus.scala:22:26]
    .auto_fixer_in_a_valid                                                                 (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_fixer_in_a_bits_opcode                                                           (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_fixer_in_a_bits_param                                                            (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_fixer_in_a_bits_size                                                             (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_fixer_in_a_bits_source                                                           (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_fixer_in_a_bits_address                                                          (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_fixer_in_a_bits_mask                                                             (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_fixer_in_a_bits_data                                                             (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_fixer_in_a_bits_corrupt                                                          (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_fixer_in_d_ready                                                                 (_subsystem_sbus_auto_coupler_to_bus_named_subsystem_obus_widget_out_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_subsystem_obus_clock_groups_in_member_subsystem_obus_0_clock                     (_subsystem_sbus_auto_subsystem_sbus_clock_groups_out_1_member_subsystem_obus_0_clock),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_subsystem_obus_clock_groups_in_member_subsystem_obus_0_reset                     (_subsystem_sbus_auto_subsystem_sbus_clock_groups_out_1_member_subsystem_obus_0_reset),	// @[generators/rocket-chip/src/main/scala/subsystem/SystemBus.scala:24:26]
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_valid        (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_valid),
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_opcode  (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_opcode),
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_param   (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_param),
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_size    (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_size),
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_source  (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_source),
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_address (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_address),
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_mask    (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_mask),
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_data    (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_data),
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_corrupt (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_a_bits_corrupt),
    .auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_ready        (_subsystem_obus_auto_coupler_to_port_named_serial_tl_mem_tlserial_manager_crossing_out_d_ready),
    .auto_fixer_in_a_ready                                                                 (_subsystem_obus_auto_fixer_in_a_ready),
    .auto_fixer_in_d_valid                                                                 (_subsystem_obus_auto_fixer_in_d_valid),
    .auto_fixer_in_d_bits_opcode                                                           (_subsystem_obus_auto_fixer_in_d_bits_opcode),
    .auto_fixer_in_d_bits_param                                                            (_subsystem_obus_auto_fixer_in_d_bits_param),
    .auto_fixer_in_d_bits_size                                                             (_subsystem_obus_auto_fixer_in_d_bits_size),
    .auto_fixer_in_d_bits_source                                                           (_subsystem_obus_auto_fixer_in_d_bits_source),
    .auto_fixer_in_d_bits_sink                                                             (_subsystem_obus_auto_fixer_in_d_bits_sink),
    .auto_fixer_in_d_bits_denied                                                           (_subsystem_obus_auto_fixer_in_d_bits_denied),
    .auto_fixer_in_d_bits_data                                                             (_subsystem_obus_auto_fixer_in_d_bits_data),
    .auto_fixer_in_d_bits_corrupt                                                          (_subsystem_obus_auto_fixer_in_d_bits_corrupt)
  );
  ClockSinkDomain prci_ctrl_domain (	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:39:36]
    .auto_resetSynchronizer_in_member_allClocks_uncore_clock  (auto_prci_ctrl_domain_resetSynchronizer_in_member_allClocks_uncore_clock),
    .auto_resetSynchronizer_in_member_allClocks_uncore_reset  (auto_prci_ctrl_domain_resetSynchronizer_in_member_allClocks_uncore_reset),
    .auto_resetSynchronizer_out_member_allClocks_uncore_clock (_prci_ctrl_domain_auto_resetSynchronizer_out_member_allClocks_uncore_clock),
    .auto_resetSynchronizer_out_member_allClocks_uncore_reset (_prci_ctrl_domain_auto_resetSynchronizer_out_member_allClocks_uncore_reset)
  );
  ClockGroupAggregator_7 aggregator (	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_in_member_allClocks_subsystem_cbus_0_clock         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_cbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_cbus_0_reset         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_cbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_mbus_0_clock         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_mbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_mbus_0_reset         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_mbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_fbus_0_clock         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_fbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_fbus_0_reset         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_fbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_sbus_2_clock         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_2_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_sbus_2_reset         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_2_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_sbus_1_clock         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_1_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_sbus_1_reset         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_1_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_sbus_0_clock         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_in_member_allClocks_subsystem_sbus_0_reset         (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_out_4_member_subsystem_cbus_subsystem_cbus_0_clock (_aggregator_auto_out_4_member_subsystem_cbus_subsystem_cbus_0_clock),
    .auto_out_4_member_subsystem_cbus_subsystem_cbus_0_reset (_aggregator_auto_out_4_member_subsystem_cbus_subsystem_cbus_0_reset),
    .auto_out_3_member_subsystem_mbus_subsystem_mbus_0_clock (_aggregator_auto_out_3_member_subsystem_mbus_subsystem_mbus_0_clock),
    .auto_out_3_member_subsystem_mbus_subsystem_mbus_0_reset (_aggregator_auto_out_3_member_subsystem_mbus_subsystem_mbus_0_reset),
    .auto_out_2_member_subsystem_fbus_subsystem_fbus_0_clock (_aggregator_auto_out_2_member_subsystem_fbus_subsystem_fbus_0_clock),
    .auto_out_2_member_subsystem_fbus_subsystem_fbus_0_reset (_aggregator_auto_out_2_member_subsystem_fbus_subsystem_fbus_0_reset),
    .auto_out_0_member_subsystem_sbus_subsystem_sbus_2_clock (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_2_clock),
    .auto_out_0_member_subsystem_sbus_subsystem_sbus_2_reset (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_2_reset),
    .auto_out_0_member_subsystem_sbus_subsystem_sbus_1_clock (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_1_clock),
    .auto_out_0_member_subsystem_sbus_subsystem_sbus_1_reset (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_1_reset),
    .auto_out_0_member_subsystem_sbus_subsystem_sbus_0_clock (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_0_clock),
    .auto_out_0_member_subsystem_sbus_subsystem_sbus_0_reset (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_0_reset)
  );
  ClockGroupParameterModifier clockNamePrefixer (	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:45:15]
    .auto_clock_name_prefixer_in_4_member_subsystem_cbus_subsystem_cbus_0_clock (_aggregator_auto_out_4_member_subsystem_cbus_subsystem_cbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_4_member_subsystem_cbus_subsystem_cbus_0_reset (_aggregator_auto_out_4_member_subsystem_cbus_subsystem_cbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_3_member_subsystem_mbus_subsystem_mbus_0_clock (_aggregator_auto_out_3_member_subsystem_mbus_subsystem_mbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_3_member_subsystem_mbus_subsystem_mbus_0_reset (_aggregator_auto_out_3_member_subsystem_mbus_subsystem_mbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_2_member_subsystem_fbus_subsystem_fbus_0_clock (_aggregator_auto_out_2_member_subsystem_fbus_subsystem_fbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_2_member_subsystem_fbus_subsystem_fbus_0_reset (_aggregator_auto_out_2_member_subsystem_fbus_subsystem_fbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_0_member_subsystem_sbus_subsystem_sbus_2_clock (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_2_clock),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_0_member_subsystem_sbus_subsystem_sbus_2_reset (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_2_reset),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_0_member_subsystem_sbus_subsystem_sbus_1_clock (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_1_clock),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_0_member_subsystem_sbus_subsystem_sbus_1_reset (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_1_reset),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_0_member_subsystem_sbus_subsystem_sbus_0_clock (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_in_0_member_subsystem_sbus_subsystem_sbus_0_reset (_aggregator_auto_out_0_member_subsystem_sbus_subsystem_sbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:50:30]
    .auto_clock_name_prefixer_out_4_member_subsystem_cbus_0_clock               (_clockNamePrefixer_auto_clock_name_prefixer_out_4_member_subsystem_cbus_0_clock),
    .auto_clock_name_prefixer_out_4_member_subsystem_cbus_0_reset               (_clockNamePrefixer_auto_clock_name_prefixer_out_4_member_subsystem_cbus_0_reset),
    .auto_clock_name_prefixer_out_3_member_subsystem_mbus_0_clock               (_clockNamePrefixer_auto_clock_name_prefixer_out_3_member_subsystem_mbus_0_clock),
    .auto_clock_name_prefixer_out_3_member_subsystem_mbus_0_reset               (_clockNamePrefixer_auto_clock_name_prefixer_out_3_member_subsystem_mbus_0_reset),
    .auto_clock_name_prefixer_out_2_member_subsystem_fbus_0_clock               (_clockNamePrefixer_auto_clock_name_prefixer_out_2_member_subsystem_fbus_0_clock),
    .auto_clock_name_prefixer_out_2_member_subsystem_fbus_0_reset               (_clockNamePrefixer_auto_clock_name_prefixer_out_2_member_subsystem_fbus_0_reset),
    .auto_clock_name_prefixer_out_0_member_subsystem_sbus_2_clock               (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_2_clock),
    .auto_clock_name_prefixer_out_0_member_subsystem_sbus_2_reset               (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_2_reset),
    .auto_clock_name_prefixer_out_0_member_subsystem_sbus_1_clock               (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_1_clock),
    .auto_clock_name_prefixer_out_0_member_subsystem_sbus_1_reset               (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_1_reset),
    .auto_clock_name_prefixer_out_0_member_subsystem_sbus_0_clock               (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_0_clock),
    .auto_clock_name_prefixer_out_0_member_subsystem_sbus_0_reset               (_clockNamePrefixer_auto_clock_name_prefixer_out_0_member_subsystem_sbus_0_reset)
  );
  ClockGroupParameterModifier_1 frequencySpecifier (	// @[generators/chipyard/src/main/scala/clocking/ClockGroupNamePrefixer.scala:81:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_cbus_0_clock  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_cbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_cbus_0_reset  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_cbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_mbus_0_clock  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_mbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_mbus_0_reset  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_mbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_fbus_0_clock  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_fbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_fbus_0_reset  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_fbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_sbus_2_clock  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_2_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_sbus_2_reset  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_2_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_sbus_1_clock  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_1_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_sbus_1_reset  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_1_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_sbus_0_clock  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_0_clock),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_in_member_allClocks_subsystem_sbus_0_reset  (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_0_reset),	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_frequency_specifier_out_member_allClocks_subsystem_cbus_0_clock (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_cbus_0_clock),
    .auto_frequency_specifier_out_member_allClocks_subsystem_cbus_0_reset (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_cbus_0_reset),
    .auto_frequency_specifier_out_member_allClocks_subsystem_mbus_0_clock (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_mbus_0_clock),
    .auto_frequency_specifier_out_member_allClocks_subsystem_mbus_0_reset (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_mbus_0_reset),
    .auto_frequency_specifier_out_member_allClocks_subsystem_fbus_0_clock (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_fbus_0_clock),
    .auto_frequency_specifier_out_member_allClocks_subsystem_fbus_0_reset (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_fbus_0_reset),
    .auto_frequency_specifier_out_member_allClocks_subsystem_sbus_2_clock (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_2_clock),
    .auto_frequency_specifier_out_member_allClocks_subsystem_sbus_2_reset (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_2_reset),
    .auto_frequency_specifier_out_member_allClocks_subsystem_sbus_1_clock (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_1_clock),
    .auto_frequency_specifier_out_member_allClocks_subsystem_sbus_1_reset (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_1_reset),
    .auto_frequency_specifier_out_member_allClocks_subsystem_sbus_0_clock (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_0_clock),
    .auto_frequency_specifier_out_member_allClocks_subsystem_sbus_0_reset (_frequencySpecifier_auto_frequency_specifier_out_member_allClocks_subsystem_sbus_0_reset)
  );
  ClockGroupCombiner clockGroupCombiner (	// @[generators/chipyard/src/main/scala/clocking/ClockGroupCombiner.scala:19:15]
    .auto_clock_group_combiner_in_member_allClocks_uncore_clock            (_prci_ctrl_domain_auto_resetSynchronizer_out_member_allClocks_uncore_clock),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:39:36]
    .auto_clock_group_combiner_in_member_allClocks_uncore_reset            (_prci_ctrl_domain_auto_resetSynchronizer_out_member_allClocks_uncore_reset),	// @[generators/chipyard/src/main/scala/clocking/HasChipyardPRCI.scala:39:36]
    .auto_clock_group_combiner_out_member_allClocks_subsystem_cbus_0_clock (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_cbus_0_clock),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_cbus_0_reset (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_cbus_0_reset),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_mbus_0_clock (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_mbus_0_clock),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_mbus_0_reset (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_mbus_0_reset),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_fbus_0_clock (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_fbus_0_clock),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_fbus_0_reset (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_fbus_0_reset),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_2_clock (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_2_clock),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_2_reset (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_2_reset),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_1_clock (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_1_clock),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_1_reset (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_1_reset),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_0_clock (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_0_clock),
    .auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_0_reset (_clockGroupCombiner_auto_clock_group_combiner_out_member_allClocks_subsystem_sbus_0_reset)
  );
endmodule

