// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module Queue_41(
  input         clock,
                reset,
                io_enq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  input  [6:0]  io_enq_bits_id,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  input  [32:0] io_enq_bits_addr,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  input  [7:0]  io_enq_bits_len,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  input  [2:0]  io_enq_bits_size,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  input  [3:0]  io_enq_bits_echo_tl_state_size,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  input  [6:0]  io_enq_bits_echo_tl_state_source,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  input         io_enq_bits_wen,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
                io_deq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output        io_enq_ready,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
                io_deq_valid,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output [6:0]  io_deq_bits_id,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output [32:0] io_deq_bits_addr,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output [7:0]  io_deq_bits_len,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output [2:0]  io_deq_bits_size,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output [1:0]  io_deq_bits_burst,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output        io_deq_bits_lock,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output [3:0]  io_deq_bits_cache,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output [2:0]  io_deq_bits_prot,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output [3:0]  io_deq_bits_qos,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
                io_deq_bits_echo_tl_state_size,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output [6:0]  io_deq_bits_echo_tl_state_source,	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
  output        io_deq_bits_wen	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
);

  wire        _io_enq_ready_output;	// @[src/main/scala/chisel3/util/Decoupled.scala:304:16, :324:{24,39}]
  wire [76:0] _ram_ext_R0_data;	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  reg         maybe_full;	// @[src/main/scala/chisel3/util/Decoupled.scala:277:27]
  wire        do_enq = _io_enq_ready_output & io_enq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35, :304:16, :324:{24,39}]
  assign _io_enq_ready_output = io_deq_ready | ~maybe_full;	// @[src/main/scala/chisel3/util/Decoupled.scala:277:27, :304:{16,19}, :324:{24,39}]
  always @(posedge clock) begin
    if (reset)
      maybe_full <= 1'h0;	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14, :277:27]
    else if (do_enq != (io_deq_ready & maybe_full))	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35, :277:27, :294:15]
      maybe_full <= do_enq;	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35, :277:27]
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        maybe_full = _RANDOM_0[0];	// @[src/main/scala/chisel3/util/Decoupled.scala:277:27]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  ram_combMem_3 ram_ext (	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
    .R0_addr (1'h0),	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .W0_addr (1'h0),	// @[src/main/scala/chisel3/util/Decoupled.scala:273:14]
    .W0_en   (do_enq),	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
    .W0_clk  (clock),
    .W0_data ({io_enq_bits_wen, io_enq_bits_echo_tl_state_source, io_enq_bits_echo_tl_state_size, 14'h81, io_enq_bits_size, io_enq_bits_len, io_enq_bits_addr, io_enq_bits_id}),	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
    .R0_data (_ram_ext_R0_data)
  );
  assign io_enq_ready = _io_enq_ready_output;	// @[src/main/scala/chisel3/util/Decoupled.scala:304:16, :324:{24,39}]
  assign io_deq_valid = maybe_full;	// @[src/main/scala/chisel3/util/Decoupled.scala:277:27]
  assign io_deq_bits_id = _ram_ext_R0_data[6:0];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_addr = _ram_ext_R0_data[39:7];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_len = _ram_ext_R0_data[47:40];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_size = _ram_ext_R0_data[50:48];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_burst = _ram_ext_R0_data[52:51];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_lock = _ram_ext_R0_data[53];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_cache = _ram_ext_R0_data[57:54];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_prot = _ram_ext_R0_data[60:58];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_qos = _ram_ext_R0_data[64:61];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_echo_tl_state_size = _ram_ext_R0_data[68:65];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_echo_tl_state_source = _ram_ext_R0_data[75:69];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
  assign io_deq_bits_wen = _ram_ext_R0_data[76];	// @[src/main/scala/chisel3/util/Decoupled.scala:274:95]
endmodule

