package chipyard

import chisel3._
import freechips.rocketchip.config.{Config, Field}

case class BindingTableParams (val arg: String)

case object BindingTableType extends Field[BindingTableParams](null)

class WithRoboBindingTable extends Config((site, here, up) => {
  case BindingTableType => BindingTableParams("robo")
})

class WithBearlyBindingTable extends Config((site, here, up) => {
  case BindingTableType => BindingTableParams("bearly")
})

case class SignalBinderConnection(
  slice_type : String, slice_inst : Int, bit : Int,
  val drv2 : Bool, drv1 : Bool, drv0 : Bool, enq : Bool,
  val enabq : Bool, pd : Bool, puq : Bool, ppen : Bool, 
  val prg_slew : Bool, pwrup_pull_en : Bool,  pwrupzhl : Bool)

object SigTable {
    val bearlySigBinderTable = Map[String, SignalBinderConnection] (
      // 10 : input
      // 01 : output
        //                                                                                 bit                drv[0]                 pd                      pwrup_pull_en
        //                                                                            inst  |          drv[1]   |           enabq    |      puq          prg_slew  |
        //                                                                 slice type  |    |   drv[2]   |      |     enq     |      |      |     ppen    |      |   pwrupzhl
        //                                                                      |      |    |     |      |      |      |      |      |      |      |      |      |      |
        "clock"                                  -> new SignalBinderConnection("W" ,   4,   1,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "clock_debug"                            -> new SignalBinderConnection("W" ,   5,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "custom_boot"                            -> new SignalBinderConnection("W" ,   5,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "gpio_0_0"                               -> new SignalBinderConnection("C" ,   0,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_1"                               -> new SignalBinderConnection("C" ,   0,   9,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_10"                              -> new SignalBinderConnection("S" ,   2,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_11"                              -> new SignalBinderConnection("S" ,   2,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_12"                              -> new SignalBinderConnection("S" ,   2,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_13"                              -> new SignalBinderConnection("S" ,   2,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_14"                              -> new SignalBinderConnection("S" ,   3,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_15"                              -> new SignalBinderConnection("S" ,   3,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_16"                              -> new SignalBinderConnection("S" ,   3,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_17"                              -> new SignalBinderConnection("S" ,   3,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_18"                              -> new SignalBinderConnection("S" ,   4,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_19"                              -> new SignalBinderConnection("S" ,   4,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_2"                               -> new SignalBinderConnection("S" ,   0,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_20"                              -> new SignalBinderConnection("S" ,   4,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_21"                              -> new SignalBinderConnection("S" ,   4,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_22"                              -> new SignalBinderConnection("S" ,   5,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_23"                              -> new SignalBinderConnection("S" ,   5,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_24"                              -> new SignalBinderConnection("S" ,   5,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_25"                              -> new SignalBinderConnection("S" ,   5,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_26"                              -> new SignalBinderConnection("S" ,   6,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_27"                              -> new SignalBinderConnection("S" ,   6,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_28"                              -> new SignalBinderConnection("S" ,   6,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_29"                              -> new SignalBinderConnection("S" ,   6,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_3"                               -> new SignalBinderConnection("S" ,   0,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_30"                              -> new SignalBinderConnection("S" ,   7,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_31"                              -> new SignalBinderConnection("S" ,   7,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_4"                               -> new SignalBinderConnection("S" ,   0,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_5"                               -> new SignalBinderConnection("S" ,   0,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_6"                               -> new SignalBinderConnection("S" ,   1,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_7"                               -> new SignalBinderConnection("S" ,   1,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_8"                               -> new SignalBinderConnection("S" ,   1,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_9"                               -> new SignalBinderConnection("S" ,   1,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_1_0"                               -> new SignalBinderConnection("W" ,   6,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_1_1"                               -> new SignalBinderConnection("W" ,   6,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_1_2"                               -> new SignalBinderConnection("W" ,   5,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_0"                               -> new SignalBinderConnection("S" ,   0,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_1"                               -> new SignalBinderConnection("S" ,   0,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_10"                              -> new SignalBinderConnection("S" ,   7,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_11"                              -> new SignalBinderConnection("S" ,   8,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_12"                              -> new SignalBinderConnection("S" ,   8,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_13"                              -> new SignalBinderConnection("C" ,   0,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_14"                              -> new SignalBinderConnection("C" ,   0,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_15"                              -> new SignalBinderConnection("C" ,   0,   8,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_16"                              -> new SignalBinderConnection("C" ,   0,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_2"                               -> new SignalBinderConnection("S" ,   1,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_3"                               -> new SignalBinderConnection("S" ,   1,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_4"                               -> new SignalBinderConnection("S" ,   2,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_5"                               -> new SignalBinderConnection("S" ,   2,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_6"                               -> new SignalBinderConnection("S" ,   3,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_7"                               -> new SignalBinderConnection("S" ,   4,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_8"                               -> new SignalBinderConnection("S" ,   6,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_9"                               -> new SignalBinderConnection("S" ,   7,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_3_0"                               -> new SignalBinderConnection("W" ,   8,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_3_1"                               -> new SignalBinderConnection("W" ,   8,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_3_2"                               -> new SignalBinderConnection("W" ,   8,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_3_3"                               -> new SignalBinderConnection("W" ,   8,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_3_4"                               -> new SignalBinderConnection("W" ,   7,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_3_5"                               -> new SignalBinderConnection("W" ,   7,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_3_6"                               -> new SignalBinderConnection("W" ,   7,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_3_7"                               -> new SignalBinderConnection("W" ,   7,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "i2c_0_scl"                              -> new SignalBinderConnection("W" ,   4,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B),
        "i2c_0_sda"                              -> new SignalBinderConnection("W" ,   4,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B),
        "i2c_1_scl"                              -> new SignalBinderConnection("W" ,   6,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B),
        "i2c_1_sda"                              -> new SignalBinderConnection("W" ,   6,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B),
        "jtag_TCK"                               -> new SignalBinderConnection("W" ,   0,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "jtag_TDI"                               -> new SignalBinderConnection("W" ,   1,   1,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "jtag_TDO"                               -> new SignalBinderConnection("W" ,   1,   3,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "jtag_TMS"                               -> new SignalBinderConnection("W" ,   1,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "lock"                                   -> new SignalBinderConnection("W" ,   3,   2,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxi_jtag_trstb"                  -> new SignalBinderConnection("W" ,   1,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "xxi_link_up_fwr"                -> new SignalBinderConnection("W" ,   0,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxo_link_up_ldr"                -> new SignalBinderConnection("W" ,   0,   3,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxo_loopback_clk"               -> new SignalBinderConnection("W" ,   3,   3,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxi_pll_bypass"                 -> new SignalBinderConnection("W" ,   2,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxi_powergood"              -> new SignalBinderConnection("W" ,   2,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxo_reset_out"                  -> new SignalBinderConnection("W" ,   3,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pll_in"                                 -> new SignalBinderConnection("W" ,   0,   0,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "pwm_0_pwm_0"                            -> new SignalBinderConnection("S" ,   7,   5,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_0_pwm_1"                            -> new SignalBinderConnection("S" ,   7,   7,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_0_pwm_2"                            -> new SignalBinderConnection("S" ,   8,   4,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_0_pwm_3"                            -> new SignalBinderConnection("S" ,   8,   6,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_1_pwm_1"                            -> new SignalBinderConnection("S" ,   8,   7,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_1_pwm_0"                            -> new SignalBinderConnection("S" ,   8,   5,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_cs_0"                            -> new SignalBinderConnection("S" ,   6,   2,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_dq_0"                            -> new SignalBinderConnection("S" ,   6,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_dq_1"                            -> new SignalBinderConnection("S" ,   7,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_dq_2"                            -> new SignalBinderConnection("S" ,   7,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_dq_3"                            -> new SignalBinderConnection("S" ,   8,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_sck"                             -> new SignalBinderConnection("S" ,   8,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_cs_0"                            -> new SignalBinderConnection("S" ,   6,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_dq_0"                            -> new SignalBinderConnection("S" ,   5,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_dq_1"                            -> new SignalBinderConnection("S" ,   5,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_dq_2"                            -> new SignalBinderConnection("S" ,   5,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_dq_3"                            -> new SignalBinderConnection("S" ,   5,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_sck"                             -> new SignalBinderConnection("S" ,   4,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "reset"                                  -> new SignalBinderConnection("W" ,   2,   0,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_in_bits"                 -> new SignalBinderConnection("S" ,   0,   0,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_in_ready"                -> new SignalBinderConnection("S" ,   1,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_in_valid"                -> new SignalBinderConnection("S" ,   0,   1,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_out_bits"                -> new SignalBinderConnection("S" ,   1,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_out_ready"               -> new SignalBinderConnection("S" ,   2,   1,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_out_valid"               -> new SignalBinderConnection("S" ,   2,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_clock"                        -> new SignalBinderConnection("S" ,   3,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "spi_1_cs_0"                             -> new SignalBinderConnection("S" ,   3,   3,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "spi_1_miso"                             -> new SignalBinderConnection("S" ,   4,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "spi_1_mosi"                             -> new SignalBinderConnection("S" ,   4,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "spi_1_sck"                              -> new SignalBinderConnection("S" ,   3,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_0_rxd"                             -> new SignalBinderConnection("W" ,   2,   3,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_0_txd"                             -> new SignalBinderConnection("W" ,   3,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_1_rxd"                             -> new SignalBinderConnection("C" ,   0,   3,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_1_txd"                             -> new SignalBinderConnection("C" ,   0,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_2_rxd"                             -> new SignalBinderConnection("C" ,   0,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_2_txd"                             -> new SignalBinderConnection("C" ,   0,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B))
   
    val roboSigBinderTable = Map[String, SignalBinderConnection] (
        //                                                                                 bit                drv[0]                 pd                   pwrup_pull_en
        //                                                                            inst  |          drv[1]   |           enabq    |     puq         prg_slew  |
        //                                                                 slice type  |    |   drv[2]   |      |     enq     |      |      |     ppen    |      |   pwrupzhl
        //                                                                      |      |    |     |      |      |      |      |      |      |      |      |      |      |
        "clock"                                  -> new SignalBinderConnection("W" ,   4,   1,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "clock_debug"                            -> new SignalBinderConnection("W" ,   5,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "clwsw_ext"                              -> new SignalBinderConnection("W" ,   7,   1,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "custom_boot"                            -> new SignalBinderConnection("W" ,   5,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "gpio_0_0"                               -> new SignalBinderConnection("C" ,   0,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_1"                               -> new SignalBinderConnection("C" ,   0,   9,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_10"                              -> new SignalBinderConnection("S" ,   2,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_11"                              -> new SignalBinderConnection("S" ,   2,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_12"                              -> new SignalBinderConnection("S" ,   2,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_13"                              -> new SignalBinderConnection("S" ,   2,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_14"                              -> new SignalBinderConnection("S" ,   3,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_15"                              -> new SignalBinderConnection("S" ,   3,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_16"                              -> new SignalBinderConnection("S" ,   3,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_17"                              -> new SignalBinderConnection("S" ,   3,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_18"                              -> new SignalBinderConnection("S" ,   4,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_19"                              -> new SignalBinderConnection("S" ,   4,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_2"                               -> new SignalBinderConnection("S" ,   0,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_20"                              -> new SignalBinderConnection("S" ,   4,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_21"                              -> new SignalBinderConnection("S" ,   4,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_22"                              -> new SignalBinderConnection("S" ,   5,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_23"                              -> new SignalBinderConnection("S" ,   5,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_24"                              -> new SignalBinderConnection("S" ,   5,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_25"                              -> new SignalBinderConnection("S" ,   5,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_26"                              -> new SignalBinderConnection("S" ,   6,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_27"                              -> new SignalBinderConnection("S" ,   6,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_28"                              -> new SignalBinderConnection("S" ,   6,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_29"                              -> new SignalBinderConnection("S" ,   6,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_3"                               -> new SignalBinderConnection("S" ,   0,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_30"                              -> new SignalBinderConnection("S" ,   7,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_31"                              -> new SignalBinderConnection("S" ,   7,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_4"                               -> new SignalBinderConnection("S" ,   0,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_5"                               -> new SignalBinderConnection("S" ,   0,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_6"                               -> new SignalBinderConnection("S" ,   1,   4,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_7"                               -> new SignalBinderConnection("S" ,   1,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_8"                               -> new SignalBinderConnection("S" ,   1,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_0_9"                               -> new SignalBinderConnection("S" ,   1,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_1_0"                               -> new SignalBinderConnection("W" ,   6,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_1_1"                               -> new SignalBinderConnection("W" ,   6,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_1_2"                               -> new SignalBinderConnection("W" ,   5,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_0"                               -> new SignalBinderConnection("S" ,   0,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_1"                               -> new SignalBinderConnection("S" ,   0,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_10"                              -> new SignalBinderConnection("S" ,   7,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_11"                              -> new SignalBinderConnection("S" ,   8,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_12"                              -> new SignalBinderConnection("S" ,   8,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_13"                              -> new SignalBinderConnection("C" ,   0,   5,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_14"                              -> new SignalBinderConnection("C" ,   0,   7,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_15"                              -> new SignalBinderConnection("C" ,   0,   8,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_16"                              -> new SignalBinderConnection("C" ,   0,   6,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_2"                               -> new SignalBinderConnection("S" ,   1,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_3"                               -> new SignalBinderConnection("S" ,   1,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_4"                               -> new SignalBinderConnection("S" ,   2,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_5"                               -> new SignalBinderConnection("S" ,   2,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_6"                               -> new SignalBinderConnection("S" ,   3,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_7"                               -> new SignalBinderConnection("S" ,   4,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_8"                               -> new SignalBinderConnection("S" ,   6,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "gpio_2_9"                               -> new SignalBinderConnection("S" ,   7,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "i2c_0_scl"                              -> new SignalBinderConnection("W" ,   4,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B),
        "i2c_0_sda"                              -> new SignalBinderConnection("W" ,   4,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B),
        "i2c_1_scl"                              -> new SignalBinderConnection("W" ,   6,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B),
        "i2c_1_sda"                              -> new SignalBinderConnection("W" ,   6,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B),
        "jtag_TCK"                               -> new SignalBinderConnection("W" ,   0,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "jtag_TDI"                               -> new SignalBinderConnection("W" ,   1,   1,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "jtag_TDO"                               -> new SignalBinderConnection("W" ,   1,   3,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "jtag_TMS"                               -> new SignalBinderConnection("W" ,   1,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "lock"                                   -> new SignalBinderConnection("W" ,   3,   2,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxi_jtag_trstb"                  -> new SignalBinderConnection("W" ,   1,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "xxi_link_up_fwr"                -> new SignalBinderConnection("W" ,   0,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxo_link_up_ldr"                -> new SignalBinderConnection("W" ,   0,   3,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxo_loopback_clk"               -> new SignalBinderConnection("W" ,   3,   3,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxi_pll_bypass"                 -> new SignalBinderConnection("W" ,   2,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxi_powergood"              -> new SignalBinderConnection("W" ,   2,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "xxo_reset_out"                  -> new SignalBinderConnection("W" ,   3,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pll_in"                                 -> new SignalBinderConnection("W" ,   0,   0,   0.B,   0.B,   0.B,   1.B,   0.B,   0.B,   1.B,   0.B,   0.B,   0.B,   0.B),
        "pwm_0_pwm_0"                            -> new SignalBinderConnection("S" ,   7,   5,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_0_pwm_1"                            -> new SignalBinderConnection("S" ,   7,   7,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_0_pwm_2"                            -> new SignalBinderConnection("S" ,   8,   4,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_0_pwm_3"                            -> new SignalBinderConnection("S" ,   8,   6,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_1_pwm_0"                            -> new SignalBinderConnection("S" ,   8,   5,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "pwm_1_pwm_1"                            -> new SignalBinderConnection("S" ,   8,   7,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_cs_0"                            -> new SignalBinderConnection("S" ,   6,   2,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_dq_0"                            -> new SignalBinderConnection("S" ,   6,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_dq_1"                            -> new SignalBinderConnection("S" ,   7,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_dq_2"                            -> new SignalBinderConnection("S" ,   7,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_dq_3"                            -> new SignalBinderConnection("S" ,   8,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_0_sck"                             -> new SignalBinderConnection("S" ,   8,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_cs_0"                            -> new SignalBinderConnection("S" ,   6,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_dq_0"                            -> new SignalBinderConnection("S" ,   5,   0,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_dq_1"                            -> new SignalBinderConnection("S" ,   5,   2,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_dq_2"                            -> new SignalBinderConnection("S" ,   5,   1,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_dq_3"                            -> new SignalBinderConnection("S" ,   5,   3,   0.B,   0.B,   0.B,   0.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "qspi_1_sck"                             -> new SignalBinderConnection("S" ,   4,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "reset"                                  -> new SignalBinderConnection("W" ,   2,   0,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_in_bits"                 -> new SignalBinderConnection("S" ,   0,   0,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_in_ready"                -> new SignalBinderConnection("S" ,   1,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_in_valid"                -> new SignalBinderConnection("S" ,   0,   1,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_out_bits"                -> new SignalBinderConnection("S" ,   1,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_out_ready"               -> new SignalBinderConnection("S" ,   2,   1,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_bits_out_valid"               -> new SignalBinderConnection("S" ,   2,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "serial_tl_clock"                        -> new SignalBinderConnection("S" ,   3,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "spi_1_cs_0"                             -> new SignalBinderConnection("S" ,   3,   3,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "spi_1_miso"                             -> new SignalBinderConnection("S" ,   4,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "spi_1_mosi"                             -> new SignalBinderConnection("S" ,   4,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "spi_1_sck"                              -> new SignalBinderConnection("S" ,   3,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_0_rxd"                             -> new SignalBinderConnection("W" ,   2,   3,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_0_txd"                             -> new SignalBinderConnection("W" ,   3,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_1_rxd"                             -> new SignalBinderConnection("C" ,   0,   3,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_1_txd"                             -> new SignalBinderConnection("C" ,   0,   1,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_2_rxd"                             -> new SignalBinderConnection("C" ,   0,   2,   0.B,   0.B,   1.B,   1.B,   0.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B),
        "uart_2_txd"                             -> new SignalBinderConnection("C" ,   0,   0,   0.B,   0.B,   1.B,   0.B,   1.B,   0.B,   1.B,   1.B,   1.B,   0.B,   0.B))
}
